### ISSUE TITLE
compactor does not join peer

### ISSUE THREAD

**Issue by aslimacc** [improbable-eng/thanos#1020]
**Thanos, Prometheus and Golang version used**
Thanos: v0.3.2
Prometheus: v2.7.1

**What happened**
Hello,
I have configured Prometheus Operator with Thanos (all components except Ruler and Compactor)

I did not have error in the logs of thanos-sidecar.

Since I have deployed Compactor, my thanos-sidecar cannot see compactor and I see error on logs in thanos-sidecar.

In my thanos-compactor configuration, the container port open is just 10902. Even if I open the 10902 port, I have the same error

**What you expected to happen**

I expect that compactor join peers.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

<details>Logs
<p>

```
level=error ts=2019-04-11T10:05:23.126470636Z caller=cluster.go:269 component=cluster msg="Refreshing memberlist" err="join peers 10.44.2.20:10900 : 1 error occurred:\n\t* Failed to join 10.44.2.20: dial tcp 10.44.2.20:10900: connect: connection refused\n\n"
```

</p>
</details>

**Anything else we need to know**

The ip address (10.44.2.20) is the pod/endpoint ip address of thanos compactor.

**Comment by bwplotka** [comment]
Why would you like sidecar to see compactor? (: The only connection needed is from Querier to StoreAPIs, compactor is not part of any of this.

You can read more about this and why gossip will be removed here: https://github.com/improbable-eng/thanos/blob/master/docs/proposals/approved/201809_gossip-removal.md
