### ISSUE TITLE
ui: Metric name feedback while typing is laggy

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#1043]
It has problems with large number of StoreAPIs (or maybe just large cardinality)?

I can see `api/v1/label/__name__/values?_=1555502472519` succeededs however UI is not giving you feedback all the time. This must some frontend/caching issue on browser side.

Might be solved by: https://github.com/improbable-eng/thanos/issues/1042

**Comment by GiedriusS** [comment]
The UI with #1042 is smooth as butter for me. @bwplotka could you double-check if that's true on your end as well? Then we could close this ticket.

**Comment by bwplotka** [comment]
Works for me (:
