### ISSUE TITLE
Compactor Crash on overlapping compaction

### ISSUE THREAD

**Issue by jstewart612** [improbable-eng/thanos#1044]
**Thanos, Prometheus and Golang version used**
master-2019-04-17-6703f14

**What happened**
Thanos Compact crashed!
**What you expected to happen**
Not to crash!  Give me options of how to address overlaps such as preferring one over the other, or warning but not otherwise dying outright.
**How to reproduce it (as minimally and precisely as possible)**:
Unsure.  It happens to me whenever I start the Thanos Compact in a specific data center.
**Full logs to relevant components**
```thanos_compact.1.o30sv2id79ik@thanos-cluster001.tools.useast2.rentpath.com    | {"caller":"main.go:182","err":"error executing compaction: compaction failed: compaction failed for group 0@{monitor=\"\",region=\"useast2\"}: pre compaction overlap check: overlaps found while gathering blocks. [mint: 1555473600000, maxt: 1555480800000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8N1GPPC453TBFJQK8AY7M69, mint: 1555473600000, maxt: 1555480800000, range: 2h0m0s\u003e, \u003culid: 01D8N1GPKKCFVF7KGWB3EJXN5E, mint: 1555473600000, maxt: 1555480800000, range: 2h0m0s\u003e\n[mint: 1555480800000, maxt: 1555488000000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8N8CDYC5ZHQKGFSVH91CRZ4, mint: 1555480800000, maxt: 1555488000000, range: 2h0m0s\u003e, \u003culid: 01D8N8CDVK34E1K2RN9N7TNJ0S, mint: 1555480800000, maxt: 1555488000000, range: 2h0m0s\u003e\n[mint: 1555488000000, maxt: 1555495200000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8NF853J26WM9FFF3Z0TMT92, mint: 1555488000000, maxt: 1555495200000, range: 2h0m0s\u003e, \u003culid: 01D8NF856CGKD6BNKP80Y7A7EX, mint: 1555488000000, maxt: 1555495200000, range: 2h0m0s\u003e\n[mint: 1555495200000, maxt: 1555502400000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8NP3WBKMGEJ7CTZ6HSZ90H8, mint: 1555495200000, maxt: 1555502400000, range: 2h0m0s\u003e, \u003culid: 01D8NP3WEC8RYHCVQMHW6SJY6A, mint: 1555495200000, maxt: 1555502400000, range: 2h0m0s\u003e\n[mint: 1555509600000, maxt: 1555516800000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8P3VAYCS1GFV8A1G6VW4Q0M, mint: 1555509600000, maxt: 1555516800000, range: 2h0m0s\u003e, \u003culid: 01D8P3VAVPQ56CVPGW3HNAS213, mint: 1555509600000, maxt: 1555516800000, range: 2h0m0s\u003e\n[mint: 1555444800000, maxt: 1555452000000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8M61SKK2RTNMN1V7SF5ZC7X, mint: 1555444800000, maxt: 1555452000000, range: 2h0m0s\u003e, \u003culid: 01D8M61SPCFGCXWYFAFFKB9CXN, mint: 1555444800000, maxt: 1555452000000, range: 2h0m0s\u003e\n[mint: 1555452000000, maxt: 1555459200000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8MCXGVKQJ5TH10QNM54V50T, mint: 1555452000000, maxt: 1555459200000, range: 2h0m0s\u003e, \u003culid: 01D8MCXGYC1ZWYJZ4HKD1MPHTZ, mint: 1555452000000, maxt: 1555459200000, range: 2h0m0s\u003e\n[mint: 1555459200000, maxt: 1555466400000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8MKS83KYW3FZJTRGCZ8RM0D, mint: 1555459200000, maxt: 1555466400000, range: 2h0m0s\u003e, \u003culid: 01D8MKS86CS5XW552NNVVB644T, mint: 1555459200000, maxt: 1555466400000, range: 2h0m0s\u003e\n[mint: 1555432013259, maxt: 1555437600000, range: 1h33m6s, blocks: 2]: \u003culid: 01D8KRAB3JZTXPTY554HWQS0BJ, mint: 1555430400000, maxt: 1555437600000, range: 2h0m0s\u003e, \u003culid: 01D8KSVJDTW0WWTKXS0D4MVKAJ, mint: 1555432013259, maxt: 1555437600000, range: 1h33m6s\u003e\n[mint: 1555502400000, maxt: 1555509600000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8NWZKPCKCQSN7WKB2XNH3T0, mint: 1555502400000, maxt: 1555509600000, range: 2h0m0s\u003e, \u003culid: 01D8NWZKKKEVPG8GQRY0AGAMDN, mint: 1555502400000, maxt: 1555509600000, range: 2h0m0s\u003e\n[mint: 1555531200000, maxt: 1555538400000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8PREGKKYKVBRDVD2VPVG0ZZ, mint: 1555531200000, maxt: 1555538400000, range: 2h0m0s\u003e, \u003culid: 01D8PREGPCY11K1818X5KHP5Z7, mint: 1555531200000, maxt: 1555538400000, range: 2h0m0s\u003e\n[mint: 1555516800000, maxt: 1555524000000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8PAQ26Q1QPJ43SBRGKSCR83, mint: 1555516800000, maxt: 1555524000000, range: 2h0m0s\u003e, \u003culid: 01D8PAQ23KVABCTKKB5XWF7PWB, mint: 1555516800000, maxt: 1555524000000, range: 2h0m0s\u003e\n[mint: 1555437600000, maxt: 1555444800000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8KZ62EETD54QD500KKHVC0J, mint: 1555437600000, maxt: 1555444800000, range: 2h0m0s\u003e, \u003culid: 01D8KZ62BKZW5CXVGSZTBPGDY0, mint: 1555437600000, maxt: 1555444800000, range: 2h0m0s\u003e\n[mint: 1555466400000, maxt: 1555473600000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8MTMZECDM6FV1QH0J2GE7VZ, mint: 1555466400000, maxt: 1555473600000, range: 2h0m0s\u003e, \u003culid: 01D8MTMZBKXMT6FEXW5G611JYQ, mint: 1555466400000, maxt: 1555473600000, range: 2h0m0s\u003e\n[mint: 1555524000000, maxt: 1555531200000, range: 2h0m0s, blocks: 2]: \u003culid: 01D8PHJSECJ2FMFA19GC9Y25AY, mint: 1555524000000, maxt: 1555531200000, range: 2h0m0s\u003e, \u003culid: 01D8PHJSBKZ35CDTQ56XW4PNZB, mint: 1555524000000, maxt: 1555531200000, range: 2h0m0s\u003e","level":"error","msg":"running command failed","ts":"2019-04-17T23:41:30.398911732Z"}```

**Anything else we need to know**

**Comment by rafaeljesus** [comment]
Do you have ruler in HA mode enabled?

**Comment by bwplotka** [comment]
Please find out why your blocks overlaps. It is useful to go to meta.json and checkout the type and `ID`. Check `ID` with your source logs that were producing those, check out why and with that external labels. 

External labels are the most common way to get into overlapped blocks. Also local & global compaction enabled is another reason.

Plus, what would you expect? I don't think it would be nice for Thanos to remove random block that overlap.

**Comment by jstewart612** [comment]
@bwplotka how do I do that

@rafaeljesus no

**Comment by jstewart612** [comment]
Well.... it sure helps when you don't give two scrapers in two different environments IDENTICAL BLANK EXTERNAL LABELS.  OUCH.

Self-inflicted user error.  I'm not a smart man today :D
