### ISSUE TITLE
[Question] How to monitor Thanos for "no space left on device" or "out of memory" can we add such to /metrics 

### ISSUE THREAD

**Issue by Alexvianet** [improbable-eng/thanos#1047]
How to monitor Thanos for "no space left on device" or "out of memory" can we add such to /metrics

**Comment by bwplotka** [comment]
So memory and CPU usage is part of Golang metrics, but I would focus to monitor "host" that Thanos is running on. E.g docker container (e.g cAdvisor metrics for cpu, mem, disk, network limits and usage), or Node metrics if it's bare node.

**Comment by povilasv** [comment]
"no space left on device" is a node problem so I suggest you use https://github.com/prometheus/node_exporter to get metrics for it
