### ISSUE TITLE
thanos compact upload downsampled block fails because meta.json is missing

### ISSUE THREAD

**Issue by azhelev** [improbable-eng/thanos#1054]
**Thanos, Prometheus and Golang version used**
docker image improbable/thanos:master-2019-04-18-3b9afb4
prometheus 2.9.0

**What happened**
thanos compact failed to upload a newly downsampled block because meta.json was missing
```
level=info ts=2019-04-18T16:45:34.762214609Z caller=downsample.go:239 msg="downsampled block" from=01D8RHXW63HW8X6V3TCHQHKM5H to=01D8RMBBZ2W9K8RYTG2TV8NPT5 duration=18m44.632381984s
level=error ts=2019-04-18T16:45:54.640332573Z caller=main.go:182 msg="running command failed" err="error executing compaction: first pass of downsampling failed: downsampling to 5 min: upload downsampled block 01D8RMBBZ2W9K8RYTG2TV8NPT5: read meta: open /data/downsample/01D8RMBBZ2W9K8RYTG2TV8NPT5/meta.json: no such file or directory"
```
the source block 01D8RHXW63HW8X6V3TCHQHKM5H has a meta.json file stored in the s3 bucket

**What you expected to happen**
downsampled block successfully uploaded

**How to reproduce it (as minimally and precisely as possible)**:
run thanos compact

**Full logs to relevant components**

**Anything else we need to know**
Running on kubernetes 1.11.8 in AWS, object storage in S3

**Comment by bwplotka** [comment]
Dup fo https://github.com/improbable-eng/thanos/issues/621
