### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by soledad000** [improbable-eng/thanos#1061]
After download thanos, I run `make build`, then it have the error :

go: k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93: unrecognized import path "k8s.io/apimachinery" (https fetch: Get https://k8s.io/apimachinery?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: sigs.k8s.io/yaml@v1.1.0: unrecognized import path "sigs.k8s.io/yaml" (https fetch: Get https://sigs.k8s.io/yaml?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/api@v0.0.0-20181213150558-05914d821849: unrecognized import path "k8s.io/api" (https fetch: Get https://k8s.io/api?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/kube-openapi@v0.0.0-20180629012420-d83b052f768a: unrecognized import path "k8s.io/kube-openapi" (https fetch: Get https://k8s.io/kube-openapi?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/klog@v0.1.0: unrecognized import path "k8s.io/klog" (https fetch: Get https://k8s.io/klog?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: error loading module requirements
Makefile:205: recipe for target 'go-mod-tidy' failed
make: *** [go-mod-tidy] Error 1

It may be i could not get the k8s , so may network error?

**Comment by jojohappy** [comment]
Maybe you could not fetch the dependency packages from the https://k8s.io repo, please check your network environment, ping or curl.

**Comment by soledad000** [comment]
> Maybe you could not fetch the dependency packages from the https://k8s.io repo, please check your network environment, ping or curl.

yes,I can not get the  https://k8s.io repo, may I have other way to get the k8s.io, or install thanos?

**Comment by soledad000** [comment]
> Maybe you could not fetch the dependency packages from the https://k8s.io repo, please check your network environment, ping or curl.

if the  https://k8s.io repo have switch to github.com/kubernetes ?

**Comment by godliness** [comment]
@soledad000 GFW doesn't want you access that link, please go to find a proxy which could help you about this.

**Comment by FUSAKLA** [comment]
Hi, what is the status of this? Can we close it? Did you managed pass the build?

**Comment by soledad000** [comment]
> @soledad000 GFW doesn't want you access that link, please go to find a proxy which could help you about this.

OK，thanks

**Comment by soledad000** [comment]
> Hi, what is the status of this? Can we close it? Did you managed pass the build?

it is done！it can be closed, thanks.

**Comment by FUSAKLA** [comment]
Great! Thanks for confirmation.
