### ISSUE TITLE
ragged chart with Max1hDownsampling

### ISSUE THREAD

**Issue by ivmaks** [improbable-eng/thanos#1063]
Hello community! I can not find an explanation for this behavior:

when Max1hDownsampling I observe emptiness

![Max1hDownsampling](https://user-images.githubusercontent.com/13006295/56492193-aafc4200-64f3-11e9-9ce5-8486d35efb5a.png)

with Max5mDownsampling it seems that everything is fine

![Max5mDownsampling](https://user-images.githubusercontent.com/13006295/56492197-b0598c80-64f3-11e9-992a-ed0e37d6cf6e.png)

```
curl -s 'https://tq-ww3d-int.wbz.sqtools.ru/api/v1/query_range?query=up%7Binstance%3D%22app56.ww3d-int.wbz.sqtools.ru%3A9102%22%7D&dedup=true&partial_response=true&start=1550479236.65&end=1555922436.65&step=21772&max_source_resolution=1h&_=1555922161796' > 1h.txt
curl -s 'https://tq-ww3d-int.wbz.sqtools.ru/api/v1/query_range?query=up%7Binstance%3D%22app56.ww3d-int.wbz.sqtools.ru%3A9102%22%7D&dedup=true&partial_response=true&start=1550479236.65&end=1555922436.65&step=21772&max_source_resolution=5m&_=1555922161796' > 5m.txt
```

[5m.txt](https://github.com/improbable-eng/thanos/files/3102785/5m.txt)
[1h.txt](https://github.com/improbable-eng/thanos/files/3102786/1h.txt)

```
thanos --version
thanos, version 0.3.2 (branch: HEAD, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       circleci@4ea007a18ffa
  build date:       20190304-17:16:56
  go version:       go1.10.8
```

`thanos bucket inspect > inspect.log`
[inspect.log](https://github.com/improbable-eng/thanos/files/3102806/inspect.log)

**Comment by bwplotka** [comment]
Yea, looks like you don't have 1h downsampling blocks yet and behaviour for fallback to 5m does not really work? (:

**Comment by ivmaks** [comment]
The problem is reproduced in several environments.

If we remove the 1h samples, the graphics are rendered perfectly. Until the compactor starts and it does not generate 1h samples.

**Comment by bwplotka** [comment]
I think we are fixing this in https://github.com/improbable-eng/thanos/pull/1146

**Comment by bwplotka** [comment]
Should be fixed by https://github.com/improbable-eng/thanos/pull/1146
