### ISSUE TITLE
Store: Leaking Go Routines

### ISSUE THREAD

**Issue by svenwltr** [improbable-eng/thanos#1072]
**Thanos, Prometheus and Golang version used**

```
prometheus, version 2.9.0 (branch: HEAD, revision: 1a9cdbd024fea05a1888c3164058087476cfdc3b)
  build user:       root@4d7ed54ba6d9
  build date:       20190415-09:06:49
  go version:       go1.12.3
```

```
thanos, version 0.3.2 (branch: HEAD, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       circleci@4ea007a18ffa
  build date:       20190304-17:16:56
  go version:       go1.10.8
```

We are using a custom Docker image, so we can actually do a core dump.

<details>Dockerfile
<p>

```
FROM improbable/thanos:v0.3.2 as thanos

FROM alpine:latest

RUN set -x \
 && apk add --no-cache \
        bash \
        ca-certificates \
        gdb

COPY --from=thanos /bin/thanos /bin/thanos

COPY thanos/bucket_config.yml /config/bucket_config.yml
COPY prometheus/config/* /config/

ENTRYPOINT [ "/bin/thanos" ]
```

</p>
</details>

**What happened**

Thanos store occacionally starts leaking Go routines:

![Screenshot 2019-04-23 02](https://user-images.githubusercontent.com/1698599/56583698-7911db00-65da-11e9-9be9-7f56d5cfd366.png)

When this happens, the store consumes all available CPU time and does not respond fast enough or not at all.

We do not see anything that might cause this.

**How to reproduce it (as minimally and precisely as possible)**:

We do not know how to reproduce this.

**Full logs to relevant components**

We did a heap dump to see what kind of routines are leaking. I am not sure how useful these samples are, since they are stuck in quite generic functions.

<details>Heap Dump Samples
<p>

```
$ echo "goroutines" | dlv core thanos core.broken > goroutines
$ cat goroutines | ack 'User: ([^ ]+)' --output '$1' | sort | uniq -c
      1 /go/src/github.com/improbable-eng/thanos/cmd/thanos/main.go:155
      1 /go/src/github.com/improbable-eng/thanos/cmd/thanos/main.go:190
      1 /go/src/github.com/improbable-eng/thanos/cmd/thanos/store.go:186
      1 /go/src/github.com/improbable-eng/thanos/pkg/store/cache.go:130
 110134 /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:43
      2 /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:52
      1 /go/src/github.com/improbable-eng/thanos/vendor/go.opencensus.io/stats/view/worker.go:147
      2 /go/src/github.com/improbable-eng/thanos/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:321
      2 /go/src/github.com/improbable-eng/thanos/vendor/google.golang.org/grpc/internal/transport/http2_server.go:934
      5 /usr/local/go/src/runtime/netpoll.go:173
     13 /usr/local/go/src/runtime/proc.go:292
      1 /usr/local/go/src/runtime/sema.go:56
 436487 /usr/local/go/src/runtime/sema.go:71
      1 /usr/local/go/src/runtime/sigqueue.go:139
      7 /usr/local/go/src/runtime/sys_linux_amd64.s:531
     19 :0
```

```
$ cat goroutines | grep '/go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:43' | head -n 2
(dlv)   Goroutine 1 - User: /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:43 github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run (0xaff91c)
  Goroutine 7987171 - User: /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:43 github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run (0xaff91c)
$ cat goroutines | grep '/usr/local/go/src/runtime/sema.go:71' | head -n 1
  Goroutine 7987173 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x43d13d)
```

```
(dlv) goroutine 1
Switched from 7987173 to 1 (thread 1)
(dlv) bt
0  0x000000000042ca8a in runtime.gopark
   at /usr/local/go/src/runtime/proc.go:292
1  0x000000000042cb3e in runtime.goparkunlock
   at /usr/local/go/src/runtime/proc.go:297
2  0x0000000000404222 in runtime.chanrecv
   at /usr/local/go/src/runtime/chan.go:518
3  0x0000000000403edb in runtime.chanrecv1
   at /usr/local/go/src/runtime/chan.go:400
4  0x0000000000aff91c in github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
   at /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:43
5  0x0000000000e2b1a8 in main.main
   at /go/src/github.com/improbable-eng/thanos/cmd/thanos/main.go:180
6  0x000000000042c632 in runtime.main
   at /usr/local/go/src/runtime/proc.go:198
7  0x0000000000459ff1 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:2361
(dlv) goroutine 7987171
Switched from 1 to 7987171 (thread 1)
(dlv) bt
 0  0x000000000042ca8a in runtime.gopark
    at /usr/local/go/src/runtime/proc.go:292
 1  0x000000000042cb3e in runtime.goparkunlock
    at /usr/local/go/src/runtime/proc.go:297
 2  0x0000000000404222 in runtime.chanrecv
    at /usr/local/go/src/runtime/chan.go:518
 3  0x0000000000403edb in runtime.chanrecv1
    at /usr/local/go/src/runtime/chan.go:400
 4  0x0000000000aff91c in github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:43
 5  0x0000000000d77275 in github.com/improbable-eng/thanos/pkg/store.(*BucketStore).Series
    at /go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:738
 6  0x0000000000bf44be in github.com/improbable-eng/thanos/pkg/store/storepb._Store_Series_Handler
    at /go/src/github.com/improbable-eng/thanos/pkg/store/storepb/rpc.pb.go:679
 7  0x0000000000d26bf5 in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:71
 8  0x0000000000d286c9 in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/recovery/interceptors.go:39
 9  0x0000000000d26b9c in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:74
10  0x0000000000d4828c in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.StreamServerInterceptor.func1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:46
11  0x0000000000d4b3a2 in github.com/improbable-eng/thanos/pkg/tracing.StreamServerInterceptor.func1
    at /go/src/github.com/improbable-eng/thanos/pkg/tracing/grpc.go:35
12  0x0000000000d26b9c in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:74
13  0x0000000000d2c396 in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:121
14  0x0000000000d26d96 in github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1
    at /go/src/github.com/improbable-eng/thanos/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:79
15  0x00000000009e06f6 in github.com/improbable-eng/thanos/vendor/google.golang.org/grpc.(*Server).processStreamingRPC
    at /go/src/github.com/improbable-eng/thanos/vendor/google.golang.org/grpc/server.go:1175
16  0x00000000009e2591 in github.com/improbable-eng/thanos/vendor/google.golang.org/grpc.(*Server).handleStream
    at /go/src/github.com/improbable-eng/thanos/vendor/google.golang.org/grpc/server.go:1256
17  0x00000000009ead7f in github.com/improbable-eng/thanos/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
    at /go/src/github.com/improbable-eng/thanos/vendor/google.golang.org/grpc/server.go:699
18  0x0000000000459ff1 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:2361
(dlv) goroutine 7987173
Switched from 7987171 to 7987173 (thread 1)
(dlv) bt
0  0x000000000042ca8a in runtime.gopark
   at /usr/local/go/src/runtime/proc.go:292
1  0x000000000042cb3e in runtime.goparkunlock
   at /usr/local/go/src/runtime/proc.go:297
2  0x000000000043d424 in runtime.semacquire1
   at /usr/local/go/src/runtime/sema.go:144
3  0x000000000043d13d in sync.runtime_SemacquireMutex
   at /usr/local/go/src/runtime/sema.go:71
4  0x000000000046fcd8 in sync.(*Mutex).Lock
   at /usr/local/go/src/sync/mutex.go:134
5  0x0000000000d8039d in github.com/improbable-eng/thanos/pkg/store.(*indexCache).setPostings
   at /go/src/github.com/improbable-eng/thanos/pkg/store/cache.go:139
6  0x0000000000d89b25 in github.com/improbable-eng/thanos/pkg/store.(*bucketIndexReader).fetchPostings.func3
   at /go/src/github.com/improbable-eng/thanos/pkg/store/bucket.go:1381
7  0x0000000000affa47 in github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1
   at /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38
8  0x0000000000459ff1 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:2361
```

</p>
</details>

**Comment by bwplotka** [comment]
Are you sure you customized index-cache and chunk-pool flags for store?

See: https://github.com/improbable-eng/thanos/blob/master/CHANGELOG.md#added-1

**Comment by svenwltr** [comment]
Currently both are set to `500MiB`. I do not understand what a "large enough value" means here and how this can be connected to a go routine leak.

But yeah, they seem to be connected:

![Screenshot 2019-04-23 03](https://user-images.githubusercontent.com/1698599/56586029-3e5e7180-65df-11e9-965f-44e24374a963.png)

I will increase the issue and see if it fixes the issue.

Is this still considered it a bug, if it fixes it? This behavior does not look comprehensible from a user perspective.

**Comment by GiedriusS** [comment]
Hello there, did it help? This probably means that you are trying to make huge (speaking in relative terms) queries and because your cache size isn't big enough, we have to go to the bucket store constantly to retrieve certain data. And those goroutines most likely come from there.

**Comment by svenwltr** [comment]
It is hard to tell if this helped, since the store always dies before reaching the limit. This is because of some SIGSEV (I did not have time yet to write an issue). At least the go routines stopped leaking since I changed the limits.

Nevertheless the is still constantly growing and I don't know what happens when it reaches the limit again:

![Screenshot 2019-04-29 01](https://user-images.githubusercontent.com/1698599/56884223-64659500-6a69-11e9-85e7-90b4a96371e9.png)

It is possible that this is caused by huge queries. We are heavily utilizing Prometheus/Thanos and our teams manage their own set of Grafana dashboards. It is possible that there are unoptimized queries, but we do not have any means figuring out what queries or dashboards are causing this.

**Comment by bwplotka** [comment]
Have you set the sample-limit and concurrency limit as well?

**Comment by bwplotka** [comment]
> Currently both are set to 500MiB. I do not understand what a "large enough value" means here and how this can be connected to a go routine leak.

That's probably way to low value. Also Store GW is bit unstable with those values being super low.

**Comment by svenwltr** [comment]
> Have you set the sample-limit and concurrency limit as well?

We now have only `--index-cache-size=2000MB` and `--chunk-pool-size=500MB`. `--block-sync-concurrency` is currently not set and therefore it uses the default of `20`. What impact would have a chance of the concurrency?

> That's probably way to low value. Also Store GW is bit unstable with those values being super low.

Why are the defaults so low?

**Comment by bwplotka** [comment]
> Why are the defaults so low?

We had to pick some values (: Very good point though. I think Action Item for this issue is to make default more reasonable or disabled even.

**Comment by povilasv** [comment]
IMO the only proper way to set good defaults is to read proc filesystem and set it based on container limits or host memory. You can run Thanos on Raspberry pi vs Thanos on huge server we will never find a good default value.

**Comment by svenwltr** [comment]
> IMO the only proper way to set good defaults is to read proc filesystem and set it based on container limits or host memory. You can run Thanos on Raspberry pi vs Thanos on huge server, so we will never find a good default value.

This is completely valid, since the flags are exactly there to adjust values according to the specific environment. Nevertheless, in this case the low values cause Thanos to leak Goroutines and stop responding. This happens without a clear indication that this behavior is linked to some config flag.

It would be perfectly okay, if a low default value would mean that Thanos just performs bad or it would exit with a clear error message.

**Comment by GiedriusS** [comment]
In the newest versions Thanos Store prints error messages to the log if it spins more than a sane number of times. It should be a good enough indication that the index cache size should be increased, no?

**Comment by svenwltr** [comment]
Yes, logging should be enough.

Nevertheless, our store instance did not leak Go routines, since we increased the cache size:

![Graph](https://user-images.githubusercontent.com/1698599/57863679-cdcffc80-77fa-11e9-81b7-7e3313d087cf.png)

So, this issues is fixed for us. Thank you.
