### ISSUE TITLE
Gaps in rule evaluation

### ISSUE THREAD

**Issue by tcolgate** [improbable-eng/thanos#1087]
** Setup **
Running in docker in kube.

- 2 prom instances with HA prometheusInstance=POD_NAME labels (0.4.0-rc.0)
- 2 rule instances with HA prometheusInstance=POD_NAME labels (0.4.0-rc.0)
- 4 query instances (0.4.0-rc.0)
- 1 compact instance (0.3.2)
- everything is using mTLS

**What happened**
I'm seeing gaps in the data evaluated by ruler. They appear at approximately 1 hour intervals. All pods are up and healthy and are not restarting during the time shown.

The data from these two charts is generated by a recording rule run on the ruler.

![gaps-cpu](https://user-images.githubusercontent.com/76019/56802362-bf07b280-6817-11e9-9e18-bbbbe79a3722.png)

![gaps](https://user-images.githubusercontent.com/76019/56802363-bfa04900-6817-11e9-829a-a24c722bf96b.png)

This shows the evaluation errors and failures reporting by both rulers.
![failures](https://user-images.githubusercontent.com/76019/56802361-bf07b280-6817-11e9-85fa-2e8eab3e8743.png)

Ruler runs all of our rules (about 80 deployed in this case)
No rule evaluations are taking longer than the eval interval (according to metrics)

**What you expected to happen**

No gaps in the evaluation interval

**How to reproduce it (as minimally and precisely as possible)**:
I have 8 clusters. 1 is seeing this very consistantly (at 1 hour intervals), probably 3 other busy clusters see it semi regularly (at least once every 4 hours). 4 very quiet clusters have not see the problem at all so far.

**Full logs to relevant components**
There are no log entries in info mode from ruler, querier or store that occur for this time.

**Comment by tcolgate** [comment]
I've also check the ruler disk space, and grpc server stats for all the components and there are no reported problems.

**Comment by tcolgate** [comment]
I don't have a definitive answer yet, but it looks like ruler occsionally stops processing some groups. I see some ruler instances where the number of rules and groups is as expected, but where ```prometheus_rule_evaluations_total``` drops.

**Comment by tcolgate** [comment]
A couple of observations:
- I have another situation where, after some rule eval failures (using the abort strategy), the rulers seems to stop evaluating that group completely going forward (the rules are loaded, but not more results appear after a spike in eval failures). I need to double check the documented behaviour in abort.
- For the situation reported in this bug, there is a correlation between the missing evaluation values and call to the store.Series calls.
I'll try and investigate these more next week.

**Comment by tcolgate** [comment]
I do see these log entries when I see the drop in the number of rules being evaluated ```caller=rule.go:822 err="unknown response type: '\"\"'"```

**Comment by tcolgate** [comment]
On the querier I have a log line ``` caller=storeset.go:234 component=storeset msg="removing store because it's unhealthy or does not exist"```. The ruler evauation does seem to recover with the ruler restarting. I am wondering if the problem lies in the querier considering the store unhealthy (one of the stores restarted at this time).

**Comment by tcolgate** [comment]
Restarting the queriers, without restarting ruler, also brings back rule evaluation. This makes me think that the problem is not in ruler, but that each ruler go routine is talking to a different querier, and some queroers aren't talking to all stores.

**Comment by tcolgate** [comment]
It appears that during the gaps in evaluation, I see this in the sidecar:
```component=sidecar msg="found timeseries without any chunk. See https://github.com/improbable-eng/thanos/issues/381 for details"```.

**Comment by brancz** [comment]
@bwplotka did we ever figure out what "right thing" was? Judging by https://github.com/improbable-eng/thanos/pull/390 we only added the above log line, but never actually changed any behavior (maybe intentionally).

**Comment by bwplotka** [comment]
Yes. This is because the empty timeseries is what we are getting from Prometheus/TSDB. And we did not dive more IF it is bug or just it can happen.

If @tcolgate find a correlation between this and gaps and e.g one query sometimes works sometimes we get empty timeseries... then it's some nasty bug. Personally I never seen this so thought it is just someting that TSDB collected in this way and there is no major issue here. Same seems to be for issue author.

**Comment by tcolgate** [comment]
I'm closing this for now as the original reported issue is, I think, a problem on my end (service discovery is periodically failing in GKE).
