### ISSUE TITLE
OpenStack cross domain authentication

### ISSUE THREAD

**Issue by auhlig** [improbable-eng/thanos#1117]
The current [OpenStack Swift configuration](https://github.com/improbable-eng/thanos/blob/master/pkg/objstore/swift/swift.go#L29-L40) lacks OpenStack Identity V3 support:
1) The term `tenant` is used in the deprecated OpenStack Identity v2. In Identity v3 it's called `project`.
2) Cross-domain authentication is supported by Identity v3 but not possible via Thanos. 
   (user being in another domain than the project (formerly tenant).

To fix them I propose:
1) Introduce the new fields `project_id`, `project_name` and mark `tenant.+` as deprecated.
2) Add the field `user_domain_id`, `user_domain_name` and `project_domain_id`, `project_domain_name` to support cross domain authentication.

I'll follow up with a PR. What do you think?

**Comment by GiedriusS** [comment]
https://github.com/improbable-eng/thanos/pull/1118 was merged so this has been done. Thank you again! :+1:
