### ISSUE TITLE
Querying long storage data times out.

### ISSUE THREAD

**Issue by OGKevin** [improbable-eng/thanos#1125]
**Thanos, Prometheus and Golang version used**
Thanos 0.3.2 && 0.4.0
Prometheus 2.9.2

**What happened**
Querying data older than 2 hours, which requires the GCP bucket to be queried, causes for `Error executing query: query timed out in expression evaluation` errors.

An example query is: 
```
histogram_quantile(0.99, sum(rate(my_metric[5m])) by (le))
```
**What you expected to happen** 
The query to be preformed smoothly like it would if you query prometheus directly. 

**How to reproduce it (as minimally and precisely as possible)**:
Setup thanos with GCP bucket, 6 prometheus shards + replica, produce a lot of metrics for `my_metric` and preform the above query for greater than 2 hours. 

**Full logs to relevant components**

Store spits out a bunch of logs containing the message: `msg="stats query processed"` and `msg="No block found"` it produces a lot of entries so not sure if these entries are useful or not.  

**Anything else we need to know**
I have a feeling that this might be related to compactor not compacting the data accordingly but not sure. By looking at this graph of disk space usage of compactor, it looks like it was not doing anything despite the `thanos_compactor_halted ` metric being 0 at that time. 

![Screenshot 2019-05-09 at 14 59 54](https://user-images.githubusercontent.com/17928966/57457106-2b020600-726f-11e9-931e-5ca61a45b67b.png)

The logs indicate the following error from compactor logs:

```
prometheus-thanos-compact-0 thanos-compact level=error ts=2019-05-09T12:28:15.427101955Z caller=compact.go:265 msg="retriable error" err="compaction failed: sync: retrieve bucket block metas: downloading meta.json for 01DAC3J8RH97E1XYJNZ1JWPNK4: meta.json bkt get for 01DAC3J8RH97E1XYJNZ1JWPNK4: storage: object doesn't exist"
```

After updating to 0.4.0 the above "resolved itself" and compactor started running again. That is the fast decline in storage you see at the end of the graph. 

*Example:*

![Screenshot 2019-05-09 at 15 45 31](https://user-images.githubusercontent.com/17928966/57458527-d01dde00-7271-11e9-9355-3aa755cb6deb.png)

**Comment by bwplotka** [comment]
Thanks for reporting.

How Thanos Store resources looks like during the request? Is it OOM?
What is the bucket used?
What are the index-cache file and chunk pool? We have seem similar thing if the value is super low.

**Comment by OGKevin** [comment]
> How Thanos Store resources looks like during the request? Is it OOM?

It had 50 Gi of ram and now 100 Gi, it was not getting OOM'ed. So memory is not the case. When it had 50Gi it was consuming 80%. So now it has more men. But the symptoms remained the same. 

> What is the bucket used?

Google GSC 

> What are the index-cache file and chunk pool?

The default values, 
```
     --index-cache-size=250MB   
      --chunk-pool-size=2GB      
```

I will increase these and report back.

**Comment by OGKevin** [comment]
Increased to 1000MB and 5Gb still have the same symptoms. Any recommendation on how to determine if this is the bottleneck or not? E.g. is there a metric for this?

**Comment by bwplotka** [comment]
Ok, so it's just OOM then, this is then duplicate to this: https://github.com/improbable-eng/thanos/issues/448 Closing, let's move discussion to 448 if that's ok? (: 

Also v0.4.0 uses Go1.12 which supposedly allocs more even if not used.

On slack: https://improbable-eng.slack.com/archives/CADR0UWS2/p1557927049160600
> managed to reclaim half of the 5GB by adding this `GODEBUG=madvdontneed=1`

**Comment by bwplotka** [comment]
Dup of https://github.com/improbable-eng/thanos/issues/448

**Comment by OGKevin** [comment]
Hmm, im not sure if its OOM... as store hasn't OOMed in days. it never hit 100% when it had 50Gi. 

> Also v0.4.0 uses Go1.12 which supposedly allocs more even if not used.

Yea I'm indeed aware of this one 👍 

On what did you conclude that this is an OOM issue? 

![Screenshot 2019-05-15 at 17 51 57](https://user-images.githubusercontent.com/17928966/57789964-2ab7ae00-773a-11e9-99af-42b3902c0295.png)

As you can see, it never crossed 50% and the same symptoms apply of queries greater then 2 hours are timing out.
