### ISSUE TITLE
Storing Data Locally in the cluster (Persistent/Volatile)

### ISSUE THREAD

**Issue by MrD2** [improbable-eng/thanos#1134]
Not an issue:

Question: Is there a slack channel or something?

Question: Can i use thanos with local storage? I have a case where i would like to use thanos to aggregate and downscale data but not store it forever.

Question: If i cannot store locally, can i specify a remote service other than the main clouds using an endpoint and respective credentials to store my data. I set up in my cluster a **minio** S3 server but i dont see a way where i can configure this in thanos.

https://github.com/minio/minio/blob/5ecac91a551c043160fbe17dd615280939b83892/pkg/iam/policy/constants.go
https://github.com/helm/charts/blob/master/stable/minio/values.yaml

**Comment by bwplotka** [comment]
@MrD2 yes (: See slack button on Thanos Readme.md

**Comment by bwplotka** [comment]
> Can i use thanos with local storage? I have a case where i would like to use thanos to aggregate and downscale data but not store it forever.

Yes & no. You cannot use pure filesystem but you can use single one-node `minio` which you can quickly spin up.

**Comment by bwplotka** [comment]
> I set up in my cluster a minio S3 server but i dont see a way where i can configure this in thanos.

Minio has S3 API so you just use is as `S3` type object storage. Closing, can reopen if not answered fully.
