### ISSUE TITLE
store/sidecar: minio-go missing support for ap-east-1

### ISSUE THREAD

**Issue by cjohnston-fuze** [improbable-eng/thanos#1135]
**What happened**

Bucket operations to ap-east-1 fail with:

```
The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```

This is because minio-go doesn't have the s3 dual stack endpoint so it defaults to s3.dualstack.us-east-1.amazonaws.com.

I've created a PR that adds the endpoint. This ticket is for information and hopefully to create new release sooner than later that includes that change.

https://github.com/minio/minio-go/pull/1105

@bwplotka

**Comment by bwplotka** [comment]
Makes sense to me :+1: We need to update minio-go dep then. We can do it in small PR and essentially you can use Thanos master, right? (:

**Comment by cjohnston-fuze** [comment]
https://github.com/improbable-eng/thanos/pull/1140

I updated go.mod but wasn't sure about mod.sum.
