### ISSUE TITLE
compaction increases storage usage on S3

### ISSUE THREAD

**Issue by ashish-yad** [improbable-eng/thanos#1164]
**Thanos, Prometheus and Golang version used**
Thanos Version 0.2.1
Go 1.11.4
Prometheus 2.9.1

**What happened**
I ran Thanos compaction on S3 storage. After successful execution of command S3 storage usage increased from 808.4 MB to 1.5 GB.

**What you expected to happen**
After running compaction on S3, occupied storage should be reduced. It should be lesser than previous value i.e. less than 808.4 MB

**How to reproduce it (as minimally and precisely as possible)**:
I ran following command, which executed successfully 
sudo thanos compact --objstore.config-file /path/bucket_config.yaml --http-address=0.0.0.0:10903

**Full logs to relevant components**
$sudo thanos compact --objstore.config-file /path/bucket_config.yaml --http-address=0.0.0.0:10903
level=info ts=2019-05-17T13:40:01.614175364Z caller=factory.go:41 msg="loading bucket configuration"
level=info ts=2019-05-17T13:40:01.614764066Z caller=compact.go:281 msg="starting compact node"
level=info ts=2019-05-17T13:40:01.614939997Z caller=main.go:308 msg="Listening for metrics" address=0.0.0.0:10903
level=info ts=2019-05-17T13:40:01.616481046Z caller=compact.go:816 msg="start sync of metas"
level=info ts=2019-05-17T13:40:02.351111692Z caller=compact.go:822 msg="start of GC"
level=info ts=2019-05-17T13:40:02.392168699Z caller=compact.go:207 msg="compaction iterations done"
level=info ts=2019-05-17T13:40:02.392226179Z caller=compact.go:214 msg="start first pass of downsampling"
level=info ts=2019-05-17T13:40:02.644374593Z caller=compact.go:220 msg="start second pass of downsampling"
level=info ts=2019-05-17T13:40:02.879703845Z caller=compact.go:225 msg="downsampling iterations done"
level=info ts=2019-05-17T13:40:02.879792645Z caller=retention.go:17 msg="start optional retention"
level=info ts=2019-05-17T13:40:03.146448509Z caller=retention.go:46 msg="optional retention apply done"
level=info ts=2019-05-17T13:40:03.146831195Z caller=main.go:184 msg=exiting

**Anything else we need to know**

previously each block were of the size of 1.1 MB and total number of blocks were 300 .
After compaction block sizes varies from 1.8 MB to 298 MB and total number of blocks is only 21.
So after compaction number of blocks reduced but overall sizes have increased.

**Comment by GiedriusS** [comment]
Hello there. So yes, Thanos did what you had asked it to do - compacted data but *not* applied any kind of retention policies. Compacting blocks does not imply that they are going to be deleted. As you can see from the output, retention policies are optional. I hope this helps, let us know if you have any more questions 😄

**Comment by GiedriusS** [comment]
No response has been received for a long time so I will assume that this has been solved. Please let us know if you have any more questions!
