### ISSUE TITLE
[store] Improve startup time.

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#119]

**Comment by fabxc** [comment]
Closing this for now. IIRC this was opened at a time before we had the compactor fully running, which easily meant 2-3 order of magnitude more blocks, which had obvious effects.

Additionally, the store node caches blocks locally (which is optional to preserve across restarts though). With that restarts should be fast as it boils down to reading the meta.json file and the small cache file for the initial index lookup stages from local disk.
