### ISSUE TITLE
How to reference sidecar in another namespace (same cluster)

### ISSUE THREAD

**Issue by popsonebz** [improbable-eng/thanos#1215]
**thanos v0.4.0 prometheus v2.8.1**

**what happened**
i installed created two kubernetes namespaces client-a-prometheus and client-b-prometheus.
i have a complete setup of all component of thanos in client-a-prometheus but only installed prometheus and thanos sidecar in client-b-prometheus.
However, when i configured the thanos querier to pick up the sidecar in client-b-prometheus, it doesn't work because its on a different namespace.

**What i expected to happen**
I expect thanos querier to pick up sidecar from other namespaces

**How to reproduce it in querier config)**:

          containers:
             - name: thanos
            image: improbable/thanos:v0.4.0
            args:
            - query
            - --log.level=debug
            - --query.replica-label=replica
            - --cluster.disable
            # Discover local store APIs using DNS SRV.
            #- --store=dnssrv+thanos-store-gateway.monitoring.svc
             - --store=dnssrv+thanos-store-gateway.client-a-prometheus.svc
 
            # Get remote store APIs by IP:Port.
            - --store=sidecar.client-b-prometheus.svc
            - --store=dnssrv+sidecar-1.client-b-prometheus.svc
            - --store=sidecar-1.client-b-prometheus:10901
            - --store=sidecar-1.client-b-prometheus.svc.local:10901
            - --cluster.peers=thanos-peers.default.svc:10900
            ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
            - name: cluster
              containerPort: 10900

**Full logs to relevant components**

**Anything else we need to know**

**Comment by bwplotka** [comment]
Hi,

Why not adding similar `thanos-store-apis` headless Kubernetes service in `client-b-prometheus` and refer `thanos-store-apis.client-b-prometheus.svc`.

I intentionally use `thanos-store-apis` instead of `thanos-store-gateway` as I think there is some accdiental naming mistake -> store gateway means rather the component itself that implements browsing of older metrics in object storage. (: We should fix our tutorial manifests...

**Comment by popsonebz** [comment]
> Hi,
> 
> Why not adding similar `thanos-store-apis` headless Kubernetes service in `client-b-prometheus` and refer `thanos-store-apis.client-b-prometheus.svc` ?
> 
> I intentionally use `thanos-store-apis` instead of `thanos-store-gateway` as I think there is some accdiental naming mistake -> store gateway means rather the component itself that implements browsing of older metrics in object storage. (: We should fix our tutorial manifests...

I will give this a try.

**Comment by popsonebz** [comment]
> Hi,
> 
> Why not adding similar `thanos-store-apis` headless Kubernetes service in `client-b-prometheus` and refer `thanos-store-apis.client-b-prometheus.svc` ?
> 
> I intentionally use `thanos-store-apis` instead of `thanos-store-gateway` as I think there is some accdiental naming mistake -> store gateway means rather the component itself that implements browsing of older metrics in object storage. (: We should fix our tutorial manifests...

I gave it a try. I can see the store-api of that namespace but the sidecars of that namespace is not listed.

**Comment by vaibhavkhurana2018** [comment]
Try using, 

`--store=<svc_name>.client-b-prometheus.svc.cluster.local.:10901`

Replace the svc with the service pointing to the sidecar of prometheus.

**Comment by FUSAKLA** [comment]
Hi, did you manage to resolve your issue? Can we close this? 
Also questions like this are better to ne asked on the [slack channel](https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc) maybe

**Comment by popsonebz** [comment]
Sorry the I did not give feedback on this.
The issue was solved by using --store=<svc_name>.client-b-prometheus.svc.cluster.local.:10901
