### ISSUE TITLE
[UI] Search by metric name does not work after some time.

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#123]
Looks like just UI issue: Nothing wrong with LabelValues. I can call  `/api/v1/label/__name__/values?_=1513164422596` as aggressively as I want.

**Comment by fabxc** [comment]
Probably more of an upstream bug then?

**Comment by Bplotka** [comment]
Not really - I cannot repro it now with our newest query version (:

**Comment by Bplotka** [comment]
cannot repro
