### ISSUE TITLE
Delete Certain Metrics From Longterm Storage

### ISSUE THREAD

**Issue by midnightconman** [improbable-eng/thanos#1237]
**Thanos, Prometheus and Golang version used**
0.5.0

**What happened**

**What you expected to happen**
I would like to be able to delete certain metrics from long-term storage. 
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by antonio** [comment]
Related: https://github.com/improbable-eng/thanos/issues/415

**Comment by bradleyhession1** [comment]
Bump - we had an incorrect client sending metrics, need to do this also.

**Comment by GiedriusS** [comment]
Closed in favor of #415 as this is a duplicate of it.
