### ISSUE TITLE
bucket/tooling: add support for retries in Azure Blob storage

### ISSUE THREAD

**Issue by wbh1** [improbable-eng/thanos#1252]
**Feature Request/Improvement:**
- Add support for handling retries (e.g. for network issues) to the Azure object storage implementation.

Other implementations like S3 (Minio) and GCS already appear to have this support.

Default behavior should not be changed (no retries), but the option to specify a maximum amount of retries in the config file should be added.

This is related to #318.

I'll be submitting a PR shortly that will close this issue.

**Comment by bwplotka** [comment]
Perfect, as in previous cases, do you know if Azure plugin we use have this logic? Essentially doing this on implementation side has more benefits -> greater knowledge on error etc.
