### ISSUE TITLE
[store] Improve LRU cache with additional features

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#127]
For instance:
- Removal of item when block is deleted
- Time-based retention (?)

**Comment by fabxc** [comment]
One is definitely an option – though those items might get evicted pretty quickly as is.

What would you hope time-based retention to do? I'd probably rather shoot for a byte size-based one instead of the current item count since it will make configuration more predictable.

**Comment by fabxc** [comment]
I think this can be closed. Retention is size-based now, which seems ideal from a users perspective. I don't see purging cache items for a block happening any time soon due to the LRU lib we are using.  Practical benefits are questionable anyway.

**Comment by Bplotka** [comment]
:+1:
