### ISSUE TITLE
What options do we have for on-prem Thanos compatible storage options

### ISSUE THREAD

**Issue by Swetad90** [improbable-eng/thanos#1303]
We are using Prometheus 2.8 and set it up using docker-compose. We wanted to leverage Thanos for its global query and longer retention feature.
I see a lot of examples on cloud storage, do we have any on-prem  storage solution that's tested with Thanos ?

**Comment by FUSAKLA** [comment]
Hi, please refer to the slack channel linked in readme of the repo with questions if possible.

Regarding your question. In our company we use Minio which is really easy to get up and running and works well but we have also swift installations which I did not try with Thanos but should work. So those two are probably on prem way to go.

**Comment by bwplotka** [comment]
Yup :+1: 

BTW, questions here are ok as well if not even better as you they are searchable (: :+1:

**Comment by FUSAKLA** [comment]
Sorry for the mystification about questions on slack :)

**Comment by Swetad90** [comment]
Thanks @bwplotka @FUSAKLA
