### ISSUE TITLE
[ruler] Should ruler scrape duplicated data? Or HA should be transparent for it?

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#137]
I think scraping deduplicated data is actually the correct answer. I think we had idea to add deduplication batch job for old data that will reduce data in obj store.

**Comment by fabxc** [comment]
Yes it should, not doing it would of course prevent us from losing insight into potential weirdnesses. But we would need ability to specify multiple replica labels, alerts would fire twice, and rules that depend on other rules would probably get really weird.

**Comment by Bplotka** [comment]
OK :+1:  closing that for now then
