### ISSUE TITLE
Some series's oldest data are not available (?)

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#145]
So for `go_goroutines` we have oldest datapoint at 26 Nov:
![image](https://user-images.githubusercontent.com/6950331/34109435-7adb9f0a-e3fb-11e7-8b3c-a8e5b826f849.png)

But for example for `go_goroutines{job="thanos-store"}` it is better 21 Nov (!)
![image](https://user-images.githubusercontent.com/6950331/34109489-a7ad508c-e3fb-11e7-9ac6-c2aed7c01502.png)

The metric without any matcher should show these old datapoints...

**Comment by Bplotka** [comment]
Shortening range does not help -> still no matcher query does not show anyting on 21 Nov

**Comment by fabxc** [comment]
So adding a matcher suddenly gives you more data for a particular series?

**Comment by Bplotka** [comment]
yes

**Comment by Bplotka** [comment]
Max Series size was greater than 4KB. Fixed.
