### ISSUE TITLE
Series fetch issue

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#146]
`querying store failed: receive series: rpc error: code = Aborted desc = fetch series for block 01C18S2S39ZQ4VK43SKVYBRKSR: invalid remaining size 4096, expected 13485`

From time to time.

**Comment by Bplotka** [comment]
This is on certain query: `graph?g0.range_input=2w&g0.end_input=2017-11-23%2013%3A48&g0.expr=go_goroutines&g0.tab=0` 

(after some time and then 100% reproducible)

**Comment by fabxc** [comment]
This started happening just after you started compaction again?

**Comment by Bplotka** [comment]
well not really. I was doing lot's of queries for different things and it started on certain query after some time.. so not sure if there is any correlation with compaction. (new compactor is running 1,5h)

**Comment by fabxc** [comment]
Yes, did you ever see this happen before that though?

**Comment by Bplotka** [comment]
nope

**Comment by fabxc** [comment]
I mean this ultimately just seems like some series entries get a good bit longer than the 4KB we expected.
It seems generally possible given we generated a lot of chunks initially with out 5s scrape interval. If you compact a week worth of those together, the series entry has to reference several hundred chunks.

13KB of chunk-indexing data for a single series in a single block actually makes me a bit worried :) But ultimately anything becomes worrisome if you keep the high resolution in long-term storage.

The answer here is basically to just bump the range we fetch per series.

**Comment by fabxc** [comment]
I just hit it as well. It seems indeed to be non-deterministic for the same query over the same time range... that's rather odd though.

**Comment by fabxc** [comment]
Got 'fixed' by bumping the maximum series size we are reading. Anything fully save will require upstream changes to the storage format.

**Comment by bwplotka** [comment]
Revisiting this as we saw some issues of violating this again e.g https://github.com/thanos-io/thanos/issues/552 

Given just one error, it might still not worth to change.

Just leaving the calculation for max size of series entry:

*  Max varint lengths: https://github.com/golang/go/blob/master/src/encoding/binary/varint.go#L19
*  max series entry size in bytes: 10 (max uvarint64) + 2 * 5 (max uvarint32) * a number of labels pairs + 10  (max uvarint64)  + 3 * 10 (max uvarint64) * chunks
