### ISSUE TITLE
Implement a way to validate completed block upload

### ISSUE THREAD

**Issue by fabxc** [improbable-eng/thanos#173]
Currently when we upload blocks to the object storage, if we encounter an error we clean up after ourselves and delete all files that were uploaded so far. This is however not 100% safe yet.

If the uploader has a hard crash, orphaned objects are left behind. Files are uploaded in order so a block will only be validly considered if the `meta.json` exists, which is uploaded last. This guards against for example, considering a block during garbage collection even though it is only partial. This is however implicit and makes us rely on upload order, i.e. we cannot parallelise it.

We should come up with a way to ensure this. This could either be a dedicated `done` file for each block or setting of a metadata/label onto the `meta.json` file in the object storage. Either way, our code would do an explicit finalization after successful upload of all block data.
We should also add a background cleanup procedure that detects and purges partial blocks.

**Comment by Bplotka** [comment]
https://github.com/improbable-eng/thanos/pull/295 fixes it I believe.

We explicitly ensure that `meta.json` is uploaded as a last item. It seems like a good enough solution for now.
