### ISSUE TITLE
ui: Add store targets page for querier.

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#212]
We wanted to do that with some UI upgrade, but that is extremely useful now -> Setting gossip cluster and ensuring all labels are ok might be tricky.

**Comment by eswdd** [comment]
Been looking at implementing this as an easy first pull request. I have a basic peers page working and exposing info about the peers. See this screenshot (needs a bit of work):

![image](https://user-images.githubusercontent.com/1651355/42245874-5dd8dc26-7f12-11e8-815d-88e2b7e94ce0.png)

One challenge is showing dropped peers as mentioned in #306, since memberlist doesn't provide a method to expose dead members. Is it worth tracking this ourselves? Challenges seem to be:
* Dead peers that come back could come back with a different name but on the same address, so we'd need to check the address against known dead peers.
* At some point we need to age out dead peers as presumably they might never come back?

**Comment by eswdd** [comment]
One odd thing I've noticed is that query peers expose a Store API, is this expected?

**Comment by Bplotka** [comment]
Thanks for doing this! It is really must-have now (: 

>  Is it worth tracking this ourselves? 
I don't think it so, and if, then maybe only for short time (seen in 1h?). In case of Kubernetes rollout, restarted peer has most likely totally new IP address so the list of dead but seen before peers would be super huge. Nice thing would be to see flaky peers.

> One odd thing I've noticed is that query peers expose a Store API, is this expected?
Yes indeed. Query can work as an intermediate proxy for another query. However, it will be never in such mode when connected through gossip. Only when connected through `--store` (another) query flag.

One important bit here is `storeset` logic (`pkg/query/storeset.go`). Basically, gossip can work, it can show us a valid member and valid peer is passed to `storeset.Update` method (along with static addresses configured by `--store` flag). Update method then, before exposing to internal request "fan out" logic, it checks healthiness of StoreAPI endpoint by fetching labels from gRPC Store.Info method. And few things can happen here:
1. StoreAPI IP is totally wrong: no such host
2. StoreAPI IP is some unaccessible IP: no such host
3. gRPC StoreAPI is not ready/not listening/rate limitted
etc... 
in such cases, peer can be assumed "dead" anyway...

Do you think we can put all of this into the same page?
- peer info like you have now (perfect!)
- an additional field for last Thanos.Store/Info gRPC request result (and when it was)
- If it is included in storeset or not.
- include statically added gRPC storeAPI addresses (via `--store` flag)

I think having some dead peers for gossip (cached) view can be done as next iteration.

They are all connected, but maybe it makes more sense to separate these into 2 different pages (store API targets vs gossip peers). That might make sense too. What do you think?

**Comment by eswdd** [comment]
OK, that all makes sense, might need to expand my testing environment beyond my laptop to check all this works as expected.

> Do you think we can put all of this into the same page?

I'll have a go at putting it all on the same page with collapsible sections like you get with the Prometheus targets and then see what it looks like. Also need to clean up the styling on things like labels to look similar.

> I think having some dead peers for gossip (cached) view can be done as next iteration.

Sounds like a plan! 

Won't get back to it for a few days now, so hopefully will have some updates for next week.

**Comment by bwplotka** [comment]
That was added here: https://github.com/improbable-eng/thanos/pull/663
