### ISSUE TITLE
Come up with convention for partial errors

### ISSUE THREAD

**Issue by fabxc** [improbable-eng/thanos#22]
When fanning out requests to multiple Prometheus instances or store nodes, partial failures will happen and should be handled gracefully. We need a consistent way to express partial failures for internal and external error handling.

**Comment by Bplotka** [comment]
What options we have?
Definitely we want to return at least some partial result, but in the same time we need to somehow notify user of Query API that this are only partial results.

Cannot see any proper way of notifying user without changing promQL package

**Comment by Bplotka** [comment]
Moved right now to just partial results with no notification(!)

**Comment by Bplotka** [comment]
No partial errors are visible on UI (using context passed by promQL).
