### ISSUE TITLE
Command-line flags page for query instances is not populated

### ISSUE THREAD

**Issue by mattbostock** [improbable-eng/thanos#248]
The 'command-line flags' page is visible in the UI for query instances, but is not populated.

If the UI is only enabled on the query instances, perhaps it's not worth including this in the UI and would be better as an API endpoint?

It's inconsistent to expose this information for query instances but not other instance types, so maybe we should remove it entirely.

**Comment by Bplotka** [comment]
Other instance types like store, sidecar etc? Well, they don't have UI so there is no inconsistency. But let's remove it if it's not even populated - fair point.

**Comment by mattbostock** [comment]
> Well, they don't have UI so there is no inconsistency.

That's part of where the inconsistency stems from, i.e. why would you use the UI to know the command-line flags for the query instance but not the other instances.

**Comment by Bplotka** [comment]
Totally agree :+1:

However, I am looking forward to seeing some other useful UI views like:
- store/query nodes in the system and their labels/time ranges at the time.
- last storeAPI errors if any
There was an idea to add these in a totally new UI, but maybe worth to add these in current UI ASAP as well
