### ISSUE TITLE
Make it obvious when distinct external labels not set

### ISSUE THREAD

**Issue by mattbostock** [improbable-eng/thanos#266]
The ['Getting Started' guide](https://github.com/improbable-eng/thanos/blob/962faa0323e69097735d120405a12b956aab1add/docs/getting_started.md#external-labels) says:

> Every Prometheus instance must have a globally unique set of identifying labels.

If feasible, we should ideally error or otherwise make it obvious if the user omits to do this.

**Comment by fabxc** [comment]
Yes! We should definitely alert on this and probably reject Prometheus servers without any external labels all together.
