### ISSUE TITLE
Set Thanos-specific user agent when communicating with object storage

### ISSUE THREAD

**Issue by mattbostock** [improbable-eng/thanos#291]
When Thanos talks to S3-compatible APIs, the user agent is:

    Minio (linux; amd64) minio-go/4.0.6

We should include the word 'Thanos', the Thanos version and the instance type (compact, store, etc) in the user agent. Adding the Go runtime version would also be nice to have.

We should try to retain the Minio version (maybe keep `minio-go/4.0.6`).

For example:

    Thanos compact v0.0.1 (go 1.10); minio-go/4.0.6

**Comment by Bplotka** [comment]
Makes sense.

**Comment by deejay1** [comment]
Seems like minio doesn't allow for easy replacement of the user agent, so far I managed to achieve `Minio (darwin; amd64) minio-go/4.0.9 Thanos/ (go1.10.1)` and it seems like `version.Version` from prometheus/common doesn't seem to play nice with `go test` . This is my first foray into golang, so comments welcome!
