### ISSUE TITLE
donwsampling: Optimize downsample memory usage 

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#297]
Downsample can OOM easily with 16GB.. wonder if we can improve that in any way. 

It uses a lot of memory when downsampling my 2-week block (on top of other mem usage after lot's of compactions maybe). Wonder if that's not some lazy GC issue.

**Comment by Bplotka** [comment]
![image](https://user-images.githubusercontent.com/6950331/38865083-b0ac33aa-4234-11e8-820c-0f6833d96ca5.png)

**Comment by Bplotka** [comment]
20GB not enough as well.

**Comment by Bplotka** [comment]
My block stats:
```
gsutil du -sh "gs://thanos-beta/01CB8HB76TAETC189K7V77VB8G/" 
13.82 GiB   gs://thanos-beta/01CB8HB76TAETC189K7V77VB8G
```

```
 gsutil du -sh "gs://thanos-beta/01CB8HB76TAETC189K7V77VB8G/chunks/"
12.58 GiB   gs://thanos-beta/01CB8HB76TAETC189K7V77VB8G/chunks
```

This guy is... HEAVY

**Comment by felipejfc** [comment]
I've allocated 50GB for mine and it's dying for OOM :/

**Comment by kedare** [comment]
It looks like this has been improved in the last releases ? I don't know if it's related but I don't see any memory spike since one of the last upgrade

**Comment by jdfalk** [comment]
I am still getting OOM on large compacted blocks. We have blocks that are 207GB and after grabbing the block it will eventually eat all system memory until it OOM's. Server memory:
```
              total        used        free      shared  buff/cache   available
Mem:           125G        8.1G        1.3G        124K        116G        116G
Swap:           23G         61M         23G
````

The server also has 32 cores that are being dramatically underutilized.

**Comment by Bplotka** [comment]
Yup, thanks for feedback. Nothing changed in this area, so this becomes an important issue.

**Comment by drax68** [comment]
Reproduced with >200Gb blocks, it tries to obtain that block after being killed by oom and wastes s3 traffic in a loop. Is there a way to disable downsampling until memory usage is fixed?

**Comment by Bplotka** [comment]
@drax68 Makes total sense. 

Added: https://github.com/improbable-eng/thanos/pull/515

Also looking for volounteer to fix this issue. I can help to lead this, but won't have time to solve this in soon-ish time.

**Comment by xjewer** [comment]
I can volunteer, what are you suggesting to look at first? Writing chunk data to a tmp file instead of eat away all heap?

**Comment by Bplotka** [comment]
Thanks @xjewer! 

1. Gather data (!) We are only suspecting what is causing this. We don't want to optimize part of code that is not relevant in memory usage. The easiest way, would be to write some manual unit-test (don't commit it even) with downsampling some mocked medium block and print memory here & there https://golangcode.com/print-the-current-memory-usage/ to be aware what is the current state and if we improve things or not. Don't have any better solution with shortest cycles - that is how I would do it.

2. Chunk data are .. not that large. By design we aggregate all so the size of it is much much more smaller than the source block we are downsampling. We should think about dumping this block only when nothing else can be optimized. When users see 200GB while downsampling I doubt their blocks are 1000GB (: 

3. I assume we stream per series from source block. But the data suggests that somehow the block is buffered. There might be different reasons. Maybe we accidently allocate some byte slice. Maybe we free the memory just fine, but GC is too lazy to actually kill those and we don't release the memory quick enough. There is one good solution - use bytes.Pool, like here: https://github.com/improbable-eng/thanos/blob/master/pkg/store/bucket.go#L163 and use it here:https://github.com/improbable-eng/thanos/blob/master/pkg/compact/downsample/downsample.go#L74 Again, we need to make sure to have something for 1. thing to measure the result.

4. The initial debug https://github.com/improbable-eng/thanos/issues/297#issuecomment-382010391 shows that byte slice with actual aggregated chunks. Maybe you are right that we need true streaming the chunk aggregations as well (per series)?  with some byte.Pool to make sure memory is released? We need data to confirm this, again (:

**Comment by xjewer** [comment]
I tested on my 9GB block. We put all the chunks in-memory.
Here's a pprof list in some time from the downsampling, it continuously wasting the memory, pushing all series to memblock:

```
112          3MB     1.12GB           			newb.addSeries(&series{lset: lset, chunks: downsampleRaw(all, resolution)}) 
113            .          .           			continue 
```
and keep them until writing all that data back to the file:

https://github.com/improbable-eng/thanos/blob/master/pkg/compact/downsample/downsample.go#L128
```
	id, err = comp.Write(dir, newb, origMeta.MinTime, origMeta.MaxTime)
```
So even bytes.Pool won't help in suggested place. 
`GODEBUG=schedtrace=500` shows GC works properly.

**Comment by xjewer** [comment]
>9GB for source block or for downsampled block? I guess for source block, right?
Sure, source block. 

And yes, we're keeping the output block there.
What I see, that initially we loading XORenconded chunks in a source block, which means the size of aggregated to 5m decoded samples would be comparable to source. Here is my result:

```
thanos-production du -h -d 1 .
632M	./01CQKYG30KE5KZJN7GCKAK18GY
5.1G	./01CQKY0N79H5572MDCMG3N0ZKS
10.0G	./01CPPF5VGX7SXDQSVXYYEJKE3Q
```
where:
10.0G - source
5.1G - first pass
632M - second pass

So for the extremely large source block we would waste a huge amount of RAM

**Comment by bwplotka** [comment]
Nice, thanks for those numbers. It seems we are getting somewhere. So definitely output block can be significant I can agree.

So we could avoid this by flush things to file if possible (Let's name it `Stream output block per series`) But still the missing `3.9GB`  (size seen minus output block) is concerning me. In theory we do all per source series. And indeed we are expanding (decoding) XOR chunks in some buffer [here](https://github.com/improbable-eng/thanos/blob/master/pkg/compact/downsample/downsample.go#L96). I.. kind of doubt that single decompressed series has 4GB - are we hitting lazy GC here? somewhere else we buffer as well? Or series is actually 4GB when decompressed? Nevertheless we might be able to stream that part per sample as well (let's call this improvement `Stream downsampling per sample`). This is not that easy, though, but possible.

Any idea where we lost those 4GB? (:

**Comment by xjewer** [comment]
from the discussion with @bwplotka in slack:

1. there was a misunderstanding, diff wasn't exactly 4GB, but some memory has gone indeed, something about 1-1.5 GB
2. interesting point https://github.com/improbable-eng/thanos/blob/3c8546ceef9cf13856d91b9897fa816303fc05b6/cmd/thanos/downsample.go#L228 https://github.com/prometheus/tsdb/blob/master/chunks/chunks.go#L371
we read chunks using pool, but don’t put them back 🤔
3. memBlock anyway is the target for optimisation: has to be handled by series to avoid memory consumption.

The next what I found:
https://github.com/improbable-eng/thanos/blob/master/cmd/thanos/downsample.go#L228 uses `mmap` to open chunk files https://github.com/prometheus/tsdb/blob/master/chunks/chunks.go#L334
For my case, ByteSlices are with `536781921` capacity, which means series' data would be pointed out on this array behind this slice and wouldn't be swept out by GC until the following series will reach next data file.

<details>
<summary>
$ chunks ls -l
</summary>
<p>

```bash
total 19980256
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:36 000001
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:36 000002
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:37 000003
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:37 000004
-rw-r--r--  1 xjewer  staff   511M  6 Sep 03:37 000005
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:37 000006
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:37 000007
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:37 000008
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:38 000009
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:38 000010
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:38 000011
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:38 000012
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:38 000013
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:39 000014
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:39 000015
-rw-r--r--  1 xjewer  staff   512M  6 Sep 03:39 000016
-rwxr-xr-x  1 xjewer  staff   512M  6 Sep 03:39 000017
-rwxr-xr-x  1 xjewer  staff   512M  6 Sep 03:39 000018
-rwxr-xr-x  1 xjewer  staff   459M  6 Sep 03:39 000019
```
</p>
</details>

Summary:
For the time being, the only way is to handle data series by series, not to keep all the output downsampled block in memory

**Comment by bwplotka** [comment]
Agreed, good stuff!

wt., 18 wrz 2018, 01:34 użytkownik xjewer <notifications@github.com>
napisał:

**Comment by tonglil** [comment]
Would we be able to open this issue until the fix? :)

**Comment by daguilarv** [comment]
Is there any update on this improvement?
