### ISSUE TITLE
store: Support Azure Storage

### ISSUE THREAD

**Issue by pharaujo** [improbable-eng/thanos#319]
Add support to use Azure Storage as Thanos long-term storage provider.

I expect to implement this in the near term, but have no availability to do it presently. I'm opening this issue mainly so that if someone else picks this up before me, there would be no duplicate work.

**Comment by Bplotka** [comment]
For this we need:
- Implement this https://github.com/improbable-eng/thanos/blob/master/pkg/objstore/objstore.go#L17 interface.
- Implement flags to configure access to the storage. (as minimum number of flags as possible or we even need to implement https://github.com/improbable-eng/thanos/issues/209 first)
- Use factory to decide what create azuro client: https://github.com/improbable-eng/thanos/blob/master/pkg/objstore/client/factory.go

**Comment by Bplotka** [comment]
The only unknowns here and important factors to have usable Azuro storage are:
- the consistency guarantees (write-read)  -need to be strong!
- latency
- cost per different operations (especially if hosted)

**Comment by vglafirov** [comment]
I am trying to implement it now

**Comment by Bplotka** [comment]
Awesome. Can you make some research on:
> the consistency guarantees (write-read) -need to be strong!

for this storage?

**Comment by andywiens** [comment]
Very interested in this as well. Happy to help if there's something still to be done.

**Comment by sylr** [comment]
Hi, I'm also very interested in Azure storage support!

Cheers.

**Comment by sylr** [comment]
@vglafirov Do you have something that works I could help testing ?

**Comment by vglafirov** [comment]
@sylr I have provider ready and passing objectstore e2e tests. But I am struggling to run some other tests though. You can check it on my fork here: https://github.com/vglafirov/thanos

**Comment by Bplotka** [comment]
Can you share those problems maybe? If you keep those problems only to yourself we cannot help you =D

**Comment by vglafirov** [comment]
@Bplotka Here is the issue I have when I try to build my fork. Already rebased to upstream master, but no luck :(
`make build                                                                                                                                                                                  (aks-prod-us1-a/default)
>> building binaries
 >   thanos
# github.com/vglafirov/thanos/cmd/thanos
cmd/thanos/flags.go:44:17: undefined: cluster.NetworkPeerTypes
cmd/thanos/flags.go:47:11: undefined: cluster.LanNetworkPeerType
cmd/thanos/flags.go:48:8: undefined: cluster.NetworkPeerTypes
cmd/thanos/flags.go:82:22: too many arguments in call to cluster.New
	have ("github.com/vglafirov/thanos/vendor/github.com/go-kit/kit/log".Logger, *"github.com/vglafirov/thanos/vendor/github.com/prometheus/client_golang/prometheus".Registry, string, string, string, string, []string, bool, time.Duration, time.Duration, time.Duration, []byte, string)
	want ("github.com/vglafirov/thanos/vendor/github.com/go-kit/kit/log".Logger, *"github.com/vglafirov/thanos/vendor/github.com/prometheus/client_golang/prometheus".Registry, string, string, string, string, []string, bool, time.Duration, time.Duration, time.Duration)
cmd/thanos/query.go:214:38: cannot use router (type *"github.com/vglafirov/thanos/vendor/github.com/prometheus/common/route".Router) as type *"github.com/improbable-eng/thanos/vendor/github.com/prometheus/common/route".Router in argument to ui.NewQueryUI(logger, nil).Register
cmd/thanos/rule.go:211:14: cannot use notify (type func(context.Context, string, ...*"github.com/vglafirov/thanos/vendor/github.com/prometheus/prometheus/rules".Alert) error) as type "github.com/vglafirov/thanos/vendor/github.com/prometheus/prometheus/rules".NotifyFunc in field value
cmd/thanos/rule.go:377:15: cannot use mgr (type *"github.com/vglafirov/thanos/vendor/github.com/prometheus/prometheus/rules".Manager) as type *"github.com/improbable-eng/thanos/vendor/github.com/prometheus/prometheus/rules".Manager in argument to ui.NewRuleUI
cmd/thanos/rule.go:377:61: cannot use router (type *"github.com/vglafirov/thanos/vendor/github.com/prometheus/common/route".Router) as type *"github.com/improbable-eng/thanos/vendor/github.com/prometheus/common/route".Router in argument to ui.NewRuleUI(logger, mgr, alertQueryURL.String()).Register
cmd/thanos/sidecar.go:68:4: cannot use *reloaderRuleDirs (type []string) as type string in argument to reloader.New
cmd/thanos/sidecar.go:232:20: assignment mismatch: 3 variables but 2 values
cmd/thanos/sidecar.go:232:20: too many errors
!! command failed: build -o /Users/vglafirov/workspace/gocode/src/github.com/vglafirov/thanos/thanos -ldflags -X github.com/vglafirov/thanos/vendor/github.com/prometheus/common/version.Version=0.1.0-rc.2 -X github.com/vglafirov/thanos/vendor/github.com/prometheus/common/version.Revision=b2e798ccfec24e5b5f5da19ef2170c7b2349b848 -X github.com/vglafirov/thanos/vendor/github.com/prometheus/common/version.Branch=master -X github.com/vglafirov/thanos/vendor/github.com/prometheus/common/version.BuildUser=vglafirov@DESKTOP-Q72F5LO.redmond.corp.microsoft.com -X github.com/vglafirov/thanos/vendor/github.com/prometheus/common/version.BuildDate=20180831-10:35:18  -a -tags netgo github.com/vglafirov/thanos/cmd/thanos: exit status 2
make: *** [build] Error 1`

**Comment by vglafirov** [comment]
@Bplotka Never mind. I figured this out. Had do add improbable-eng/thanos to Gopkg.toml

**Comment by vglafirov** [comment]
Here we go.
#502

**Comment by vglafirov** [comment]
#502 Has been merged. I think we can close this issue
