### ISSUE TITLE
Problem parsing json returned from Thanos

### ISSUE THREAD

**Issue by nmaupu** [improbable-eng/thanos#320]
Hey!

I am currently facing a problem using Grafana which cannot parse json returned from Thanos.
I noticed a weird behavior when calling API, I get a `warnings` field set to null:
```
curl http://thanos-query:9090/api/v1/query?query=node_cpu | jq
{
[...]
    "warnings": null
  }
}
```

According to https://github.com/improbable-eng/thanos/blob/3278b4687e25683b082f9815e5ff0b2eb5169f91/pkg/query/api/v1.go#L84
this field should not be there thanks to `omitempty` but the field appears anyways.

This prevents the json to be parsed correctly. Do you have any insight on this ?

**Comment by nmaupu** [comment]
After further investigation, it comes from this struct :
https://github.com/improbable-eng/thanos/blob/3278b4687e25683b082f9815e5ff0b2eb5169f91/pkg/query/api/v1.go#L168

We can see that the Warnings field does not have the `omitempty` option set.
Setting it fixes this issue.

I can make a PR for that if you want me to. I am just wondering if there is a reason that this field is not `omitempty` already...

**Comment by Bplotka** [comment]
Hey, thanks for reporting the issue.

What exactly Grafana error you have seen?

yea omitempty should work, but actually, you can have "some" warnings on query filled so it will crash grafana as well (: So if Grafana does not accept additional fields we need some better solution anyway (for example put warnings only for certain user agents)

**Comment by Bplotka** [comment]
We need `omitempty` for sure, PR would be awesome.

But wonder on behaviour of Grafana if this is actually filled (:

**Comment by nmaupu** [comment]
I guess Grafana does not like the bare `null` appearing in the field. If warnings is set, it would contain strings and grafana should not complain about that. I hope.

I am preparing the PR

**Comment by Bplotka** [comment]
Hope based solutions are the best! (:

Thanks!

**Comment by Bplotka** [comment]
Fix merged. The only question is how grafana handles filled warnings.
