### ISSUE TITLE
query: support web.external-url flag

### ISSUE THREAD

**Issue by danhcole** [improbable-eng/thanos#364]
Prometheus has a `--web.external-url` flag used for generating relative and absolute links back to prom itself.  Currently Thanos doesn't support this option, but it would be nice to support compatibility with existing Prometheus deploys.  

Thanos already uses the Prometheus `common/route` package, which supports `route.WithPrefix()` (which is what Prometheus itself uses).

Would you be open to a PR to add this?

**Comment by Bplotka** [comment]
Is there any way we can avoid this? It proved (especially in Prometheus from what I heard) to be really hard to maintain.

What are the use cases? Anything that blocs you right now?

**Comment by danhcole** [comment]
We run prom behind a reverse proxy and with an extra path added, and so use this flag.  We'd like Thanos to be as drop-in as possible.

When testing locally, I forked and added the flag based on how it's done in Prometheus, and it seemed a pretty simple change, since the functionality is already there in the `route` package.

**Comment by Bplotka** [comment]
Feel free to put PR for it, we can discuss it (:

**Comment by NikonNLG** [comment]
@danhcole Can you please share your path? I'm new in golang, but use prometheus behind proxy too, so can't use thanos-sidecar as well

**Comment by Bplotka** [comment]
You mean thanos-query @NikonNLG ? You don't need anything like this for sidecar or any other thing beside query.

**Comment by Bplotka** [comment]
Some quick view on recent Prometheus issues shows how painful is to maintain this to be useful for all the use cases:
- https://github.com/prometheus/prometheus/issues/4241
- https://github.com/prometheus/prometheus/pull/4256
- https://github.com/prometheus/prometheus/issues/4163
- https://github.com/prometheus/prometheus/issues/4004

Can we talk about exact places where some external URL should be used?

If really needed I would aim to grab the exact Prometheus external URL logic to make sure we have conistent logic. But would love to avoid this (:

**Comment by danhcole** [comment]
We ended up using a different workaround, but if there's interest, I can still put in a PR.  

For what it's worth, the fix I had was using more or less the exact Prometheus logic.  I agree that maintaining it against the way Prometheus works going forward could be painful, especially in regards to the interaction between `--web.external-url` and `--web.route-prefix`.

**Comment by Bplotka** [comment]
On the other note @danhcole , what was your workaround? Maybe that workaround will work for others? (:

**Comment by danhcole** [comment]
Oh, of course!  We started using Grafana's 'HTTP Auth -- With Credentials' option, and worked out the proper CORS headers in our lb/proxy.

Our issue also had nothing to do with sidecar (or Thanos at all, per se).  Our Prometheus boxes were also run using the same setup, and had the same fix applied at the Grafana level.

**Comment by NikonNLG** [comment]
@Bplotka I have one domain for both grafana and prometheus, so I need to setup path like `/prom` to access to prometheus web ui. Unfortunately, there's no chance to make additional domain for direct access to prometheus.
