### ISSUE TITLE
sidecar: Warn or even don't allow shipping non-default sized blocks.

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#374]
Users are trying to achieve quicker upload with attempts like
```
          - "--storage.tsdb.min-block-duration=1m"
          - "--storage.tsdb.max-block-duration=1m"
```
Which is extremely unsafe and should not be done unless you know what you are doing.

**Comment by GiedriusS** [comment]
https://github.com/improbable-eng/thanos/commit/eddaf1138a107ed5304d7cfb66a43de31a8e56da#diff-7ce94421c80fe10fd04ce3e2480209c9R348 fixed here 😄
