### ISSUE TITLE
Sync between replica copies

### ISSUE THREAD

**Issue by muralikanagala** [improbable-eng/thanos#379]
Hello there,

I have a couple of questions about high availability of prometheus servers in a region/datacenter.

Does Thanos support back-filling the data if one of the nodes in a HA pair dies and restored back?
Also can I use a third party HA like F5 to load balance between Quariers in multiple regions/datacenters?

Thank you!

**Comment by Bplotka** [comment]
Hello, 

Sorry for delayed response.

> Does Thanos support back-filling the data if one of the nodes in a HA pair dies and restored back?

No, but it is totally not needed. With Thanos you never access Prometheus + sidecar node directly. You use `thanos-query` that gives you single PromQL endpoint. It does the deduplication to make sure if one replica is lacking of data we fill it from another replica.

> Also can I use a third party HA like F5 to load balance between Quariers in multiple regions/datacenters?

Can you explain the example case for this? You can put whatever you want above Queriers, they are stateless. (:

**Comment by bwplotka** [comment]
No response back, closing.
