### ISSUE TITLE
kube: error: unable to read client-key, permission denied trying to run  bash ./kube/run-local.sh -i -d none

### ISSUE THREAD

**Issue by irinafakotakis** [improbable-eng/thanos#384]
**Thanos, Prometheus and Golang version used**
Golang version 1.10.3
Prometheus 2.3.0

**What happened**
got error 
`error: unable to read client-key [...]/go/src/github.com/improbable-eng/thanos/kube/.minikube/client.key for minikube due to open [...]/go/src/github.com/improbable-eng/thanos/kube/.minikube/client.key: permission denied`
`Cluster is running. See README.md for example deployments you can apply.`

when trying to run PromLTS kubernetes test setup, at step:` bash ./kube/run-local.sh -i -d none`

Subsequently, I cannot run the example setup.

**What you expected to happen**
I expect to be able to run the example setup.

**How to reproduce it (as minimally and precisely as possible)**:
In the thanos directory, running ` bash kube/run-local.sh -i -d none`

**Comment by bwplotka** [comment]
This piece was removed.
