### ISSUE TITLE
sidecar : check exists: stat s3 object: Access Denied.

### ISSUE THREAD

**Issue by vishksaj** [improbable-eng/thanos#394]
Hi Team,

I am having 2 prometheus clusters (4 instances). I want to configure thanos for those.  As primary step i started configuring sidecar and got access denied error.

./thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus --s3.endpoint s3-us-west-1.amazonaws.com --s3.bucket prometheus-backup --s3.access-key XXXXXXXXXXXX --s3.signature-version2

level=info ts=2018-06-28T14:56:39.150915454Z caller=flags.go:51 msg="StoreAPI address that will be propagated through gossip" address=10.65.58.166:10901
level=info ts=2018-06-28T14:56:39.156908539Z caller=sidecar.go:270 msg="starting sidecar" peer=
level=info ts=2018-06-28T14:56:39.157006815Z caller=sidecar.go:215 component=store msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2018-06-28T14:56:39.157020254Z caller=main.go:240 msg="Listening for metrics" address=0.0.0.0:10902
level=error ts=2018-06-28T14:56:39.4122846Z caller=shipper.go:165 msg="shipping failed" block=01CH0N8K0M9HAZ3DKN60Z8RR7G err="check exists: stat s3 object: Access Denied."
level=error ts=2018-06-28T14:56:39.415855697Z caller=shipper.go:165 msg="shipping failed" block=01CH0W4A8FY6G70M05HTH7CDGM err="check exists: stat s3 object: Access Denied."
level=error ts=2018-06-28T14:56:39.419042541Z caller=shipper.go:165 msg="shipping failed" block=01CH1301M3AWNEXWR8S60P31BV err="check exists: stat s3 object: Access Denied."
level=error ts=2018-06-28T14:56:39.422402706Z caller=shipper.go:165 msg="shipping failed" block=01CH19VRXF3NYJN6SF5J8RFSR8 err="check exists: stat s3 object: Access Denied."
    
Configured using IAM user and role as mentioned : https://github.com/improbable-eng/thanos/blob/master/docs/storage.md

I am using Thanos : 
Version | v0.1.0-rc.1
-- | --
6cc17fe3efc017ec1a6200726433cbb47551b787
master

Prometheus : 
Version | 2.2.1
-- | --
bc6058c81272a8d938c05e75607371284236aadc
HEAD

Any help would be appreciated!

I am very eager to make it work since it is a great tool!

**Comment by Bplotka** [comment]
Well, these IAM rules works for others (unless tested wrongly), so you might want to maybe make them more permissive to check what's going on..  (: maybe you have special permission on these.

**Comment by Bplotka** [comment]
Maybe signature version is wrong? Access Denied error is kind of clear what is the problem. (: But not easy to debug on AWS side.

**Comment by Bplotka** [comment]
No known issue that would limit the Prometheus version. Newest should work (: (2.3.1)

**Comment by harmw** [comment]
Looks like I'm running into the same issue here :)

Just verified if my policy is correct, which it seems to be:

```
# aws s3 ls metrics
                           PRE test/
```

After that running `thanos` yields the above error:

```
Aug 02 20:01:34 prometheus-i-08d1150031a732b67 docker[28264]: level=error ts=2018-08-02T20:01:34.227107477Z caller=shipper.go:166 msg="shipping failed" block=01CKY05KZWP9Z9SCBN7CXFVXYN err="check exists: stat s3 object: Access Denied."
```

Started as:
```
/usr/bin/docker run \
    --name prometheus-thanos-sidecar \
    --publish "10902:10902" \
    --volume "/services/prometheus-data/tsdb/:/tsdb:rw" \
    --env "S3_SECRET_KEY=IAMFTW" \
    --net "bridge" \
    wehkamp/prometheus-thanos-sidecar:0.1.0.rc2 \
      --prometheus.url=http://prometheus.service.consul:9090 \
      --s3.bucket=metrics \
      --s3.endpoint=s3.eu-west-1.amazonaws.com \
      --s3.access-key=IAMFTW \
      --tsdb.path=/tsdb \
      --s3.signature-version2
```

It looks a bit weird having to set `S3_SECRET_KEY` and `--s3.access-key` though, but without those we observe the following:

```
Aug 02 19:52:38 prometheus-i-08d1150031a732b67 docker[20798]: level=info ts=2018-08-02T19:52:38.952767473Z caller=sidecar.go:233 msg="No GCS or S3 bucket was configured, uploads will be disabled"
```

**Comment by Bplotka** [comment]
> It looks a bit weird having to set S3_SECRET_KEY and --s3.access-key
@harmw That might be what is incorrect in your configuration then, becuase these keys are 2 different things:
https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys

BTW we just landed https://github.com/improbable-eng/thanos/pull/450 which might help you to get AWS access through different means.

**Comment by harmw** [comment]
yes exactly, _but_ as I'm using an IAM profile attached to my EC2 instance it shouldn't even be depending on either `secret-key` or `access-key`. The manual test with `aws-cli` indicates that too.

I was already tracking #450 so when that got merged I immediately started building `master` (so far I was using the `rc2` tag) 😄 Let's see what happens, thanks 👍

**Comment by harmw** [comment]
awesome, it's pushing to S3 now 🎉
