### ISSUE TITLE
Store: when support openTSDB, rrdtool or whisper

### ISSUE THREAD

**Issue by wolfzhaoshuai** [improbable-eng/thanos#409]
Now I found the store module only support GCS and S3, do you have any plan to support other store system, like openTSDB, rrdtool or whisper.

**Comment by Bplotka** [comment]
Yes, we will accept PRs if anyone requires such object store!

All you need is a `Bucket` interface implementation explained here: https://github.com/improbable-eng/thanos/blob/master/docs/storage.md

There are already some users that wanted to start working on:
https://github.com/improbable-eng/thanos/issues/326
and
https://github.com/improbable-eng/thanos/issues/319

 Also for S3 we use `minio` client which supports multiple object stores via special minio gateways (and `minio` storage itself). 

Hope you can find this useful.
