### ISSUE TITLE
"Cost" description not clear

### ISSUE THREAD

**Issue by kamelkev** [improbable-eng/thanos#416]
In docs/design is this description:

> Suppose we want to store 100TB of metric data. At about 1.07 bytes/sample in total data size, this is equivalent to storing 6.5 years of data across an average of 1 million active time series.
The cost for this amount of metric data would cost approximately $2400/month on top of the baseline Prometheus setup. In return, being able to reduce the retention time of Prometheus instances from weeks to hours will provide cost savings for local SSD or network block storage (typically $0.17/GB) and reduce memory consumption. This calculation does not yet account for shorter retention spans of low-priority data and downsampling.

Would be helpful if we include a reference to how many samples per minute we're making such that others can follow up on this math.

**Comment by Bplotka** [comment]
I am pretty sure it is for 15s scrape internval so 4 samples / minute x 1 mln actibe series = 4mln samples / min (:

**Comment by kamelkev** [comment]
Hi @Bplotka,

Maybe I'm missing something, but:

3,416,400 min * 4mln samples / min *  1.07 bytes/sample = 14,622,192,000,000 bytes, or 13.3 TB? I thought we wanted 100TB?

I think instead it's 30 samples / min:
3,416,400 min * 30mln samples / min *  1.07 bytes/sample = 109,666,440,000,000, or 100 TB.

For reference: there are 3,416,400 min within 6.5 years.

If this is correct it would be very useful for those of us in the community to have that note added to the cost section.

**Comment by Bplotka** [comment]
yup, broken math (: Let's update this. 30 mln samples/ min is quite large with 1 mln time series the interval would be 2s which is not real.

**Comment by kamelkev** [comment]
Maybe while here we can update the retention period as well? Right now it's listed as 6.5 years, which is a little usual.

I more frequently see 3, 5 and 7 as requirements, so using one of these might be helpful for an apples to apples comparison.

**Comment by tonglil** [comment]
I think if you can provide the values for each variable and make the math line up, that's all that matters.

Then people can calculate the costs for their own use cases :)

I was just doing this math earlier this week as well.

**Comment by Bplotka** [comment]
Cool, let's do this. I think this 2s interval in the example was to showcase the ridiculous amount of data and still how cheap it is.

I think we can make this more real, agree

**Comment by kamelkev** [comment]
Agree - but the devil's in the details. I monitor on a 1s interval... every 2s appears "fake" to me. :)
