### ISSUE TITLE
Thanos query error: "refresh cluster could not join peers" 

### ISSUE THREAD

**Issue by jackyym** [improbable-eng/thanos#426]
**Thanos, Prometheus and Golang version used**
Prom/prometheus:v2.2.0-rc.0 docker image, so the prom version should be v2.2.0
Golang version is go 1.10.3
Thanos version is master and we build it by ourselves.
build date: 20180713-06:00:21
go version: go1.10.3

Prom and Thanos sidecar are on the same node.
thanos query are on the other node 

**What happened**
thanos query can start but with error and no metric query data pop-up query portal
sudo ./thanos query --http-address 0.0.0.0:19192 --grpc-address 0.0.0.0:19092 --cluster.address 0.0.0.0:19591 --cluster.advertise-address 127.0.0.1:19591 --cluster.peers  127.0.0.1:19391

level=info ts=2018-07-13T06:36:20.367140941Z caller=flags.go:53 msg="StoreAPI address that will be propagated through gossip" address=172.22.9.33:19092
level=info ts=2018-07-13T06:36:20.378266614Z caller=flags.go:68 msg="QueryAPI address that will be propagated through gossip" address=172.22.9.33:19192
level=warn ts=2018-07-13T06:36:20.378318221Z caller=cluster.go:123 component=cluster err="this node advertises itself on an unroutable address" host=127.0.0.1 port=19591
level=warn ts=2018-07-13T06:36:20.378334909Z caller=cluster.go:124 component=cluster err="this node will be unreachable in the cluster"
level=warn ts=2018-07-13T06:36:20.37834434Z caller=cluster.go:125 component=cluster err="provide --cluster.advertise-address as a routable IP address or hostname"
level=info ts=2018-07-13T06:36:20.379778438Z caller=query.go:256 msg="starting query node"
level=info ts=2018-07-13T06:36:20.379846993Z caller=query.go:248 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:19092
level=info ts=2018-07-13T06:36:20.379835502Z caller=query.go:230 msg="Listening for query and metrics" address=0.0.0.0:19192

level=error ts=2018-07-13T06:37:20.381500448Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391
level=error ts=2018-07-13T06:38:20.381941146Z caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=127.0.0.1:19391

**What you expected to happen**

We need idea on how to fix "refresh cluster could not join peers" error

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by Bplotka** [comment]
Added PR to show actual error, sorry for that no being there yet ): We will see actual error then.
