### ISSUE TITLE
index.GatherIndexIssueStats() assumes Chunk is non-nil

### ISSUE THREAD

**Issue by asbjxrn** [improbable-eng/thanos#431]
When attempting to downsample a block compacted by Prometheus I get panics in GatherIndexIssueStats() as it is trying to calculate the checksum of chunks in the following snippet. I think some handing of the case where Chunk is nil is needed.

```
			if c.MinTime == c0.MinTime && c.MaxTime == c0.MaxTime {
				ca := crc32.Checksum(c0.Chunk.Bytes(), castagnoli)
				cb := crc32.Checksum(c.Chunk.Bytes(), castagnoli)
				if ca == cb {
					// Duplicate.
					stats.DuplicatedChunks++
				}
				ooo++
			}

```

c and c0 may look like this (Printf %v format):

```
c0: {51623238719 <nil> 1530331200000 1530332985000}
c: {51623238909 <nil> 1530331200000 1530332985000}

```

There are comments in chunks.Meta definition saying Chunk may not be set if the Ref is set:

```
// Meta holds information about a chunk of data.
type Meta struct {
	// Ref and Chunk hold either a reference that can be used to retrieve
	// chunk data or the data itself.
	// Generally, only one of them is set.
	Ref   uint64
	Chunk chunkenc.Chunk

	MinTime, MaxTime int64 // time range the data covers
}

```

**Comment by Bplotka** [comment]
We can fix it, but would love to know why Prometheus compacted blocks are different... It is same compaction.

**Comment by asbjxrn** [comment]
I don't know. They may not be, I just added that info in case it was significant.

Could it be related to some issue happening during scraping. (possibly same endpoint scraped for two different jobs so some race condition may be involved as well. I know we used to have some misconfiguration like that.)

It happened 37699 times in 2 blocks (162h lvl 5 compaction), but only happened for metrics collected from two of the servers scraped by prometheus. And it was almost all from the node exporter on one of the servers. Only a handful from another server and job. 

When it happened, it happened across a number of metrics, there were only 88 different timespans. (minTime, maxTime) 

The vast majority of the timespans were ~ 30 minutes, some were ~60 min and a few ~15min.

**Comment by Bplotka** [comment]
Interesting, thanks for details. Maybe worth to put issue on Prometheus as well? 

Basically the issue here is that `Chunk chunkenc.Chunk` is nil, and you said (and you are right) that: 
> There are comments in chunks.Meta definition saying Chunk may not be set if the Ref is set:

However I am pretty sure that when chunk is nil, then Ref is not set either in your case. Chunk is not checked to be nil, because this method of reading the chunks assures that chunk is always not-nil (: I will make this code flow handle that, but still a nil chunk is within blocks is something wrong and need to be reported upstream (Prometheus).

**Comment by asbjxrn** [comment]
Ref should be first values in the structs, I think:

```
c0: {51623238719 <nil> 1530331200000 1530332985000}
c: {51623238909 <nil> 1530331200000 1530332985000}
```

**Comment by dnr** [comment]
I think I'm hitting this also:

```
level=debug ts=2018-07-19T21:09:24.695545944Z caller=compact.go:166 msg="download meta" block=01CJT5F97BK7ZEY9VJT4DWD1MW
level=debug ts=2018-07-19T21:09:24.72254922Z caller=compact.go:184 msg="block is too fresh for now" block=01CJT5F97BK7ZEY9VJT4DWD1MW
level=info ts=2018-07-19T21:09:24.7226022Z caller=compact.go:132 msg="start of GC"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7bf70c]

goroutine 70 [running]:
github.com/improbable-eng/thanos/pkg/block.GatherIndexIssueStats(0xf14100, 0xc4203592c0, 0xc4204ab100, 0x75, 0x16459938f00, 0x1645d705400, 0xbc05, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/improbable-eng/thanos/pkg/block/index.go:317 +0x52c
github.com/improbable-eng/thanos/pkg/compact.(*Group).compact(0xc4206eec80, 0xf20880, 0xc420195000, 0xc4200ab3e0, 0x54, 0xf1e880, 0xc4201a5270, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/improbable-eng/thanos/pkg/compact/compact.go:695 +0x7ea
github.com/improbable-eng/thanos/pkg/compact.(*Group).Compact(0xc4206eec80, 0xf20880, 0xc420195000, 0xc4200bd9a0, 0xf, 0xf1e880, 0xc4201a5270, 0x0, 0x0, 0x36de30, ...)
        /go/src/github.com/improbable-eng/thanos/pkg/compact/compact.go:464 +0x185
main.runCompact.func2(0x48, 0xe9b000)
        /go/src/github.com/improbable-eng/thanos/cmd/thanos/compact.go:144 +0x21a
main.runCompact.func3(0x0, 0x0)
        /go/src/github.com/improbable-eng/thanos/cmd/thanos/compact.go:191 +0x277
github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run.func1(0xc4201a3260, 0xc42033cd20, 0xc420193740)
        /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/improbable-eng/thanos/vendor/github.com/oklog/run.(*Group).Run
        /go/src/github.com/improbable-eng/thanos/vendor/github.com/oklog/run/group.go:37 +0xa8
```

I'm not an expert on prometheus internals, but if there's anything I can do to help debug, please let me know.

**Comment by TransactCharlie** [comment]
HI all - @Bplotka you mentioned you'd make the code flow handle this. Any PR or news on this. We hit this occasionally also.

**Comment by jojohappy** [comment]
I also meet the problem, and I print out the value of instance of chunks `c` and `c0`.
```
fn: /var/thanos-compact/compact/0@{monitor="prometheus",replica="prom-thanos-s3-0"}/01CRFAS69HNGJKKRMQ7QKKA02C/index
c: chunks.Meta{Ref:0x22827b6, Chunk:chunkenc.Chunk(nil), MinTime:1538078400000, MaxTime:1538078400000}
c0: chunks.Meta{Ref:0x228279f, Chunk:chunkenc.Chunk(nil), MinTime:1538078400000, MaxTime:1538078400000}
```

As @asbjxrn said, the `Chunk chunkenc.Chunk` is nil, but it has a stranger appearance, the `MinTime` and `MaxTime` are different with the `meta.json` in this block and as same as each other.

Here is the content of `meta.json`
```json
{
	"version": 1,
	"ulid": "01CRFAS69HNGJKKRMQ7QKKA02C",
	"minTime": 1538064000000,
	"maxTime": 1538092800000,
	"stats": {
		"numSamples": 849990243,
		"numSeries": 1443007,
		"numChunks": 7630195
	},
	"compaction": {
		"level": 2,
		"sources": [
			"01CRE6DVYK9YDPEG5KT7FD75VP",
			"01CRED9K6KN835FMC79S0RBHXC",
			"01CREM5AEMM36RT49APRZ5Y60M",
			"01CREV11PMCJTJQ6FZTPCV7QJA"
		]
	},
	"thanos": {
		"labels": {
			"monitor": "prometheus",
			"replica": "prom-thanos-s3-0"
		},
		"downsample": {
			"resolution": 0
		},
		"source": "compactor"
	}
}
```

So is it something wrong for the compact processing? @bwplotka

**Comment by bwplotka** [comment]
So I added PR for fix to handle problem gracefully - was wrong - obviously ref was only fileld not chunks encoding, so I was wrong.

But the issue itself should not happen. And compactor will halt now anyway (just with proper message).

The @jojohappy info is insideful.. It seems we have just ghost chunks, that has just one sample or maybe even nothing. And also this is already compacted block (level 2). Worth to track this down.

**Comment by bwplotka** [comment]
This was fixed.
