### ISSUE TITLE
I appear to be alone in the cluster

### ISSUE THREAD

**Issue by jackyym** [improbable-eng/thanos#434]
Thanos: 0.1.0-rc.2 (branch: master, revision: c14e33b9ceb37b019bc08d641f9b65c3b6d31f4c)
Prometheus: v2.3.2
Golang version: go1.10.3 linux/amd64

I have 3 nodes (node A  IP: 172.22.9.150, node B IP: 172.22.9.33, node C IP：172.22.11.100)

I  deploy 2 prometheus instances config as replica A and B then start them with sidecar like:

node A:  /gopath/src/github.com/improbable-eng/thanos/thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus_data0 --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391 --cluster.advertise-address 127.0.0.1:19391 --cluster.peers 127.0.0.1:19391 --http-address 0.0.0.0:19191

node B: /gopath/src/github.com/improbable-eng/thanos/thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus_data0 --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391 --cluster.advertise-address 127.0.0.1:19391 --cluster.peers 172.22.9.150:19391 --http-address 0.0.0.0:19191

then I start query at node C：
/gopath/src/github.com/improbable-eng/thanos/thanos query --http-address 0.0.0.0:19192  --cluster.address 0.0.0.0:19591 --cluster.advertise-address 127.0.0.1:19591 --cluster.peers 172.22.9.150:19391

then I  get  no data at http://172.22.11.100:19192/graph

both of the tow roles log show "I appear to be alone in the cluster"

level=warn ts=2018-07-16T15:07:09.12822314Z caller=cluster.go:300 component=cluster NumMembers=1 msg="I appear to be alone in the cluster"
level=warn ts=2018-07-16T15:07:19.128205924Z caller=cluster.go:300 component=cluster NumMembers=1 msg="I appear to be alone in the cluster"
level=warn ts=2018-07-16T15:07:29.128220957Z caller=cluster.go:300 component=cluster NumMembers=1 msg="I appear to be alone in the cluster"

I thik I have somethig wrong at the command.pls help me.

**Comment by Bplotka** [comment]
A couple of things:

- You cannot have local advertise address: `--cluster.advertise-address 127.0.0.1:1939` it simply does not make sense if you have remote peers (in different nodes)
- You seem to have 3 "peers", each on a different node but 2 peers has only one cluster peer: ` --cluster.peers 172.22.9.150:19391`. Newest thanos has cluster refresh join logic, but still it would be nice to have peers joining sooner, with a valid cluster peers configuration. All peers  should have other peers as each `--cluster.peers`.
- Node A peer has `--cluster.peers 127.0.0.1:19391` which does not make sense - do you want this guy tries to do gossip cluster with itself?

Overall:
- don't specify `--cluster.advertise-address`. In your case, Thanos should deduct this automatically
- put each `--cluster.peers` for each peer in each component (query, sidecar) etc using remote IPs.

Let me know if this works, if not will reopen.

**Comment by jackyym** [comment]
@Bplotka ，hi my dear friend.It is works to me. I can get all replica data from 172.22.11.100:19192（query node） and I config one sidecar --cluster.peers 172.22.11.100:19391 but it's log show "caller=cluster.go:275 component=cluster msg="refresh cluster could not join peers" peers=172.22.11.100:19391"

all my command is ：

sidecar：172.22.9.150
/gopath/src/github.com/improbable-eng/thanos/thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus_data0 --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391  --cluster.peers 172.22.11.100:19391 --http-address 0.0.0.0:19191

sidecar：172.22.9.33
/gopath/src/github.com/improbable-eng/thanos/thanos sidecar --prometheus.url http://localhost:9090 --tsdb.path /prometheus_data0 --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391  --cluster.peers 172.22.9.150:19391 --http-address 0.0.0.0:19191

query：172.22.11.100
/gopath/src/github.com/improbable-eng/thanos/thanos query --http-address 0.0.0.0:19192 --grpc-address 0.0.0.0:19092 --cluster.address 127.0.0.1:19391  --cluster.peers 172.22.9.33:19391 --query.replica-label replica
