### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by Jerryhax** [improbable-eng/thanos#444]
when I run a make after go get thanos,I got this in my Console：
>[jerry@localhost thanos]$ make
> fetching dep from 45be32ba4708aad5e2aa8c86f9432c4c4c1f8da2 revision
> #cd /home/jerry/data/thanos/src/github.com/golang/dep; git pull --ff-only
>From https://github.com/golang/dep
>    Bc152799..ba8d7503 master -> origin/master
>You are not currently on a branch.
>Please specify which branch you want to merge.
>See git-pull(1) for details.
>
>     Git pull <remote> <branch>
>
>Package github.com/golang/dep/cmd/dep: exit status 1
>Make: *** [Makefile:142:/home/jerry/data/thanos/bin/dep-45be32ba4708aad5e2a] Error 1

# version:
**Thanos:0.1.0-rc.2
Prometheus：2.3.2 
and Golang version：go1.10.1 linux/amd64

Uncomment and fill if you use not casual environment or if it might be relevant.

**Environment**:
- OS (e.g. from /etc/os-release):
> #cat /etc/os-release
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

- Kernel (e.g. `uname -a`):
> #uname -a
Linux localhost.localdomain 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

How can I solve it?

**Comment by xjewer** [comment]
Your dep package isn't on any branch, as it said
>You are not currently on a branch.

```
cd $GOPATH/src/github.com/golang/dep
git reset HEAD --hard && git checkout master
cd -
```
and try `make` again

**Comment by Bplotka** [comment]
Yea, clearly our makefile is not perfect. We should install proper dep version outside of user `GOPATH`. 

Valid issue, but help would be nice (:

**Comment by Jerryhax** [comment]
After I `make` again ,I got :
> [jerry@localhost thanos]$ make
 fetching dep from 45be32ba4708aad5e2aa8c86f9432c4c4c1f8da2 revision
 dep ensure
The following issues were found in Gopkg.toml:
  ✗ unable to deduce repository and source type for "cloud.google.com/go": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://cloud.google.com/go?goget=1": Get http://cloud.google.com/go?go-get=1: dial tcp 172.217.24.14:80: connect: connection refused
  ✗ unable to deduce repository and source type for "golang.org/x/net": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/net?go-get=1: Get http://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:80: connect: connection refused
  ✗ unable to deduce repository and source type for "golang.org/x/sync": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/sync?go-get1": Get http://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:80: connect: connection refused
  ✗ unable to deduce repository and source type for "google.golang.org/api": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/api?go-get=1": Get http://google.golang.org/api?go-get=1: dial tcp 216.239.37.1:80: connect: connection refused
  ✗ unable to deduce repository and source type for "google.golang.org/grpc": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://google.golang.org/gpc?go-get=1": Get http://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:80: connect: connection refused
ProjectRoot name validation failed
make: *** [Makefile:128：vendor] 错误 1


I run src/github.com/improbable-eng/thanos/cmd/thanosmain.go,then 

> jerry@localhost thanos]$ go build main.go 
#command-line-arguments
./main.go:63:2: undefined: registerSidecar
./main.go:64:2: undefined: registerStore
./main.go:65:2: undefined: registerQuery
./main.go:66:2: undefined: registerRule
./main.go:67:2: undefined: registerCompact
./main.go:68:2: undefined: registerBucket
./main.go:69:2: undefined: registerDownsample

what is wrong？any suggestion?

**Comment by Bplotka** [comment]
Well, 

1.  `make deps` could not get all deps because of flaky network (connection refused)
2. you cannot build thanos with just `main.go` because it ignores rest files in the same dir. `make build` should help you

@jojohappy submitted fix to the make deps, which should fix this issue, let us know if it is not the case. 

Cheers! (:

**Comment by Jerryhax** [comment]
[jerry@localhost thanos]$ go build .
# github.com/improbable-eng/thanos/pkg/objstore
../../pkg/objstore/objstore.go:235:32: cannot use b.opsDuration.WithLabelValues(op) (type prometheus.Observer) as type prometheus.Histogram in argument to newTimingReadCloser:
        prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
../../pkg/objstore/objstore.go:250:32: cannot use b.opsDuration.WithLabelValues(op) (type prometheus.Observer) as type prometheus.Histogram in argument to newTimingReadCloser:
        prometheus.Observer does not implement prometheus.Histogram (missing Collect method)

**Comment by jojohappy** [comment]
@Jerryhax Could you provide the status of the project's dependencies  with `dep status`? In my env, I could not replicate that.

**Comment by jojohappy** [comment]
I found that Prometheus/client_golang has been removed function Set() at v0.9.0-pre1. #247 to see the detail. So you should make sure your Prometheus/client_golang version is 0.8.0.

**Comment by Jerryhax** [comment]
@jojohappy 
> [jerry@localhost thanos]$ dep status
/home/jerry/data/thanos/src/github.com/improbable-eng/thanos is not within a known GOPATH/src


I am sure that the version of Prometheus/client_golang I am using is 0.8.0.

**Comment by Jerryhax** [comment]
error:Cannot use 'b.opsDuration.WithLabelValues(op)' (type "github.com/prometheus/client_golang/prometheus".Observer) as type "github.com/prometheus/client_golang/prometheus".prometheus.Histogram
![image](https://user-images.githubusercontent.com/16162773/43386051-0b427ca2-9415-11e8-8b16-698b4bb8c1ce.png)

and error @src/thanos/cmd/thanos/query.go line181 :
Cannot use 'reg' (type "github.com/prometheus/client_golang/prometheus".*prometheus.Registry) as type "github.com/prometheus/prometheus/vendor/github.com/prometheus/client_golang/prometheus".prometheus.Registerer less... (Ctrl+F1) 
Reports incompatible types.

**Comment by Jerryhax** [comment]
@jojohappy 

> [jerry@localhost thanos]$ make build
               >>dep ensure
make: execvp: /home/jerry/data/proth/bin/dep-45be32ba4708aad5e2a: Permission denied
make: *** [Makefile:133：vendor] 错误 127
