### ISSUE TITLE
Docs refer multiple times to use slack, but there's no clear instructions on signing up

### ISSUE THREAD

**Issue by paulcdejean** [improbable-eng/thanos#446]
I signed up for slack under the name paul-reviewpush, and there's no ability to read or write anything.

If the slack is for contributors only, employees of improbable-engineering only, or so on it should mention that in contributing.md or similar.

Rules and guidelines for interactions there would also be good to mention, even if they are repeated in a slack motd or similar.

Personally I think some kind of community help channel would be useful to have, but even if there is a decision not to have an open one, it would be helpful to clear that up, so that people don't think they made some technical mistake in the sign up process.

**Comment by Bplotka** [comment]
> and there's no ability to read or write anything.
Sorry, what do you mean? (: 

Slack is open for everyone who sign. Have you tried to search for any channel? `#thanos` and `#thanos-dev` channel is what you need (: 

Good point with help channel. Will do!

**Comment by Bplotka** [comment]
Thanks for reporting it, I created `#help` channel for new guests.
