### ISSUE TITLE
Compilation Failure 

### ISSUE THREAD

**Issue by dhbarman** [improbable-eng/thanos#449]
**Thanos, Prometheus and Golang version used**

Thanos version: 0.1.0-rc.2

>go version
go version go1.10.1 darwin/amd64

**What happened**

Compilation Failed 

**What you expected to happen**

Successful compilation

**How to reproduce it (as minimally and precisely as possible)**:

Run make 

**Full logs to relevant components**

<details>Logs
<p>

 make
>> formatting code
>> errchecking the code
/Users/dbarman/Work/Go/bin/errcheck -verbose -exclude .errcheck_excludes.txt ./cmd/... ./pkg/... ./test/...
Excluding (github.com/improbable-eng/thanos/vendor/github.com/go-kit/kit/log.Logger).Log
Excluding fmt.Fprintln
Excluding fmt.Fprint
/Users/dbarman/Work/Go/src/github.com/improbable-eng/thanos/pkg/objstore/objstore.go:235:3: cannot use b.opsDuration.WithLabelValues(op) (value of type github.com/prometheus/client_golang/prometheus.Observer) as github.com/prometheus/client_golang/prometheus.Histogram value in argument to newTimingReadCloser: missing method Collect
/Users/dbarman/Work/Go/src/github.com/improbable-eng/thanos/pkg/objstore/objstore.go:250:3: cannot use b.opsDuration.WithLabelValues(op) (value of type github.com/prometheus/client_golang/prometheus.Observer) as github.com/prometheus/client_golang/prometheus.Histogram value in argument to newTimingReadCloser: missing method Collect
/Users/dbarman/Work/Go/src/github.com/improbable-eng/thanos/pkg/store/cache.go:85:2: invalid operation: evicted.WithLabelValues(cacheTypePostings) (value of type github.com/prometheus/client_golang/prometheus.Counter) has no field or method Set
/Users/dbarman/Work/Go/src/github.com/improbable-eng/thanos/pkg/store/cache.go:86:2: invalid operation: evicted.WithLabelValues(cacheTypeSeries) (value of type github.com/prometheus/client_golang/prometheus.Counter) has no field or method Set
error: failed to check packages: could not type check: couldn't load packages due to errors: github.com/improbable-eng/thanos/pkg/store, github.com/improbable-eng/thanos/pkg/objstore
make: *** [errcheck] Error 2

</p>
</details>

**Anything else we need to know**

**Environment**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
Darwin dbarman-Mac 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

- Others:

**Comment by jojohappy** [comment]
I found that Prometheus/client_golang has been removed function `Set()` at `v0.9.0-pre1`. [#247](https://github.com/prometheus/client_golang/pull/247) to see the detail.  So you should make sure your Prometheus/client_golang version is `0.8.0`.

**Comment by Bplotka** [comment]
Interesting, will double check, Thanks for reporting

**Comment by dhbarman** [comment]
I could successfully build thanos. So, you may close the ticket.
