### ISSUE TITLE
Only reference for command line options is via calling the program with -h

### ISSUE THREAD

**Issue by paulcdejean** [improbable-eng/thanos#451]
For the sake of convenience you should automatically generate some docs as part of the build process, and have said docs online somewhere, perhaps https://readthedocs.org/ or similar?

As a workaround I just added http://termbin.com/vo5b and http://termbin.com/sz9e to my bookmarks bar. Ideally though I'd like to be able to google "thanos sidecar command line options" or similar and see a reference of some sort.

**Comment by paulcdejean** [comment]
This is also an issue that exists in prometheus, much to my chagrin...

**Comment by xjewer** [comment]
what's wrong with internal documentation? https://github.com/improbable-eng/thanos/tree/master/docs/components

Probably, we have to add the reference on the main README page 🤔

**Comment by paulcdejean** [comment]
First of all for some reason my stupid brain thought that the command line args weren't mentioned in https://github.com/improbable-eng/thanos/blob/master/docs/components/sidecar.md and etc.

Which is complete nonsense because I've definitely read over those files before, so I don't know why my brain was mixed up.

Second of all even though it's good that those thingies are mentioned there, it seems its maintained manually which is probably asking for trouble.

But yes linking those docs from the main README would not only help humans, but would also assist search engine indexing! Anyways I'm going to close this because the title is me being wrong and dumb and confused. Hope I didn't waste too much time.

**Comment by xjewer** [comment]
>Second of all even though it's good that those thingies are mentioned there, it seems its maintained manually which is probably asking for trouble.

CI will check, if you change flags, but haven't run `make docs`
https://github.com/improbable-eng/thanos/pull/441

>But yes linking those docs from the main README would not only help humans, but would also assist search engine indexing!

It works well actually:
![image](https://user-images.githubusercontent.com/922743/43427733-d76d5288-9452-11e8-8695-ae8e96efcd7e.png)
