### ISSUE TITLE
compact: Implement retention policy

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#458]
Initially, we were not focused on this area, because for our use case, GCS buckets seem cheap enough to store even couple of years data (see https://github.com/improbable-eng/thanos/blob/master/docs/design.md#cost). However, we are seeing plenty or user request to implement this for various reasons. E.g a limited number of objects for store (because of custom Ceph object store) or simply desire to limit old metrics.

Initially, we also thought that object lifecycle should be used for those operations just fine, however there are some blockers:
- Not all object storages have lifecycle object policies.
- You could have some races (since object store will most likely not kill whole block folder, just some files one by one, introducing errors here & there)
- Compaction makes it even more difficult as data that were produced in T-1y and with 1y retention might be deleted after 1y + couple of weeks, because compactor put compacted blocks as new "files" from object store perspective 
- Our biggest compacted blocks have 2 weeks, so you cannot ensure retention more fine-grained than this.

Acceptance criteria for this task:
- simple periodic job integrated into compactor that will delete blocks with their maxTime exceeding certain age. 
- should not conflict with compactor and downsampling stages
- should be configurable from flag

**Comment by treed** [comment]
I'm unsure if this is the correct issue for this related item, and trying various search terms hasn't shown me anything else, but:

Would this potentially include variable downsampling/retention?

Which is to say, a policy like:

Keep full resolution for 30 days
Keep 30s resolution for an additional 60 days
Keep 1m resolution for an additional 120 days
Keep 5m resolution forever

Which could help keep historical data around while dropping detail to reduce space usage for the lesser used data. The project I'm designing at the moment to do a full Prometheus/Thanos/Trickster setup will like use 10TB per instance for 90 days of retention, which is... a lot. It would be nice to keep more data, but at a significantly reduced level of detail.

Oh, which reminds me of another related item. It's possible this is already a thing but I haven't seen it mentioned anywhere.

If we have an HA pair going into object storage, will that keep all the data from both sides forever, or is it possible to pre-deduplicate to save space?

**Comment by Bplotka** [comment]
Yea all of this makes sense, I think the first idea (different retentions for different resolution) makes sense to be done & tracked within this ticket. The second one (deduplicate in place) we could add in a different issue to track this separately.

**Comment by Bplotka** [comment]
BTW contributions are welcome! We can help design and review this (:
