### ISSUE TITLE
Follow Prometheus Metrics Best Practices

### ISSUE THREAD

**Issue by jdfalk** [improbable-eng/thanos#463]
When I was attempting to look for all thanos statistics in prometheus I noticed several metrics like this:
store_
store_fqdn
sidecar_
sidecar_fqdn

According to the best practices the naming scheme should be thanos_store / thanos_sidecar and should not have the server name directly in the metric name but as a label. 
https://prometheus.io/docs/practices/naming/
https://prometheus.io/docs/practices/instrumentation/#things-to-watch-out-for

Asks:
1. All misnamed metrics are renamed to follow a common naming pattern of thanos_
2. Additional labels are generated to specify node name and component

I am happy to assist on this work if accepted.

**Comment by Bplotka** [comment]
Yes, of course we want to follow prometheus policy! (:  Please help if you have time to improve this. This might lead to improve dashboards as well
