### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by pulord** [improbable-eng/thanos#466]
**Thanos, Prometheus and Golang version used**
thanos version: master a7d1ef827d09
prometheus version: 2.3.2
golang version: 1.10

**What happened**
execute "make" fail

![image](https://user-images.githubusercontent.com/15811706/43747877-054b4e36-9a1f-11e8-9c70-8392a68973b4.png)

**What you expected to happen**
build success
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**
change to 0.1.0-rc.2
build success

**Comment by Bplotka** [comment]
https://github.com/improbable-eng/thanos/pull/460 should help you. 

I think you need to poke dep to actually do something. You can do it by doing changing gopkg.toml file in any form. (:  (add comment or space etc)

**Comment by Bplotka** [comment]
Should work now, let me know if you can repro
