### ISSUE TITLE
Securing gRPC?

### ISSUE THREAD

**Issue by tcolgate** [improbable-eng/thanos#468]
I can't see any information in the docs about providing TLS certs for the gRPC endpoints.
I'd like to use thanos across multiple kube cluster. Basically one thanos cluster per cluster, ad then a querier configured to query each storer from each cluster. This seems like a reasonably typical use case. From what I can see though I can't secure the gRPC endpoint of the storer so would need to do this via other means.

Are there plans to support securing the gRPC endpoints using a common CA among components?

**Comment by Bplotka** [comment]
Use case makes sense. Usually you can do it by puttin some nginx/envoy etc forward and reverse proxies, but I think for something that common as TLS certs we might want to accept the PR (:

**Comment by tcolgate** [comment]
@Bplotka I think I'd classify an additional proxy as "other means". If you are happy to take a PR, I'll try and put something together next week. (FWIW, "other means" isn't neccessarily a bad thing, it's just a bit of a pain).

**Comment by tcolgate** [comment]
I've not tested this yet but something like: 
https://github.com/improbable-eng/thanos/pull/508

**Comment by tcolgate** [comment]
Closed via https://github.com/improbable-eng/thanos/pull/508
(FYI, I'm actively running this in our staginng environment and all seems well)
