### ISSUE TITLE
Bucket Verify: Expose Error in Thanos Bucket Verify

### ISSUE THREAD

**Issue by jdfalk** [improbable-eng/thanos#473]
**Thanos, Prometheus and Golang version used**

thanos, version 0.1.0-rc.2 (branch: HEAD, revision: 8b7169b78f5b1cf76424cabb2e7586f7219ae11b)
  build user:       jenkins
  build date:       20180805-04:24:54
  go version:       go1.10.3

**What happened**
Running Thanos Bucket Verify does not expose the underlying errors.

**What you expected to happen**
It should display the error.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Run ```thanos bucket verify --s3.endpoint localhost:46214 --s3.bucket prometheus2 --s3.insecure  --s3-backup-bucket=promrepair --log.level=debug -i overlapped_blocks``` and give it incorrect credentials.

**Full logs to relevant components**

<details>Logs
<p>

level=warn ts=2018-08-09T18:58:31.81293109Z caller=verify.go:49 msg="GLOBAL COMPACTOR SHOULD __NOT__ BE RUNNING ON THE SAME BUCKET" issues=1 repair=false
level=info ts=2018-08-09T18:58:31.813047133Z caller=overlapped_blocks.go:25 msg="started verifying issue" with-repair=false issue=overlapped_blocks
level=info ts=2018-08-09T18:58:57.135784942Z caller=verify.go:68 msg="verify completed" issues=1 repair=false
level=info ts=2018-08-09T18:58:57.136004813Z caller=main.go:163 msg=exiting
</p>
</details>

**Comment by bwplotka** [comment]
Sorry for delayed answer and thanks for reporting. This makes sense, but it also seems to be trivial to fix (: 

Volounteers highly wanted (:

**Comment by jojohappy** [comment]
@bwplotka I guess this issue has been fixed, here is the logs with wrong credentials.
```
level=info ts=2018-09-28T10:02:41.5562604Z caller=factory.go:47 msg="loading bucket configuration file" filename=s3-bucket.yml
level=info ts=2018-09-28T10:02:41.5590955Z caller=factory.go:47 msg="loading bucket configuration file" filename=
level=warn ts=2018-09-28T10:02:41.5592003Z caller=verify.go:49 msg="GLOBAL COMPACTOR SHOULD __NOT__ BE RUNNING ON THE SAME BUCKET" issues=1 repair=false
level=info ts=2018-09-28T10:02:41.5592439Z caller=overlapped_blocks.go:25 msg="started verifying issue" with-repair=false issue=overlapped_blocks
bucket verify command failed: verify: overlapped_blocks: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by bwplotka** [comment]
Closing as while adding new way bucket configuration (files) this was most likely fixed.

if you can repro it @jdfalk, let us know!
