### ISSUE TITLE
query: prometheus.url not used for remote read

### ISSUE THREAD

**Issue by svanschie** [improbable-eng/thanos#478]
**Thanos, Prometheus and Golang version used**

<pre>
thanos --version
thanos, version 0.1.0-rc.2 (branch: master, revision: d068d53741b93e7b4be3f174fddacd44b786ca7d)
  build user:       root@thanos
  build date:       20180815-13:36:50
  go version:       go1.10
</pre>

**What happened**
I'm running Prometheus using a URL prefix (/prometheus/). Because of this I started sidecar with the following option: `--prometheus.url http://localhost:9090/prometheus`. This works fine for requests the sidecar process makes itself. However, the Thanos query process doesn't seem to use this option. It does use the correct domain and port, but the URL prefix seems to be ignored as I'm seeing POST requests to `/api/v1/read` when querying. 

The full HTTP Request headers for an example query are as follows (with the query as payload):

<pre>
POST /api/v1/read HTTP/1.1
Host: localhost:9090
User-Agent: Go-http-client/1.1
Content-Length: 80
Content-Encoding: snappy
Content-Type: application/x-protobuf
X-Prometheus-Remote-Read-Version: 0.1.0
Accept-Encoding: gzip
</pre>

**What you expected to happen**
The query process to fully use the prometheus.url value as provided by sidecar.

**How to reproduce it (as minimally and precisely as possible)**:
* Run Prometheus with a URL prefix: `--web.route-prefix=/prometheus/`
* Start sidecar pointing to the URL with the prefix: `--prometheus.url http://localhost:9090/prometheus`
* Send a query to the Thanos query process

**Full logs to relevant components**
The logs don't show anything relevant. When using the webinterface of the query process to execute a query the following message is shown:

<pre>
receive series: rpc error: code = Unknown desc = query Prometheus: request failed with code 404 Not Found
</pre>

This makes sense as Prometheus expects requests to /prometheus/*

Please let me know if you need anything else.

**Comment by Bplotka** [comment]
Thanks for reporting, makes sense

**Comment by svanschie** [comment]
First time Golang, luckily it was an easy fix
