### ISSUE TITLE
Add proposal to remove Gossip

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#484]
Additionally fix https://github.com/improbable-eng/thanos/blob/master/docs/getting_started.md#communication-between-components ASAP to stop confusion around which component should talk with which component.

**Comment by jdfalk** [comment]
Is there a planned replacement or will static addresses be the only option?

**Comment by Bplotka** [comment]
All will be covered by proposal (: 

TL;DR: File SD is planned as a replacement.

**Comment by TDabasinskas** [comment]
It would actually be nice to have support for DNS-based SD, so we could provide a single FQDN, e.g. `--store thanos.mycompany.org` (which can be under Consul, if needed), for the querier, which would resolve and use all the IP resolved under the DNS name. 🙂

**Comment by Bplotka** [comment]
Done.

**Comment by drax68** [comment]
Doesn't seems to be a well thought decision to remove autodiscovery for tool that supposed to be used in dynamic environments like aws with instances going up and down for whatever reason.

**Comment by bwplotka** [comment]
@drax68 did you have a chance to read the proposal? DNS discovery gives exactly the same dynamicity without massive overhead (and other disadvantage mentioned in document) of gossip protocol (: 

Let me know if any other functionality is missing.

**Comment by bwplotka** [comment]
Proposal completed.
