### ISSUE TITLE
Sidecar deleting data files used by Prometheus?

### ISSUE THREAD

**Issue by tgxworld** [improbable-eng/thanos#490]
**Thanos, Prometheus and Golang version used**

docker image: `improbable/thanos:master-2018-08-22-5cbcf0d`
Prometheus image: `prom/prometheus:v2.2.1`

**What happened**

Prometheus is failing to start with 

```
level=error ts=2018-08-27T09:08:49.358182359Z caller=main.go:582 err="Opening storage failed open block /prometheus/data-v3/01CNX9RYN8C08PTVEJET537BGZ: try lock file: open /prometheus/data-v3/01CNX9RYN8C08PTVEJET537BGZ/index: no such file or directory"
``` 
Looking inside the relevant folder, it looks like sidecar is involved? 

```
root@yyy:/prometheus-server/data-v3/01CNX9RYNMBV93D81GC7CYWC7M# ls
index.cache.json  meta.json
root@yyy:/prometheus-server/data-v3/01CNX9RYNMBV93D81GC7CYWC7M# cat meta.json
{
	"version": 1,
	"ulid": "01CNX9RYNMBV93D81GC7CYWC7M",
	"minTime": 1535349600000,
	"maxTime": 1535356800000,
	"stats": {
		"numSamples": 31665025,
		"numSeries": 83662,
		"numChunks": 238869
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01CNX9RYNMBV93D81GC7CYWC7M"
		]
	},
	"thanos": {
		"labels": {
			"datacenter": "<censored>",
			"server": "<censored>"
		},
		"downsample": {
			"resolution": 0
		},
		"source": "sidecar"
	}
}
```

**What you expected to happen**

Not sure about this but is sidecar supposed to create/alter those folders causing Prometheus to fail to start? The relevant `chunks` and `index` files that prometheus is looking for are stored properly in the bucket though.

**Full logs to relevant components**

#### Sidecar

```
level=info ts=2018-08-27T08:37:04.94693281Z caller=sidecar.go:270 msg="starting sidecar" peer=
level=info ts=2018-08-27T08:37:04.947040401Z caller=sidecar.go:215 component=sidecar msg="Listening for StoreAPI gRPC" address=[::]:19091
level=info ts=2018-08-27T08:37:04.947098522Z caller=main.go:243 msg="Listening for metrics" address=[::]:19191
level=info ts=2018-08-27T08:40:05.124748841Z caller=reloader.go:189 component=reloader msg="Prometheus reload triggered" cfg_in= cfg_out= rule_dirs=
level=info ts=2018-08-27T09:00:05.407205366Z caller=shipper.go:201 msg="upload new block" id=01CNX9RYN8C08PTVEJET537BGZ
```

**Comment by Bplotka** [comment]
It looks like... you accidently connected StoreGateway working dir in the same `tsdb.path` as Prometheus ^^ Store Gateway is the only component which produces `index.cache.json`... (: Is that the case?

**Comment by tgxworld** [comment]
O that was it. I guessed I got confused by the flag [`--tsdb.path="./data"      Data directory of TSDB.`](https://github.com/improbable-eng/thanos/blob/master/docs/components/store.md) which seems to have an incorrect description. 

Thank you so much @Bplotka :+1:

**Comment by Bplotka** [comment]
Yes! Flag is confusing. Feel free to put PR to fix the naming of this flag (: 

Glad we found the cause.
