### ISSUE TITLE
Add File Service Discovery 

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#492]
**Rationales**
Similarly to Prometheus [File SD](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cfile_sd_config%3E) our idea for File SD will allow to update hosts for various purposes (StoreAPIs for Querier, Queriers for Ruler) to be discovered on runtime. Additionally it will allow to build custom integrations that will fill those in run time.

Iinitially I thought we could just use [Prometheus package](https://github.com/prometheus/prometheus/blob/master/discovery/file/file.go#L172) but it is quite tied to targets, so no longer sure. Sticking to same library will really help us to not maintain it and have proven solution that works with __ANY__ integration that is already build into that. We should consider this.

**Acceptance Criteria**
* Agree if we want to reuse (and hack) same [package](https://github.com/prometheus/prometheus/blob/master/discovery/file/file.go#L172) or copy some code for something similar.
* Define if we support one file or more? [Prometheus format](https://github.com/prometheus/prometheus/blob/release-2.3/config/testdata/conf.good.yml#L42)
* Define file format. Should it be same [as Prometheus one](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cfile_sd_config%3E)? (which will allow reusing similar sidecars/projects like [this](https://github.com/ContainerSolutions/prometheus-swarm-discovery))
* Add working File Service Discovery (SD) with tests.
  * A way to dynamically specify FQDN, hosts, IPs and ports that will be resolved to IPs.
    * Support SRV
    * Support periodic resolution refresh (we can reuse Prom code:  https://github.com/prometheus/prometheus/blob/master/discovery/dns/dns.go#L167)
  * Reuse or even __USE__ runtime reload logic from Prometheus (https://github.com/prometheus/prometheus/blob/master/discovery/file/file.go#L172)
  * Hook it in:
    * Thanos Querier (for StoreAPIs)
    * Thanos Ruler (to discover Querier) 
  * Document usage.
  * Add solid unit tests to confirm usability.

**Comment by Bplotka** [comment]
This is related to https://github.com/improbable-eng/thanos/issues/484

(in fact we want to combine DNS SD as well here)

**Comment by Bplotka** [comment]
We need to also make sure this is https://github.com/improbable-eng/thanos/issues/452 within the scope.

**Comment by yuecong** [comment]
could we also support https as [prometheus's tls_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Ctls_config%3E) and basic_auth? With these, I think we can even config thanos cluster discovery over the internet.

**Comment by xjewer** [comment]
>We need to also make sure this is #452 within the scope.
removing gossip/memberlist solves this problem, as it's all about memberlist's resolver

**Comment by xjewer** [comment]
>so still it would be nice to remember about /etc/hosts (:

@Bplotka  afaik, the golang unix resolver lookup `Resolver.LookupHost` respects a [/etc/nsswitch.conf file](http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html) and an order of lookup accordingly

**Comment by Ehekatl** [comment]
DNS based sd would be more than enough, I'm using headless service to publish thanos peer endpoint within k8s, even without k8s, manage several dns records by hand is not much of work.

It would be better if you make `--cluster.peers=` compatible with dns sd,
so my configuration`--cluster.peers=peers.thanos.svc.cluster.local` works the same after remove gossip.

**Comment by xjewer** [comment]
Is anyone who works on this issue or has plan doing it?

**Comment by ivan-valkov** [comment]
Hey, I am working on file sd right now. I am working on getting a basic version of file sd running without dns resolution. When this is done, I plan on implementing a dns resolver that can be used in the file service discovery.

**Comment by bwplotka** [comment]
This was being merged! :tada: 

Thanks @ivan-valkov for this!
