### ISSUE TITLE
Clarification on storage buckets

### ISSUE THREAD

**Issue by tcolgate** [improbable-eng/thanos#521]
We have multiple kubernetes clusters accross various cloud providers. Including multiple clusters within individual GCS projects.

On our new configuration we will have one prometheus install per cluster (this install may include multiple prom instances for sharding).

I'm intending to have a single thanos-query with static store configs to query each store. 

Now, ideally I'd have each store write to a GCS  / AWS bucket that is local to the cluster

My question is, should each store have it's own GCS/AWS bucket? or is it OK for two stores in the same GCS project (but different cluters), to share buckets? Would I need one compactor per bucket?

**Comment by Bplotka** [comment]
> I'd have each store write to a GCS / AWS bucket that is local to the cluster

Well, store gateway does not write - it only browse, but maybe you mean Store API -> sidecar here?

Anyway, buckets can be treated totally orthogonal to AWS/GCP projects and clusters you have. It's up to you how you aggegate those. You can have bucket per cluster, you can have huge bucket globally. It all depends how powerful your object storage provider is, does it support multi-regional buckets, how access looks like, what's the latency, how big individual buckets can be etc... And yes, currently Store Gateway and Compactor supports only single bucket, so having less of them is easier to operate.

**Comment by tcolgate** [comment]
@bwplotka, thanks. From a deployment aspect, it will be easiest for me to have each a compactor and gateway per-cluster, then one query-api  to fan out queries to those. I'm starting to think that might not work with the rule node though?
  Essentially I have a bunch of clusters that aren't going to be able to gossip, but would prefer to have a single place to query. We've been standard federation (only scraping aggregates, longer retention), until now but am look to replace that with thanos.

**Comment by tcolgate** [comment]
Some further reflection, I think out primary use for the rules component is for alerts we have that will be greater than the rentention period of the prometheus instance. As such, and since I was intending to deploy a query node inside each cluster (just for convenience really), I think I can potentially deploy the rule component in each cluster too.
