### ISSUE TITLE
store/s3: add possibility to get more information about the requests/responses

### ISSUE THREAD

**Issue by GiedriusS** [improbable-eng/thanos#530]
It would be useful to be able to look at the requests themselves made by Thanos Store easily. `minio-go` supports a method called `TraceOn`: https://github.com/minio/minio-go/blob/master/api.go#L347. If that is called on a client then each request and response is logged to a `io.Writer`. Perhaps this could be added behind a separate flag something like `--s3.traceon`. It could optionally take a string argument - a file where such logs would be written. Obviously, one can look at the requests made by Thanos Store by using external tools such as `tcpdump` or `strace` but IMHO it would be useful to have such functionality baked in Thanos Store to make it easier to debug problems.

**Comment by bwplotka** [comment]
With the new objstore.config, you are more than welcome to add this option (: :+1: or anyone else can do it.

**Comment by GiedriusS** [comment]
Actually, `c.TraceOn()` makes it print each request and response. It would have a lot of unnecessary information. Instead, maybe we should improve `minio-go` to only print those things when the request had gotten a response which is not 2xx. Without that, there would be way too much noise and this feature in general would not be useful.

**Comment by bwplotka** [comment]
Well, it might be ok to put it under feature flag, so you can start your component with this super verbose option only temporary while debugging. (:

**Comment by szalai1** [comment]
@GiedriusS hi did you start working on this? if not I am happy to do it. let me know

**Comment by szalai1** [comment]
or/and @bwplotka Do you know anybody who started working on this ?

**Comment by bwplotka** [comment]
Not aware of any, so go for it!

**Comment by GiedriusS** [comment]
Thank you a lot for your work on this, @szalai1! Closing as this exists now in form of `trace.enable: true`.
