### ISSUE TITLE
compaction do not work with s3

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [improbable-eng/thanos#541]
**Thanos, Prometheus and Golang version used**

docker improbable/thanos:master-2018-09-21-1e1f9e5

**What happened**
Run compaction to downsample long retention s3 storage but there is now new block are created, and all operation took only few seconds it more looks like it do not try to do anything with the existing blocks that has size near 6GB
**What you expected to happen**
I expected that compaction create new blocks with downsampled data to query
**How to reproduce it (as minimally and precisely as possible)**:
not sure i just use docs from the github, maybe i miss something 
**Full logs to relevant components**
```
/ # thanos compact --objstore.config-file=/creds/s3-config --http-address="" --log.level=debug
level=info ts=2018-09-27T19:35:49.170523334Z caller=factory.go:47 msg="loading bucket configuration file" filename=/creds/s3-config
level=info ts=2018-09-27T19:35:49.171236275Z caller=compact.go:223 msg="starting compact node"
level=info ts=2018-09-27T19:35:49.171514704Z caller=compact.go:811 msg="start sync of metas"
level=info ts=2018-09-27T19:35:49.171585369Z caller=main.go:292 msg="Listening for metrics" address=
level=debug ts=2018-09-27T19:35:49.390452488Z caller=compact.go:174 msg="download meta" block=01CRDHPRJJ2EM8GKAYQ3PM3MEC
level=debug ts=2018-09-27T19:35:49.439990558Z caller=compact.go:174 msg="download meta" block=01CRDHTP7BY4Z4GCZY68S7A4GQ
level=debug ts=2018-09-27T19:35:49.470718626Z caller=compact.go:174 msg="download meta" block=01CRDRKP9AWZKNQB4CNVAKR3H5
level=debug ts=2018-09-27T19:35:49.502677747Z caller=compact.go:174 msg="download meta" block=01CRDRPDDKKGR3MKX93KPTS78G
level=debug ts=2018-09-27T19:35:49.540440283Z caller=compact.go:174 msg="download meta" block=01CRDZEG4NT340RQQ6GJ9P06JJ
level=debug ts=2018-09-27T19:35:49.560644244Z caller=compact.go:174 msg="download meta" block=01CRDZJ4NDTZ4XB8C8WKRT0N3K
level=debug ts=2018-09-27T19:35:49.587291398Z caller=compact.go:174 msg="download meta" block=01CRE6C1Z7ZPHF7350QGQF06VE
level=debug ts=2018-09-27T19:35:49.618160311Z caller=compact.go:174 msg="download meta" block=01CRE6DVXC0ZMHA5W87948BJCH
level=info ts=2018-09-27T19:35:49.65045978Z caller=compact.go:817 msg="start of GC"
level=info ts=2018-09-27T19:35:49.658204413Z caller=compact.go:149 msg="compaction iterations done"
level=info ts=2018-09-27T19:35:49.658279946Z caller=compact.go:156 msg="start first pass of downsampling"
level=info ts=2018-09-27T19:35:49.835052424Z caller=compact.go:162 msg="start second pass of downsampling"
level=info ts=2018-09-27T19:35:50.015181588Z caller=compact.go:167 msg="downsampling iterations done"
level=info ts=2018-09-27T19:35:50.015307227Z caller=retention.go:17 msg="start optional retention"
level=info ts=2018-09-27T19:35:50.201559202Z caller=retention.go:46 msg="optional retention apply done"
level=info ts=2018-09-27T19:35:50.202410485Z caller=main.go:168 msg=exiting
```

**Anything else we need to know**

Uncomment and fill if you use not casual environment or if it might be relevant.

**Environment**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:
Version of prometheus with sidecar is 2.3.1

**Comment by bwplotka** [comment]
Sure, it will not compact anything if there is nothing to compact. It needs at least 3 source blocks of smaller compaction level, so it will take time.

Downsampling hits in only after longer time as well, as there is no need to downsample fresh data.
Let me know if I am missing something here I will reopen - otherwise, it it expected.

**Comment by dmitriy-lukyanchikov** [comment]
@bwplotka  thank you very much for answer i alredy see that it start to work. So i have only one more question, is there any information how downsampling trigger, i mean dows it will start only for data only than 1 day or something similar. And if there is a way i can configure what data i need to downsample, for example, i need to downsample all that older than 1 week

**Comment by dmitriy-lukyanchikov** [comment]
@bwplotka Update looks like i found what will trigger downsampling, need to wait https://github.com/improbable-eng/thanos/blob/984f42ea00f1e62d599709382408e6c1861212b2/cmd/thanos/downsample.go#L169
for 5 minutes downsampling
and 
https://github.com/improbable-eng/thanos/blob/984f42ea00f1e62d599709382408e6c1861212b2/cmd/thanos/downsample.go#L190
for 1h downsampling

Does it possible to make this parameters configurable?
Dows it possible to configure downsampling resolution, for example not 5 minutes but 10 minutes.

Also notice one thing, if retention for row data is configured less than downsampling start to work it will delete all raw data before it will be downsampled, but maybe i miss some other parameter
