### ISSUE TITLE
downsample question

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [improbable-eng/thanos#545]
I have questions is there are any docs about how can downsamlping configured if there is a way, and  if not if there is possibility to implement new flags that will configure downsampling resolution and time when it will start to create downsample copies of data. Here what i found n the code for now
Looks like need to wait https://github.com/improbable-eng/thanos/blob/984f42ea00f1e62d599709382408e6c1861212b2/cmd/thanos/downsample.go#L169
for 5 minutes downsampling
and 
https://github.com/improbable-eng/thanos/blob/984f42ea00f1e62d599709382408e6c1861212b2/cmd/thanos/downsample.go#L190
for 1h downsampling

Does it possible to make this parameters configurable?
Dows it possible to configure downsampling resolution, for example not 5 minutes but 10 minutes.

Also notice one thing, if retention for row data is configured less than downsampling start to work it will delete all raw data before it will be downsampled, but maybe i miss some other parameter

**Comment by bwplotka** [comment]
It is not possible, currently. What's the use case for changing those? They should be generally correct. 

> Also notice one thing, if retention for row data is configured less than downsampling start to work it will delete all raw data before it will be downsampled, but maybe i miss some other parameter

Yup, but this is intented. (: There is no need to downsample if there is not enough retention.

**Comment by bwplotka** [comment]
yes. Otherwise there is no much of benefit in downsampling
