### ISSUE TITLE
Some metrics not uploaded to S3 bucket.

### ISSUE THREAD

**Issue by robvalca** [improbable-eng/thanos#565]
**Thanos, Prometheus and Golang version used**

thanos, version 0.1.0 (branch: HEAD, revision: ebb58c23a786b2ba714ff07b1795efea7ef37132)
  build user:       root@393679b8c49c
  build date:       20180918-17:02:30
  go version:       go1.10.3
Prometheus: 2.4.2
Backend: S3 (RadosGW + ceph)

**What happened**

Not sure if this is a bug or a misconfiguration. If I remember correctly when you run the sidecar for the first time, it uploads all the metrics currently stored in local prometheus data folder. Although, I've just added a new thanos installation on our current prometheus server and only some of them were uploaded.

Here is the content local prometheus folder:

drwxr-xr-x. 3 prometheus prometheus  68 Sep 12 10:03 01CQ6CX1XCMJBCX320E1JXV4F2
drwxr-xr-x. 3 prometheus prometheus  68 Sep 25 23:04 01CR98K5Z6PXNZWAQBA6Y3E3VE
drwxr-xr-x. 3 prometheus prometheus  68 Oct  2 17:01 01CRTMQ58BRE5D6Y87RJYDA3E2
drwxr-xr-x. 3 prometheus prometheus  68 Oct  9 11:01 01CSC0WZVGGJZ8AQR23GNMB52Y
drwxr-xr-x. 3 prometheus prometheus  68 Oct 10 05:00 01CSDYNSJ0AGFNCD444G5HXBVX
drwxr-xr-x. 3 prometheus prometheus  68 Oct 10 11:00 01CSEK8V22W51W1RR8RMQCTK1Y
drwxr-xr-x. 3 prometheus prometheus  68 Oct 10 17:00 01CSF7VS0MKYSCTWW5XZ5ZH64X
drwxr-xr-x. 3 prometheus prometheus  68 Oct 10 17:00 01CSF7W076R8NBZPB2V3JD7E93

But only the following dirs were uploaded in the S3 bucket:

01CSEK8KXBYGV0A01WKZQ9XMS9
01CSET4B5BJA512MNM801PNAJ4
01CSF102DBXDQDAS77YJ4N02EG
01CSF7VS0MKYSCTWW5XZ5ZH64X

Interestingly, the content of `thanos.shipper.json` is like this:

{
	"version": 1,
	"uploaded": [
		"01CQ6CX1XCMJBCX320E1JXV4F2",
		"01CR98K5Z6PXNZWAQBA6Y3E3VE",
		"01CRTMQ58BRE5D6Y87RJYDA3E2",
		"01CSC0WZVGGJZ8AQR23GNMB52Y",
		"01CSDYNSJ0AGFNCD444G5HXBVX",
		"01CSEK8V22W51W1RR8RMQCTK1Y",
		"01CSF7VS0MKYSCTWW5XZ5ZH64X",
		"01CSF7W076R8NBZPB2V3JD7E93"
	]
}

The local retention is set to 365d, I've though that maybe this was the problem and tried with 30d, 25d but the older metrics were not uploaded. I see no errors on thanos-sidecar and the new metrics  are uploaded correctly.

How I can upload the old metrics?

Thank you a lot!

**Comment by bwplotka** [comment]
> Not sure if this is a bug or a misconfiguration. If I remember correctly when you run the sidecar for the first time, it uploads all the metrics currently stored in local prometheus data folder. Although, I've just added a new thanos installation on our current prometheus server and only some of them were uploaded.

This is not the case, see this: https://github.com/improbable-eng/thanos/issues/348

Only new metrics will be uploaded. There is no safe way to upload old already compacted ones.

**Comment by robvalca** [comment]
Thanks Bartek and sorry for the noise :)
