### ISSUE TITLE
How to correctly configure thanos compact to rotate data stored in object storage.

### ISSUE THREAD

**Issue by Alexvianet** [improbable-eng/thanos#573]
I got a question.
I want to store data in object storage for 3month ( no needed more)  

our Prometheus configuration:
      prometheus:
        storage:
          tsdb:
            retention: 170h

How should i configure thanos compact:
      --retention.resolution-raw=0d  
      --retention.resolution-5m=0d  
      --retention.resolution-1h=0d  
to make it work effectively?

thanos and Prometheus latest versions

**Comment by bwplotka** [comment]
> I want to store data in object storage for 3month ( no needed more)

I would suggest just setting to 3 months:
```
--retention.resolution-raw=90d
--retention.resolution-5m=90d
--retention.resolution-1h=90d
```
Regarding your configuration:
```
Prometheus configuration:
prometheus:
storage:
tsdb:
retention: 170h
```
If you use object store, your Prometheus retention should minimal like 12h or 24h and local compaction disabled.

**Comment by Alexvianet** [comment]
to disabled local compaction in prometheus:
--storage.tsdb.max-block-duration=0d
--storage.tsdb.min-block-duration=0d

needed ?

**Comment by Alexvianet** [comment]
have found thanks
The --storage.tsdb.min-block-duration and --storage.tsdb.max-block-duration must be set to equal values to disable local compaction. The default of 2h is recommended.
