### ISSUE TITLE
Cleaning up dataDir breaks backwards comparability.

### ISSUE THREAD

**Issue by domgreen** [improbable-eng/thanos#580]
Cleaning up dataDir from #571 breaks backwards comparability.

https://github.com/improbable-eng/thanos/pull/571#issuecomment-430632467

```
compact command failed: clean working temporary directory: remove /var/thanos/data: device or resource busy
```

I use data-dir the same as the mount path of volume in k8s, hence dir couldn't be deleted.
The workaround is to set data-dir as nested dir. I.e. in my case this's: /var/thanos/data/compact

**Comment by jojohappy** [comment]
Sorry, my bad... I also meet the problem when it is integrated in Kubernetes today. 

So could we clean up the subpath directories such as `compact` and `downsample` instead of the temporary directory itself?

**Comment by dmitriy-lukyanchikov** [comment]
i meet this problem too, when add hostpath as volume in kubernetes
