### ISSUE TITLE
Compaction and Downsample potentially loose data with retention

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [improbable-eng/thanos#585]
**Thanos, Prometheus and Golang version used**

```
thanos, version 0.1.0 (branch: master, revision: a09d41dd6534f28365eede43fd024fed3dcc0750)
  build user:       circleci@c3a93aad0498
  build date:       20181011-11:17:20
  go version:       go1.10.4
```
**What happened**
I run thanos with s3 storage for 11 days and today i notice some strange behavior. 5minutes downsampled blocks are created every 2 days, and there is 4 5minutes downsampled blocks with data for first 8 days, but today i notice that 5minutes blocks not created for last 3 days instead there is huge block with all data for almost 10 days and it downsampled and store near with block that already have 2 first days downsampled. I think keeping the same metrics twice its not good if you have 30Gb of metrics for just 1 day.
Also notice that this huge block do not have metrics for 10 days, and its not started second downsampled iteration and already have compaction 4 level so it will not be downsampled further. So we have two problems here:

1) compaction not properly working for downsampled blocks, there is possibility to double information for some period of time, and in this way downsample will not decrease number of information that need to query during long period of time, but maybe i miss something maybe this will be handled by compactor later, i just want to make sure that its correct behaviour.
2) And problem when some blocks for downsampled data are not created at all for example maximum compaction 4 and block is still less than 10 days and second downsample iteration are not triggered on this block. Then if you have retention for raw blocks and 5minutes data blocks blocks will be deleted in time, but if 1h blocks are not created for some data there is possibility to loose some of metrics. Maybe i misunderstood, please correct me if i am wrong here.

**Comment by bwplotka** [comment]
What is your retention configuration for compactor?

This seems to be valid bug as different retention levels for different downsampling levels are experimental. However the retention seems to be quite low. IMO there is not that much of advantage of having retention set to less than couple of months, because that many data you can just store locally on Prometheuses (with some persistent disk)

**Comment by dmitriy-lukyanchikov** [comment]
Hello, thank you for help, here is configuretion of retention policy for thanos compactor component
```
--retention.resolution-raw=21d
--retention.resolution-5m=30d
--retention.resolution-1h=3y
```

We setthis retention and start to sue thanos because we have too many metrics to store it locally and store it more than 3 weeks raw data. We have near 9 Millions series and need to store it all for at least 1 year, better 3 years. But for 2 weeks of using thanos already have 900Gb of data. To store it locally for couple of months in prometheus we need at least 512 GB of RAM just to start prometheus.
I will try to investigate can we improve the code to fix retention for different resolution. I have an idea maybe we can change compaction behaviour to compact only if we have needed number of blocks with previous compaction level to create new, does it make sense to you?

**Comment by bwplotka** [comment]
> I have an idea maybe we can change compaction behaviour to compact only if we have needed number of blocks with previous compaction level to create new

Well, this what is happenning right now (: Have you expierience something opposite?

You have 9 million series from one source? (One prometheus?)

**Comment by dmitriy-lukyanchikov** [comment]
> > I have an idea maybe we can change compaction behaviour to compact only if we have needed number of blocks with previous compaction level to create new
> 
> Well, this what is happenning right now (: Have you expierience something opposite?

Hm strange, because i see that blocks with compaction level 4 have less than 10 days interval after compaction, so looks like 1h downsampling will not trigger for them(if i not mistaken), not sure how its happened, actually this is my main concern) because having so much data for more than 1 month is too expensive and hard to query. Maybe i miss something in configuration, or maybe i have some race condition not sure yet. Will be glad if you can point me for solution.


> You have 9 million series from one source? (One prometheus?)

For now its 4 different Prometheus for different type of metrics in our infrastructure, so if we merge it together it will be near 9 millions for now, but we are growing and its only start :)

**Comment by bwplotka** [comment]
We are aware that this part related to downsampling might be confusing. Created ticket with some answers you might want and to track this further: #813 Let's move the discussion there.
