### ISSUE TITLE
Standardise YAML Casing - S3 Config Update

### ISSUE THREAD

**Issue by domgreen** [improbable-eng/thanos#596]
We currently support a number of YAML casing in the config files ... we have `kebab-case` in the `s3` yaml config and `snake_case` in the config for service discovery.

We should update the s3 object store to be `snake_case` and standardise on this casing.

**Comment by bwplotka** [comment]
Thanks for issue. S3 part is done:
- https://github.com/improbable-eng/thanos/pull/597

**Comment by FUSAKLA** [comment]
Is there anything left to be done? 
Looking at the configs all looks to be `snake_case` now otherwise I'd be happy to help.

**Comment by bwplotka** [comment]
This is done AFAIK (:
