### ISSUE TITLE
grafana do not read downsampled thanos blocks 

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [improbable-eng/thanos#601]
Hello guys. 

I create downsampled 5m and 1h blocks and my grafana cannot read it, it reads only raw data from Thanos may be i miss something in configuration please help

**Comment by bwplotka** [comment]
Why it was closed? (: 

I guess you found option for `--query.auto-downsampling` in Thanos Querier?

**Comment by dmitriy-lukyanchikov** [comment]
Hello, yes i think this option need some additional explaining because its was not clear when i read description first time

**Comment by itarch** [comment]
So what is the secret to get grafana showing data older than "raw data" ?

What I understand is, Grafana (Version 5.3) sits on top of Thanos Query Instance. However when I jump to Thanos Query Instance (http:/x.x.x:19191) I see the whole range of existing (raw + downsampled) data.

**Comment by bwplotka** [comment]
You can set Querier with `--query.auto-downsampling` on or off. This controls the default behaviour when no param is set on HTTP request (Which is the case when you use grafana)
