### ISSUE TITLE
Question: Add a path to a bucket yaml

### ISSUE THREAD

**Issue by doodle-tnw** [improbable-eng/thanos#618]
We have multiple prometheus instances across a few namespaces and gcp clusters - Is it possible to get them all to write to the same bucket? Is it possible to get them to write to different directories or paths into the bucket?

**Comment by bwplotka** [comment]
> We have multiple prometheus instances across a few namespaces and gcp clusters - Is it possible to get them all to write to the same bucket?

Yes. All prometheuses should have unique external labels, and then all can get into same bucket.

> Is it possible to get them to write to different directories or paths into the bucket?

Currently not. What that would give you, what problems you want to solve?

**Comment by doodle-tnw** [comment]
Ah that's brilliant, we will place in one bucket 

And the base path was so we could segregate customer data without having to create loads of buckets - it's not a massive priority to us because it's monitoring data, just curious if it was possible
