### ISSUE TITLE
Add option to disable partial response for Thanos Querier.

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#622]
We need to have partial error opt-out if needed for reliable alerting using thanos ruler.

Acceptance criteria:
* Way to disable partial response logic for thanos querier based on some QueryAPI negotiation (e.g headers?)
  * When partial response option is off, we have to error out immdiately.

**Comment by bwplotka** [comment]
The problem is with queries like `sum(failures_percentage) > xx ` that aggregates data from all clusters. With partial response turn on, you can get mislead, becuase some cluster might not be summed into result.

**Comment by tdabasinskas** [comment]
Yeah, that would be nice, as I believe we faced issues due to this when trying to use [Trickster](https://github.com/Comcast/trickster), as it cached data is incorrect, if Thanos Query returned only partial result, which got cached.

**Comment by bwplotka** [comment]
@tdabasinskas this means that would you rather have option to turn partial response completely on Thanos querier?

**Comment by tdabasinskas** [comment]
Yes, I think having that option might be good.
