### ISSUE TITLE
[Feature] Add ALERTS metrics to Thanos-ruler

### ISSUE THREAD

**Issue by zenman94** [improbable-eng/thanos#630]
Dear All,

In a standard Prometheus deployment we use the _ALERTS_ metrics to make some treatments.
We implement the excellent Thanos project in our monitoring infrastructure but we don't find this metric now.

Is it possible to create and expose this metric like Prometheus does?

Regards

**Comment by bwplotka** [comment]
Yes! We need to figure out how to do it, but yes ;p

**Comment by GiedriusS** [comment]
This has been implemented some time ago now: https://github.com/improbable-eng/thanos/blob/05f81a52802ae93f63c6c811e1edfaf3300cb472/test/e2e/rule_test.go#L107 so I am closing this. Please shout at me if I'm wrong :smile:

**Comment by WesternStar** [comment]
For other people like me who search and find this issue. The way you query for these metrics is through the store api. If you hook ruler up to query's store api you will be able to see these metrics.
