### ISSUE TITLE
Query has been running for a long time and the query has no data and can only be valid if restarted

### ISSUE THREAD

**Issue by gecailong** [improbable-eng/thanos#640]
thanos version:0.1.0-rc.2
prometheus version:version 2.3.1

When the problem occurs：
The following error occurs in query, thanos interface query becomes slow. An error occurred while waiting for a period of time to timeout. Error message: Error executing the query: Internal Server Error, I have to restart the query to solve query information. This scenario seems to have happened after I set Prometheus after several Prometheus sets were set together.

thanos query error：
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.4086949Z caller=proxy.go:117 err="fetch series for [{monitor qtt-thanos-prometheus03}]: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408777657Z caller=proxy.go:117 err="fetch series for [{monitor qtt-thanos-elasticsearch}]: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408804068Z caller=proxy.go:117 err="fetch series for []: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408829482Z caller=proxy.go:117 err="fetch series for [{monitor qtt-thanos-prometheus01}]: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408853465Z caller=proxy.go:117 err="fetch series for [{monitor qtt-thanos-rec}]: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408884764Z caller=proxy.go:117 err="fetch series for [{monitor qtt-thanos-prometheus-db}]: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408908438Z caller=proxy.go:117 err="fetch series for []: rpc error: code = Canceled desc = context canceled"
Nov 23 10:36:22 bje-qtt-public-queryer-03 thanos[14911]: level=error ts=2018-11-23T02:36:22.408881809Z caller=proxy.go:117 err="fetch series for [{monitor thanos-prometheus-others}]: rpc error: code = Canceled desc = context canceled"

problem：
Now this is causing me trouble, which happens on an irregular basis. The query cannot be queried without a restart. I want to know what causes this, because this is placed in the production environment and urgently needs to be solved

**Comment by bwplotka** [comment]
Hello! (: 

I feel like we need more info, like metrics from thanos querier and logs, metrics from StoreAPI you uses underneath. 

The `thanos query error：` you provided suggests that client cancelled  the request due to either user cancel or client timeout. 

> This scenario seems to have happened after I set Prometheus after several Prometheus sets were set together.
Can you elaborate? What do you mean `Prometheus sets`?

**Comment by bwplotka** [comment]
Yup, we need more info. Worth to grab `grpc` histogram metrics to check the latencies on underlying storeapis. 

Also the version is pretty old, for example you might be hitting this (https://github.com/improbable-eng/thanos/pull/563  - however rather unlikely).  I would use master one: `master-2018-11-23-f26bc09` to be up to date.

**Comment by GiedriusS** [comment]
Closing this because it has been inactive for quite some time to keep everything clean. Please shout at me if this is still a problem in the newest version 😄
