### ISSUE TITLE
trigger reload: received non-200 response: 403 Forbidden?? how to resolve this error

### ISSUE THREAD

**Issue by deep7710** [improbable-eng/thanos#643]
**Thanos, Prometheus and Golang version used**

**What happened**

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by bwplotka** [comment]
You need `--web.enable-lifecycle`.

I updated docs and error here: https://github.com/improbable-eng/thanos/pull/645
