### ISSUE TITLE
query: metadata endpoint `/api/v1/label/<label_name>/values` should return external labels

### ISSUE THREAD

**Issue by FUSAKLA** [improbable-eng/thanos#649]
The metadata endpoint of Thanos Query `/api/v1/label/<label_name>/values` should return all values of the specified label name. (see [Prometheus docs](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values)).

This works for all labels but not for the labels specified added by the `external_labels` of Thanos Store instances.

This is used for example by Grafana in `label_values(<label_name>)` which can be used to load lavel values to query variable see http://docs.grafana.org/features/datasources/prometheus/#query-variable.

**Comment by bwplotka** [comment]
Thanks, valid issue, PRs welcome (:

**Comment by bwplotka** [comment]
The actual work to be done, is to glue external labels from blocks in store Gateway.
