### ISSUE TITLE
HTTP related memory leak in store nodes

### ISSUE THREAD

**Issue by fabxc** [improbable-eng/thanos#66]
The store node is leaking memory very heavily. For the high request frequency I currently have, each query bumps the resident memory by 200-500MB.

The memory seems to go somewhere in `net/http` but is neither reused nor freed. From the heap profile I cannot tell whether it comes from our own gRPC or from requests to GCS.
We are not opening connections ourselves for either but only instantiate a constant number of clients. So possibly it's something we have to change in how we configure those.

**Comment by Bplotka** [comment]
Fixed, right?

**Comment by fabxc** [comment]
Most likely, yes.
