### ISSUE TITLE
Built docker image cannot run

### ISSUE THREAD

**Issue by shangjin92** [improbable-eng/thanos#667]
**Thanos, Prometheus and Golang version used**
Thanos: 0.1.0
Golang: 1.10.3
docker: 18.09.0

**What happened**
I pull the newest code of thanos. Then I run make command, and it successfully got the output of thanos. The executable file can be run normally.
```
./thanos 
usage: thanos [<flags>] <command> [<args> ...]

A block storage based long-term storage for Prometheus

Flags:
  -h, --help               Show context-sensitive help (also try --help-long and --help-man).
```
```
./thanos store
level=info ts=2018-12-09T14:53:35.647432745Z caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=192.168.0.142:10901
level=info ts=2018-12-09T14:53:35.659098796Z caller=factory.go:41 msg="loading bucket configuration"
store command failed: create bucket client: not found bucket
```

Then I run 'make docker', the docker image has built successfully. But the built image cannot be run anyway, it reported 'exec format error' like below.
```
docker run -it improbable/thanos:latest -- store

standard_init_linux.go:190: exec user process caused "exec format error"
```
Then I change Dockerfile like this.
```
FROM quay.io/prometheus/busybox:latest
LABEL maintainer="The Thanos Authors"

COPY thanos /bin/thanos

ENTRYPOINT [ "" ]
```
I tried again, it reported error still.
```bash
docker run -it improbable/thanos:latest -- /bin/thanos

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--\": executable file not found in $PATH": unknown.
```
I tried the existed image(https://hub.docker.com/r/improbable/thanos/tags/), it will run successfully. 

I have tried to run 'docker build' in MacOS or Linux, but it still cannot run still. I wander why it cannot run after I run 'docker build'.

**What you expected to happen**
I want to run the built docker image like below.
```
docker run -it improbable/thanos:master-2018-10-29-8f247d6 -- store

level=info ts=2018-12-09T13:57:13.65227324Z caller=flags.go:83 msg="StoreAPI address that will be propagated through gossip" address=172.17.0.2:10901
level=info ts=2018-12-09T13:57:13.656174967Z caller=factory.go:35 msg="loading bucket configuration"
store command failed: create bucket client: not found bucket
```

**Comment by medanasslim** [comment]
is anybody find a solution ?

I tried to migrate from thanos v0.1 to v0.2 with the same config of s3 bucket and I still have the error:
store command failed: create bucket client: not found bucket

I have created a new bucket and always the same error 
Thanks

**Comment by bwplotka** [comment]
@medanasslim this is totally separate issue

**Comment by nkggautam** [comment]
@shangjin92 how you resolved your issue? I am having the same problem while running thanos version v0.3.2. And also how to use the thanos commands ?
