### ISSUE TITLE
Vault as a secret backend

### ISSUE THREAD

**Issue by arnitolog** [improbable-eng/thanos#675]
Do you guys have any plans to add Vault as a secret backend?
The use-case is: 
 sidecar retrieves username/password from the Vault and substitutes placeholders in the Prometheus config file. Almost the same as it works for env vars substitution, but get data from Vault.

**Comment by bwplotka** [comment]
No plans for it as we don't want to try to support all secret managements tools users wants to use.

It can be quickly done by your orchestration system (e.g Kubernetes or even bash script) that put secrets from vault in environment and Thanos sidecar envvar substituiting those in config.

**Comment by arnitolog** [comment]
got it.
thanks

чт, 13 дек. 2018 г. в 14:07, Bartek Płotka <notifications@github.com>:
