### ISSUE TITLE
cos: Provider is not depent on preknown object size for upload.

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#679]
Discussion for Reference https://github.com/improbable-eng/thanos/pull/617 

Acceptance Critiria:
* COS provider works even with just  `Upload(ctx context.Context, name string, r io.Reader)` interface (and without deducing implementation of Reader)

Hope we can have some help on this from @jojohappy  in communication with https://github.com/mozillazg/go-cos

**Comment by jojohappy** [comment]
A good news here.

The COS provider has been supported uploading files without the length using the new API version since a few days ago. It's my bad to do not pay attention to the COS API.

So I will update the version of COS provider and make a test.

**Comment by bwplotka** [comment]
Thanks for checking this up! This is awesome news.
