### ISSUE TITLE
Thanos ruler throwing err="no query peer reachable"

### ISSUE THREAD

**Issue by vivekbny** [improbable-eng/thanos#683]
I am trying to run the thanos ruler. when i start it, below error is thrown and it keeps repeating

level=warn ts=2018-12-14T10:50:42.177112042Z caller=manager.go:343 component=rules group=app.rules msg="Evaluating rule failed" rule="alert: MemoryUtilizationThresholdExceeded********************************************************************************************err="no query peer reachable"

To start the Thanos ruler:
./thanos rule --rule-file=/root/thanos-0.1.0.linux-amd64/alert.rules.yml --alert.query-url=http://thanos-queryurl.com:10902 --eval-interval=30s --data-dir=/root/thanos-0.1.0.linux-amd64 --alertmanagers.url=http://alertmanager-url:9093

Can you please advise

Thanks,
Vivek

**Comment by bwplotka** [comment]
Please use thanos 0.2.0 and specify `--query` label.

alert.query does totally something else (it is a reference link for alert page on UI). `thanos ruler --help` can help to check possible options. Problem with 0.1.0 is that it requires gossip. It is not the case on 0.2.0 anymore.

**Comment by vivekbny** [comment]
Thank you @bwplotka, --query label worked in 0.2.0 but not in 0.1.0.

Ruler is now working fine in 0.2.0

**Comment by bwplotka** [comment]
It is fine to use it on prod, but there few missing bits we are working now:
- Metric for query evaluation failure (work in progress on upstream: https://github.com/prometheus/prometheus/pull/4961)
- Partial response support https://github.com/improbable-eng/thanos/pull/687
- Definite list of important alerts to configure for thanos ruler and improved docs.
 
Those wil close up the thanos ruler production readiness, but will in current state (v0.2.0) ruler should work reliable. There are just certain edge, failure cases that we want to improve.

**Comment by vivekbny** [comment]
@bwplotka  Thank you for your detailed response.

I am trying to run the Thanos ruler in docker. I have the alert.rules.yml file in location /root/thanos-0.1.0.linux-amd64/alert.rules.yml and i am using the below command to spin up the thanos ruler as container.

docker run --net=host  thanos/thanos:0.2-SNAPSHOT rule --rule-file=/root/thanos-0.1.0.linux-amd64/alert.rules.yml --query=10.100.20.25:10902 --eval-interval=30s --alertmanagers.url=http://alertmanager-alerts.net:9093

Now, I can able to see the ruler UI. 

**But the issue here is that, rules are not being recognized by the Thanos ruler.it is empty** 

With this same setup, when i run it as a process. it works fine.
./thanos rule --rule-file=/root/thanos-0.1.0.linux-amd64/alert.rules.yml --query=10.100.20.25:10902 --eval-interval=30s --alertmanagers.url=http://alertmanager-alerts.net:9093
 
Can you please guide/help on it.

Thanks,
Vivek
