### ISSUE TITLE
Cannot access thanos metrics

### ISSUE THREAD

**Issue by robvalca** [improbable-eng/thanos#688]
### Versions
thanos, version 0.1.0 (branch: HEAD, revision: ebb58c23a786b2ba714ff07b1795efea7ef37132)
  build user:       root@393679b8c49c
  build date:       20180918-17:02:30
  go version:       go1.10.3

prometheus, version 2.5.0 (branch: HEAD, revision: 67dc912ac8b24f94a1fc478f352d25179c94ab9b)
  build user:       root@578ab108d0b9
  build date:       20181106-11:40:44
  go version:       go1.11.1

### Our setup

1 x prometheus server + thanos sidecar (8c, 16G RAM)
2 x thanos queriers (4c, 8G RAM)
1 x thanos-store + thanos compactor (8c, 16G RAM)
backend: S3 ceph+radosgw
OS: CentOS 7.6

### Issue

Debugging other issues I've realized that lately I cannot access to the metrics older than 15d (prometheus local retention) while we have a few months (~140G) of metrics in S3 and it worked fine before. From the thanos dash I got the following message if I put time range of 1w or older (the metrics are shown but no data older than 15d)

```
receive series: rpc error: code = Aborted desc = fetch series for block 01CYM85GN9Q7XRA5HZJJSCRARD: add chunk preload: reference sequence 0 out of range
```

The thanos store is looping with the following warning:

```
Dec 18 09:19:36 cephthanos-store thanos[11993]: level=warn ts=2018-12-18T08:19:36.704180131Z caller=bucket.go:240 msg="loading block failed" id=01CYX8J17RW9EAECCDSV026JD2 err="new bucket block: load index cache: download index file: get file: The specified key does not exist."
```
And the thanos compactor seems broken:

```
Dec 18 09:02:53 cephthanos-store thanos[13556]: level=error ts=2018-12-18T08:02:53.638097634Z caller=compact.go:201 msg="critical error detected; halting" err="compaction failed: compaction: compact blocks [/var/lib/thanos/compactor/compact/0@{monitor=\"cern\",replica=\"A\"}/01CYKKJB05D515N47V38JH7KJY /var/lib/thanos/compactor/compact/0@{monitor=\"cern\",replica=\"A\"}/01CYKTE22ZY6W7RK4JK5V9EFE7 /var/lib/thanos/compactor/compact/0@{monitor=\"cern\",replica=\"A\"}/01CYM19SAKRWFWYVYYCMV3SSDM /var/lib/thanos/compactor/compact/0@{monitor=\"cern\",replica=\"A\"}/01CYM85GN9Q7XRA5HZJJSCRARD]: write compaction: chunk 8 not found: reference sequence 0 out of range"
```
### Possible cause

Lately we had problems with the compactor crashing due to OOM, and eventually I ran it from a different (bigger) machine and this was probably not a good idea :)  

I've also upgraded to prometheus v.2.5.0 but all was working fine after that, I don't think that is related. I don't have any specific configuration for thanos nor prometheus, just default values. 

Any help/comments about how to unblock the situation? thank you in advance!!

Roberto

**Comment by bwplotka** [comment]
> Lately we had problems with the compactor crashing due to OOM, and eventually I ran it from a different (bigger) machine and this was probably not a good idea :)

Why wrong idea? (:

**Comment by bwplotka** [comment]
Also please update to Thanos v0.2.0 or master, because there were fixes to partial upload issues.

**Comment by bwplotka** [comment]
Related to https://github.com/improbable-eng/thanos/issues/377

**Comment by bwplotka** [comment]
> I though that maybe the temporary files that the compactor stores locally were important for the compactor process and I did not copy them to the new host but I guess that this is not a problem right?

Tmp files can be removed. It's leftover from compactor being restart in between some job.

Please upgrade to v0.2.0 as some of those bugs are fixed. In terms of index, you cannot recreate it because essentially you lost all the label names and locations of encoded samples.

I think you are hitting some old issue already fixed, when we were not correctly checking error: https://github.com/improbable-eng/thanos/pull/403 so please update (:

**Comment by robvalca** [comment]
Deleted the block and now all seems fine. I will update to 0.2.0 ASAP.
Thanks again for the great support :)
