### ISSUE TITLE
dropping store, external labels are not unique

### ISSUE THREAD

**Issue by pippozq** [improbable-eng/thanos#689]
**Thanos, Prometheus and Golang version used**
Thanos, version 0.1.0 (branch: master, revision: 0f15be67b6a51b4b86c25d12271c90986684b2cf)
Prometheus: 2.5
Go: 1.10

**What happened**
i got an error like "dropping store, external labels are not unique"
**What you expected to happen**
I used the k8s file [prometheus.yaml](https://github.com/improbable-eng/thanos/blob/master/kube/manifests/prometheus.yaml) in kube 
seems that this env is not right
`
       replica: '$(HOSTNAME)'
`

**How to reproduce it (as minimally and precisely as possible)**:
None
**Full logs to relevant components**

<details>Logs
<p>

```
level=debug ts=2018-12-18T08:28:58.079368885Z caller=stdlib.go:89 component=cluster caller="peers2018/12/18 08:28" msg=":58 [DEBUG] memberlist: Initiating push/pull sync with: 10.100.3.23:10900"
level=warn ts=2018-12-18T08:29:02.243258145Z caller=storeset.go:222 component=storeset msg="dropping store, external labels are not unique" address=10.100.20.28:10901
level=warn ts=2018-12-18T08:29:02.243310781Z caller=storeset.go:222 component=storeset msg="dropping store, external labels are not unique" address=10.100.19.21:10901
level=warn ts=2018-12-18T08:29:07.243061016Z caller=storeset.go:222 component=storeset msg="dropping store, external labels are not unique" address=10.100.20.28:10901
level=warn ts=2018-12-18T08:29:07.243116069Z caller=storeset.go:222 component=storeset msg="dropping store, external labels are not unique" address=10.100.19.21:10901
level=warn ts=2018-12-18T08:29:12.243430343Z caller=storeset.go:222 component=storeset msg="dropping store, external labels are not unique" address=10.100.19.21:10901
level=warn ts=2018-12-18T08:29:12.243482038Z caller=storeset.go:222 component=storeset msg="dropping store, external labels are not unique" address=10.100.20.28:10901
```

</p>
</details>
**Anything else we need to know**
None

**Comment by pippozq** [comment]
it just warning level

**Comment by bwplotka** [comment]
And that is correct behaviour right?

You don't want to ship this data to Thanos as this will cause you overlaps.

**Comment by pippozq** [comment]
data is right,after i read the doc twice i figured it out
