### ISSUE TITLE
Update thanos/kube/manifests/ files according to the thanos  latest v0.2.0 

### ISSUE THREAD

**Issue by asudhakarreddy** [improbable-eng/thanos#691]
**Thanos, Prometheus and Golang version used**

**What happened**

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by FUSAKLA** [comment]
Sorry, I didn't find the time but thanks to @ervikrant06 it is in progress now
https://github.com/improbable-eng/thanos/pull/709

**Comment by bwplotka** [comment]
Still we can add either configmap or passing this by content, which I like more! (: 
```
        - |
          --objstore.config=type: GCS
          config:
            bucket: <bucket>
```
