### ISSUE TITLE
Allow config reloader to use compressed files (configmaps and secrets)

### ISSUE THREAD

**Issue by wleese** [improbable-eng/thanos#692]
The reloader pkg is used by prometheus-operator. A secret is mounted as file, monitored and a reload done if necessary.

Now a secret/configmap is limited to 1mb. We've hit that limit and would like compression to be used here. Of course prometheus-operator will have to write a compressed secret/configmap first. 

But anyway, changes to the reloader will be needed to support this use case.

Played around with how to solve this and came up with https://github.com/coreos/prometheus-operator/pull/2243/
If there's any interest I'll cleanup, implement suggestions and submit here.

**Comment by bwplotka** [comment]
Valid case, thanks for your PR, let's move implementation discussion there.

**Comment by bwplotka** [comment]
This seems to be done (:  https://github.com/improbable-eng/thanos/pull/693
