### ISSUE TITLE
How thanos query execution happens in sharded prometheus

### ISSUE THREAD

**Issue by vivekbny** [improbable-eng/thanos#701]
Hi,

We have around 4000 node-exporters running and we are scraping it with 4 Prom instances and it is shard based on the node-name. 

All these Prom instances are side-cared by Thanos and it is connected to Thanos-querier.

Now, we are trying to get node_cpu metric for a particular node(xxx) because we don't know which prom is scraping the node_exporter for that particular node(xxx). 

Can you please explain on how the query execution happens in Thanos for the above case.

Thanks,
Vivek

**Comment by bwplotka** [comment]
Hi!

The answe is simple. When you don't filter with external labels of those Prometheuses, Thanos Querier will ask every shard. Each shard will then respond either with empty data (no such exporter there) or with some metric samples if the requested node is actually there (: 

Does it answer your questions?

**Comment by vivekbny** [comment]
Yeah it answers my question. @bwplotka 

But asking every shard will make the thanos query a little heavy right?

**Comment by bwplotka** [comment]
What do you mean `heavy`? (: 

It will ask all "leafs" concurrently, so it will be no slower than just asking just one with data. It will have some minimal footprint on shards without data, yes.

**Comment by vivekbny** [comment]
if the footprints are minimal, it should be fine. @bwplotka 

one another clarification regarding the query is when I m trying to run it as docker container with service discovery flags i am getting the below error.

docker run --network=host thanos/thanos:0.2-SNAPSHOT query --store.sd-files=/root/thanos-0.2.0.linux-amd64/store.yaml --query.replica-label monitor --store.sd-interval=30s

level=info ts=2019-01-02T11:17:49.224555602Z caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=10.63.32.23:10901
level=info ts=2019-01-02T11:17:49.249293363Z caller=flags.go:105 msg="QueryAPI address that will be propagated through gossip" address=10.63.32.23:10902
level=info ts=2019-01-02T11:17:49.278779029Z caller=main.go:256 component=query msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-01-02T11:17:49.278832489Z caller=query.go:436 msg="starting query node"
level=info ts=2019-01-02T11:17:49.278956754Z caller=query.go:405 msg="Listening for query and metrics" address=0.0.0.0:10902
level=info ts=2019-01-02T11:17:49.279016146Z caller=query.go:428 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=error ts=2019-01-02T11:17:49.281080165Z caller=file.go:214 msg="Error adding file watch" path=/root/thanos-0.2.0.linux-amd64 err="no such file or directory"

but there is an yaml in that location

root@********thanos-0.2.0.linux-amd64]# cat /root/thanos-0.2.0.linux-amd64/store.yaml
- targets: ['10.**.**.**:10901','10.**.**.**:10901']

**Comment by bwplotka** [comment]
Yea, it's weird? Are you sure thanos process in docker can access this? Maybe permissions are wrong? Have you tried to execute into docker and ls this file?

**Comment by vivekbny** [comment]
Yeah it is. The same setup works fine when i run it as binary process.

Also regarding the permission they are good

.
