### ISSUE TITLE
querier: Add /api/v1/labels support

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#702]
Prometheus in 2.6.0 added support for new method: https://github.com/prometheus/prometheus/pull/4835

We may want to add same method to Thanos Querier to stay up to date with Query API. StoreAPI we have supports this, but most of implementations do not implement this:
```
func (s *ProxyStore) LabelNames(ctx context.Context, r *storepb.LabelNamesRequest) (
	*storepb.LabelNamesResponse, error,
) {
	return nil, status.Error(codes.Unimplemented, "not implemented")
}
```

This seems to be useful for Grafana adhoc filters feature: https://github.com/grafana/grafana/issues/6038

Let us know if priority of this needs to be increased, currently it does not seem urgent. Also, help wanted (: 

Acceptance Criteria:
* Thanos Querier exposes `/api/v1/labels` that will fanout to store API gRPC labelNames method.
* Store gateway, sidecar and ruler implements this method.

**Comment by GiedriusS** [comment]
This has been added in March so closing! Thanks, @jojohappy ❤️
