### ISSUE TITLE
s3 update failure in sidecar as a result of pull reqeuest 632

### ISSUE THREAD

**Issue by druss17** [improbable-eng/thanos#708]
We encountered the following error in our sidecar after moving to release: master-2018-11-16-d4887bf that had pull request 632:

/data/prometheus/thanos/upload/01D07R41K7NH577M07Q65NDVR5/meta.json as debug/metas/01D07R41K7NH577M07Q65NDVR5.json: upload s3 object: Invalid canned ACL"

This error does not occur on prior releases of the sidecar.

We attempted to fix this issue by applying a canned ACL to our S3 bucket but the product we are using does not support this yet.  Would it be possible to please add a flag that will disable the sending of the UserMetaData that was added in pull request 632?  We are using the IBM Cloud Object Storage product.

Thank you.

**Comment by bwplotka** [comment]
Fix: https://github.com/improbable-eng/thanos/pull/710

**Comment by druss17** [comment]
Thank you for getting started on this so quickly.  It is greatly appreciated.

**Comment by bwplotka** [comment]
Please review if you want it fast (:

**Comment by druss17** [comment]
Sorry, not a golang programmer or I would.  Is there anyone else that could review this code?  If not, I can try and find a golang developer to review.

**Comment by bwplotka** [comment]
Done

**Comment by druss17** [comment]
Thank you for the quick turnaround!!!   I will watch for the next docker image to be available.

**Comment by druss17** [comment]
We used version master-2019-01-07-270d81f
