### ISSUE TITLE
Using a local objstore

### ISSUE THREAD

**Issue by Kokonoe** [improbable-eng/thanos#715]
Hi guys,

Is it possible to use Thanos with a local objstore or another server instead of a remote one (GCP, AWS Bucket, etc...)?

Thank you!

**Comment by bwplotka** [comment]
Yes. Please see [our e2e tests](https://github.com/improbable-eng/thanos/blob/master/test/e2e/spinup_test.go#L290)

It is super easy to install and run one node https://github.com/minio/minio and configure s3 type bucket in Thanos components. (:
