### ISSUE TITLE
store command failed: create bucket client: not found bucket

### ISSUE THREAD

**Issue by medanasslim** [improbable-eng/thanos#719]
Hello,

I tried to migrate from thanos v0.1.0 to v0.2.1 with the same config of s3 bucket 

I have the error: store command failed: create bucket client: not found bucket I have created a new bucket and always the same error

**Full logs**
level=info caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=100.96.3.120:10901
level=debug caller=cluster.go:158 component=cluster msg="resolved peers to following addresses" peers=100.96.8.18:10900,100.96.7.10:10900,100.96.5.15:10900
level=info caller=factory.go:39 msg="loading bucket configuration"
store command failed: create bucket client: not found bucket

**Environment**:
- kube 1.10 (e.g. from /etc/os-release):

Thanks

**Comment by bwplotka** [comment]
Please see `CHANGLOG.md`, configuration flag changed (:

**Comment by bwplotka** [comment]
Sorry for confusing error message. That is being fixed here: https://github.com/improbable-eng/thanos/pull/721
