### ISSUE TITLE
Needing steps for adding s3 bucket as object storage and how to use them with store component.

### ISSUE THREAD

**Issue by ashish-yad** [improbable-eng/thanos#727]
**Needing steps for adding s3 bucket as object storage and also query from them**
I have successfully configured and run thanos sidecar with Thanos query component for multiple prometheus server. 

But I'm confused and struggling on adding S3 storage as Object storage for long term data retention.
I need to use S3 storage for historical data.

I'm new to this technology. It will be really great if you can provide general steps for configuration of Thanos and S3 for adding S3 bucket as object storage for prometheus block storage.

**Comment by FUSAKLA** [comment]
I believe the documentation in https://github.com/improbable-eng/thanos/blob/master/docs/components/store.md and https://github.com/improbable-eng/thanos/blob/master/docs/storage.md#aws-s3-configuration is sufficient but maybe I'm missing something out. 

What do you feel should be better explained there? 
Possibly you can ask questions on the Slack: [#thanos](https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc)

**Comment by bwplotka** [comment]
Otherwise AWS S3 documentations appllies (:

**Comment by base698** [comment]
What properties are required for the S3 bucket for starters.  Thanos fails saying it needs an s3-bucket-endpoint in the bucket.yml.
