### ISSUE TITLE
Show type of store on store overview page

### ISSUE THREAD

**Issue by metalmatze** [improbable-eng/thanos#739]
On the store overview page under `/stores` it would be useful to also display the type of the store (sidecar, store, querier).

![screenshot from 2019-01-15 16-08-30](https://user-images.githubusercontent.com/872251/51196857-49bf4400-18f0-11e9-9f7f-6c5b62269542.png)

As per Slack discussion this needs an extra field to info storeAPI endpoint as gossip only is not enough.

/cc @bwplotka @FUSAKLA

**Comment by bwplotka** [comment]
Thanks for reporting, that makes sense.

Potential solution:
* Add to StoreAPI info endpoint field for type of StoreAPI server.
* Based on got metadata update UI in extra column
* Reuse/adapt https://github.com/improbable-eng/thanos/blob/3c8546ceef9cf13856d91b9897fa816303fc05b6/pkg/block/block.go#L39 enum to have full list of types and source. More info below:

So regarding the implementation I think we need to have typed enums that we can cast either to `source` or `storeapi` or both.

For example: https://play.golang.org/p/gFPdCSOBohK
```
package component

type StoreAPI interface {
  implementsStoreAPI()
  String() string
}

type Source interface {
   producesBlocks()
   String() string
}

type component struct {
   name string
}

func (c component) String() string { return c.name}

type storeAPI struct {
   component
}

func (storeAPI) implementsStoreAPI() {}

type source struct {
   component
}

func (source) producesBlocks() {}

type sourceStoreAPI struct {
   component
   source
   storeAPI
}

var (
   Compactor = source{component{name: "compactor"}}
   Sidecar = sourceStoreAPI{component: component{name: "sidecar"}}
   ...
)
```

**Comment by adrien-f** [comment]
I'll get something going for this !

**Comment by benclapp** [comment]
Perhaps semi related, it'd be nice to be able to provide some labels to various Thanos stores, to be shown in the Announced Labels column on the store page. 

Equivalent of Prometheus' external labels but for Thanos components.

**Comment by bwplotka** [comment]
Hm... I guess for sidecar, Prom external labels are enough?

For stores yes -> we might add that feature which would help to filter out things early on and indentify store, but there is no easy way to automatically create them - there must be added manually
