### ISSUE TITLE
[UI] Hide unhealthy stores after some time

### ISSUE THREAD

**Issue by metalmatze** [improbable-eng/thanos#748]
**Thanos, Prometheus and Golang version used**
This was on Kubernetes running Thanos v0.2.1.

**What happened**
I was looking at the Stores UI and saw a lot of unhealthy stores even though some were gone for 192+ hours.

**What you expected to happen**
I don't really care about stores that are reported as unhealthy after, I would say, 24 hours.

**How to reproduce it (as minimally and precisely as possible)**:
Not actually sure how to reproduce, probably deploy a new store every now and then, but keep at least one store for persisting the gossip state?!

**Full logs to relevant components**
 - 

**Anything else we need to know**
I would be happy to take a look at this and try to fix it, if you could give me a guideline on what type of semantics the filtering should happen on.

![screenshot from 2019-01-17 14-49-53](https://user-images.githubusercontent.com/872251/51323849-97ab8780-1a69-11e9-96de-bc1ecba6abcc.png)

/cc @bwplotka

**Comment by adrien-f** [comment]
Mmm I'm not sure about this one. I tried to mimic Prometheus' Targets page when doing this. Does it removes unhealthy targets about a while ? 

If those stores are supposed to be gone, shouldn't the Query config be updated with a fresher list of stores ?

**Comment by bwplotka** [comment]
It removes, (hopefully), but seems like they are still on page. 

The main problem is that we indentify those StoreAPIs by IP and it's quite wrong. As pod restarts the IP is different but it's actually same storeAPI (:

**Comment by ipstatic** [comment]
@bwplotka Did another PR resolve this?

**Comment by bwplotka** [comment]
Sorry I should link the fix (thought it was linked before): https://github.com/improbable-eng/thanos/pull/910

**Comment by bwplotka** [comment]
It's fixed on master, yes, thanks to @adrien-f

**Comment by ipstatic** [comment]
Great!
