### ISSUE TITLE
GCS bucket configuration issue

### ISSUE THREAD

**Issue by justinmydomain** [improbable-eng/thanos#756]
```
Version details 

Thanos : improbable/thanos:master
Proemtheus : quay.io/prometheus/prometheus: v2.6.1
Prometheus-operator : quay.io/coreos/prometheus-operator: master
```

**What happened**

We have latest Prometheus enabled with Thanos. Enabled thanos sidecar in prometheus-operator _values.yaml_ . Thanos sidecar failed with the following error.

```
Error parsing commandline arguments: unknown long flag '--gcs.bucket'
thanos: error: unknown long flag '--gcs.bucket'
```

Thanos configuration:

    thanos:
      peers: thanos-peers.monitoring.svc.cluster.local:10900
      image: improbable/thanos:v0.2.1
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
      gcs:
        bucket: md-thor-thanos
        secretkey:
          name: gcs-credentials
          key: gcs-credentials.json

**What you expected to happen**

Expected to configure the thanos sidecar to accept the GCS bucket credentials and start backing up to the bucket

Any kind of help will be greatly appreciated.

**Comment by firefixmaarten** [comment]
Please take a look at the release notes. Thanos 0.2.1 uses a config file for bucket configuration :).

**Comment by bwplotka** [comment]
Yup :+1:

**Comment by justinmydomain** [comment]
I have also tried it by creating a secret with the following details. But its not even picking up the bucket configuration in that case.

```
type: gcs
config:
  bucket: md-thor-thanos
  secretkey:
    name: gcs-credentials
    key: gcs-credentials.json
```

Not even adding '--gcs.bucket' to the statefulsets. 

https://github.com/coreos/prometheus-operator/blob/ec16333d4c52d7991b4dea4e80eaa78c941e12bd/pkg/prometheus/statefulset.go#L701


It would be great if you can provide an example of GCS bucket configuration for the latest release.

**Comment by firefixmaarten** [comment]
https://github.com/improbable-eng/thanos/releases

Flag --objstore.config-file to reference to the bucket configuration file in yaml format. Detailed information can be found in document storage.

All clients are configured using --objstore.config-file to reference to the configuration file or --objstore.config to put yaml config directly.

**Comment by firefixmaarten** [comment]
Afaik a secret gets mounted in a kubernetes pod, so you can point it to that file or use the content as argument directly.
