### ISSUE TITLE
Compactor Disk Space

### ISSUE THREAD

**Issue by PsychoSid** [improbable-eng/thanos#759]
Hi,

The compactor docs state "The compactor needs local disk space to store intermediate data for its processing. Generally, about 100GB are recommended for it to keep working as the compacted time ranges grow over time." 

I have a 100gb filesystem dedicated to this and I get "write compaction: write chunks: no space left on device" errors constantly.

Is there a way to calculate the size required for processing ?

**Comment by bwplotka** [comment]
Hey, what Thanos version are you using. I think you are hitting this old issue: https://github.com/improbable-eng/thanos/issues/624

I would recommend upgrading thanos for compactor at least (:

**Comment by PsychoSid** [comment]
Nope:-
Version | 0.2.1
30e7cbdafd3ef01189f202945c2728fcf37e1cf1

I am running as a daemon if that make a difference

**Comment by bwplotka** [comment]
Cool, 

>  Generally, about 100GB are recommended

It is not a hard limit, it's just recommendation for average setup. Are you sure your blocks are not just too big for this disk size? Can you look into object storage how large they are? also full logs would be helpful.

**Comment by PsychoSid** [comment]
Hi,

Thanks for helping out.

The size of the objects in "chunks" is 536mb and they roll up to varied sizes.

Logs look like this:-
`Jan 24 01:32:16 lpqospeu50274 thanos_compactor: level=info ts=2019-01-24T08:32:16.405430846Z caller=compact.go:816 msg="start sync of metas"
Jan 24 01:32:16 lpqospeu50274 thanos_compactor: level=info ts=2019-01-24T08:32:16.478850706Z caller=compact.go:822 msg="start of GC"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192121267Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192287772Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.19233343Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="f
ailed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/t
hanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192374813Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192433348Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192484579Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192508952Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192531581Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192565979Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.19258962Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="f
ailed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/t
hanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192619571Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192651472Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192678233Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib$
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192651472Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg=$
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib$
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192678233Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg=$
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib$
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192712551Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg=$
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192777219Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192812467Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192862854Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192888399Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192941358Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.192967282Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.193023106Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks" err="remove /var/lib/
thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.193062006Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V" err="remove /var/lib/thanos/
compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=warn ts=2019-01-24T09:34:16.193196239Z caller=objstore.go:164 compactionGroup="0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}" msg="
failed to remove file on partial dir download error" file="/var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V" err="remove /var/lib/thanos/
compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V: directory not empty"
Jan 24 02:34:16 lpqospeu50274 thanos_compactor: level=error ts=2019-01-24T09:34:16.193418755Z caller=compact.go:265 msg="retriable error" err="compaction failed: compaction: download block 01D1Z1ASCR4VEHAQ67ZA16WS9V: copy object to file: wr
ite /var/lib/thanos/compact/0@{cluster=\"v4/customer/paas/e2\",environment=\"ecp-prometheus-e2_blue\",replica=\"lpqosput50217\"}/01D1Z1ASCR4VEHAQ67ZA16WS9V/chunks/000022: no space left on device"
Jan 24 02:34:26 lpqospeu50274 thanos_compactor: level=info ts=2019-01-24T09:34:26.904949895Z caller=compact.go:816 msg="start sync of metas"`

**Comment by bwplotka** [comment]
oh! Well for sure it might conflict (: Please don't do it (:

**Comment by PsychoSid** [comment]
Yeah - moved them apart now :)

**Comment by PsychoSid** [comment]
Just chucked a load of space at my 2 dev environments where I am putting this through it's paces. One maxed out at 277gb, and the other at 250gb.

The getting_started doc says between 100-300gb, and the compact does says 100gb is enough I guess I took the latter.

I will close this and say thank you for the time spent on this and keep an eye on it, appreciate the help and the product. Cheers.

**Comment by bwplotka** [comment]
:+1:
