### ISSUE TITLE
FileSD not working for thanos query when running it as docker container

### ISSUE THREAD

**Issue by vivekbny** [improbable-eng/thanos#767]
Hi,

@bwplotka 

We are running thanos query as docker container in nonprod and it is working fine.

Everytime to add a new store, we use to update the docker command. So, we planned to use file SD for adding the stores without stopping the container.

When i tried to run thanos query with fileSD, it keeps failing to watch the file and throws err="no such file or directory"

[root@x0012345 monitoring]# cat /hull/dev/xyz/monitoring/store.yaml
- targets: ['10.160.60.6:10901','10.150.50.5:10901']

docker run --net=host  thanos-imagename query --store.sd-files=/hull/dev/xyz/monitoring/store.yaml
level=info ts=2019-01-28T08:40:36.432992124Z caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=10.170.70.7:10901
level=info ts=2019-01-28T08:40:36.446071944Z caller=flags.go:105 msg="QueryAPI address that will be propagated through gossip" address=10.170.70.7:10902
level=info ts=2019-01-28T08:40:36.464817916Z caller=main.go:256 component=query msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-01-28T08:40:36.464874275Z caller=query.go:427 msg="starting query node"
level=error ts=2019-01-28T08:40:36.465040962Z caller=file.go:214 msg=**"Error adding file watch" path=/hull/dev/xyz/monitoring/store.yaml err="no such file or directory"**
level=info ts=2019-01-28T08:40:36.472695022Z caller=query.go:419 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2019-01-28T08:40:36.472844226Z caller=query.go:396 msg="Listening for query and metrics" address=0.0.0.0:10902

Can you please help

Thanks,
Vivek

**Comment by jojohappy** [comment]
Hi, could you provide the full command of `docker run`? I guess you might not mount the host filesystem for the container. I have tested in my kubernetes cluster successfully.

**Comment by jojohappy** [comment]
@vivekbny maybe you should run command below:
`docker run --net host -v /path/to/real/sidecarstore.yml:'/root/thanos/sidecarstore.yml' improbable/thanos:master-2019-01-25-c54ff55 query --store.sd-files=/root/thanos/sidecarstore.yml --query.replica-label monitor --store.sd-interval=30s`

The container filesystem is different with your local filesystem, you should bind the local volume into container.

**Comment by vivekbny** [comment]
@jojohappy I ran the below docker command and i still see the query is not picking up the stores.

docker run -d --net host -v /hull/dev/pki/monitoring/store.yaml:/root/store.yaml improbable/thanos:master-2019-01-25-c54ff55 query --store.sd-files=/hull/dev/pki/monitoring/store.yaml --query.replica-label monitor --store.sd-interval=30s

[root@x0012345 monitoring]# docker logs fdb46dc2a1b5
level=info ts=2019-01-28T14:45:29.046528478Z caller=flags.go:90 msg="StoreAPI address that will be propagated through gossip" address=10.63.32.27:10901
level=info ts=2019-01-28T14:45:29.059405194Z caller=flags.go:105 msg="QueryAPI address that will be propagated through gossip" address=10.63.32.27:10902
level=info ts=2019-01-28T14:45:29.074262055Z caller=main.go:256 component=query msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-01-28T14:45:29.07433359Z caller=query.go:441 msg="starting query node"
level=info ts=2019-01-28T14:45:29.074641955Z caller=query.go:410 msg="Listening for query and metrics" address=0.0.0.0:10902
level=error ts=2019-01-28T14:45:29.074822653Z caller=file.go:214 msg="Error adding file watch" path=/hull/dev/pki/monitoring err="no such file or directory"
level=info ts=2019-01-28T14:45:29.074926424Z caller=query.go:433 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901

Thanks,
Vivek

**Comment by vivekbny** [comment]
@jojohappy 

It is working now

Thanks,
Vivek

**Comment by bwplotka** [comment]
:+1:
