### ISSUE TITLE
query: Metrics missing when using query component

### ISSUE THREAD

**Issue by rsommer** [improbable-eng/thanos#821]
**Thanos, Prometheus and Golang version used**
```
thanos, version 0.2.1 (branch: HEAD, revision: 30e7cbdafd3ef01189f202945c2728fcf37e1cf1)
  build user:       root@79ffcf51ff9b
  build date:       20181227-15:44:56
  go version:       go1.11.4
```
```
prometheus, version 2.6.0 (branch: HEAD, revision: dbd1d58c894775c0788470944b818cc724f550fb)
  build user:       root@bf5760470f13
  build date:       20181217-15:14:46
  go version:       go1.11.3
```

**What happened**
I recently did setup thanos for long term metric storage. After the first few weeks of running the setup, I tried to zoom out in grafana to see how everything works out. While zooming out to 30 days in grafana, I started to see gaps in the displayed metrics. There is metric data for the selected time range. If I do query prometheus directly, I get the expected results.

**What you expected to happen**
Getting all existing data when querying via thanos query.

**Full logs to relevant components**
[query.log](https://github.com/improbable-eng/thanos/files/2839813/query.log)

Queried via prometheus:

![node-monitoring-30-days-via-prometheus](https://user-images.githubusercontent.com/178013/52397483-03f03880-2ab6-11e9-9792-56d679e7cf82.png)

Queried via thanos query:

![node-monitoring-30-days-via-thanos](https://user-images.githubusercontent.com/178013/52397502-166a7200-2ab6-11e9-8d4c-83522542bc0d.png)

**Comment by jojohappy** [comment]
hi, it seems to be as same as this [issue](https://github.com/improbable-eng/thanos/issues/396), it has been fixed in this [PR](https://github.com/improbable-eng/thanos/pull/718).

You try to upgrade the Thanos with the newest master head or wait for the 0.3.0 version, the new version will come soon.

**Comment by rsommer** [comment]
@jojohappy you're right, I just built thanos from the master branch and the problem has gone away. I did miss the referenced bug, sorry for the duplication.
