### ISSUE TITLE
store: support for <> != <val> matcher is not implemented after upgrade to V0.3.0

### ISSUE THREAD

**Issue by arnitolog** [improbable-eng/thanos#834]
**Thanos, Prometheus and Golang version used**

* Thanos: all components 0.3.0
* Prometheus: 2.7.1

**What happened**
After upgrading query and store components from 0.2.1 to 0.3.0 we started seeing below errors for  queries which use "not-equal" (!=) binary operator:

`receive series: rpc error: code = Aborted desc = fetch series for block 01D3EFDYWZ6WX3C1SEHF3ESA95: expanded matching posting: match labels: support for <> != <val> matcher is not implemented; empty matcher for label name mode`

**What you expected to happen**
query component returns the correct value

**How to reproduce it (as minimally and precisely as possible)**:
any query with != (not-equal) binary operator. My, in particular, looks like: 
`node_cpu_seconds_total{mode!="idle"}`
**Full logs to relevant components**

**Anything else we need to know**

**Comment by bwplotka** [comment]
Fix in progress.

**Comment by bwplotka** [comment]
https://github.com/improbable-eng/thanos/pull/839
