### ISSUE TITLE
Latency increasing notably with result size

### ISSUE THREAD

**Issue by fabxc** [improbable-eng/thanos#84]
The result size of the a final PromQL query seems to have very significant effect on total latency.

For example, `apiserver_request_count{job="apiserver"}` takes at the order of 15-20 seconds. If wrapped with a `sum` like `sum(apiserver_request_count{job="apiserver"})`, latency sharply decreases to 2-3 seconds.

The data queried from GCS and flowing into query nodes is the same. The query engine is actually doing more work.
So the whole delta seems to come from sending the result after data fetching and processing completed successfully. The result is bigger, so more JSON encoding happens and more data is sent to the browser. The difference seems rather extreme nonetheless.

Query node is in the US, end client in EU. Still seems rather unusually high.
The query node is accessed via an SSH tunnel, which might play a role as well.

**Comment by Bplotka** [comment]
I can reproduce that easily as well for VPN setup and US cluster (from 5-16s) to reliable 500ms for `go_goroutines{}` vs `sum(go_goroutines{})`

**Comment by fabxc** [comment]
Looks like the tunnel is the issue.

Retrying it directly on the node, the queries take 800 and 600ms respectively. I've been having issues with my SSH traffic apparently being heavily throttled for a couple of days now. Not sure whether by my ISP or GCP.

**Comment by fabxc** [comment]
After having access to a full setup with store nodes and sidecars, it appears that queries hitting sidecars/Prometheus servers are significantly slower. That's unlikely to be just the plain data duplication overhead.

A few things found out:
* The HTTP v1 API is not using gzip
* The HTTP v1 API doesn't encode straight into the response writer but into an intermediate byte slice

Both are problematic in general but especially for the Prometheus proxy which uses that very API to get full resolution data, which means massive responses.

Regardless of fixing above issues, it probably is a good idea to switch to the remote read APIs. They are still experimental and not gRPC yet but at least protobuf over HTTP.

**Comment by fabxc** [comment]
@Bplotka can we close this? The issue seems entirely fixed for me?

**Comment by Bplotka** [comment]
yup, let's close it for now. Cannot repro
