### ISSUE TITLE
thanos 0.3.0 rule compent

### ISSUE THREAD

**Issue by zhxiaom5** [improbable-eng/thanos#854]
thanos 0.3.0
thanos rule

http get  http://xxx:xx/rules
below error occus
level=warn ts=2019-02-18T13:52:26.392412042Z caller=ui.go:86 msg="template expansion failed" err="template: :66:57: executing \"content\" at <.GetEvaluationTime.S...>: can't evaluate field GetEvaluationTime in type *rules.Group"

**Comment by bwplotka** [comment]
Thanks for report. Can you submit the rule that causes this? (: Looks like a valid bug.

**Comment by zhxiaom5** [comment]
I would love to，but my rule really long and complex，maybe I should get to know which rule trigger this error before I paste all the rules

**Comment by davtsur** [comment]
Seems like need to use GetEvaluationDuration in rules.html instead of GetEvaluationTime.

Reference :
https://github.com/prometheus/prometheus/pull/4416/files

**Comment by davtsur** [comment]
@bwplotka, can u take a look at the PR: 

https://github.com/improbable-eng/thanos/pull/894

BTW I noticed that the bindata.go isn't updated when running "make".
