### ISSUE TITLE
Thanos0.3.1 rules  cannot dynamic loading configuration?

### ISSUE THREAD

**Issue by xingmin860818** [improbable-eng/thanos#859]
**Thanos, Prometheus and Golang version used**

**What happened**

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by xingmin860818** [comment]
when I modify the rule files, rule component should reload it dynamic.

**Comment by bwplotka** [comment]
Why it was closed? (: This feature should work.

**Comment by xingmin860818** [comment]
I found nobody response me for several days, and I move back the rules to promethues , It works for me now,thank you.

**Comment by bwplotka** [comment]
It is recommended to store rules locally yes, but still this issue makes sense, just we need to edit description for others to be able to read the details through: how to reproduce this and what is expected (:
