### ISSUE TITLE
multi prometheus instances send repeated alerts

### ISSUE THREAD

**Issue by xingmin860818** [improbable-eng/thanos#861]
**Thanos, Prometheus and Golang version used**
prometheus2.7.1 
thanos v0.3.1

**What happened**
I have to instance of prometheus collect the same targets. I config uniq extrnal label for deduplacate.
But when prometheus trigger alert to alertmanager,the alertmanager send two the same alerts. I found it is because the extrnal label. Then I tried the rule component , the problem is solved. but the official dosen't recommend to deploy the rules to rule component.
**What you expected to happen**
I want to  I keep the rule files in prometheus and alertmanager can deduplacate the alerts.
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by FUSAKLA** [comment]
Hi, you should use relabeling in the prometheus alerting configuration section to drop the unique label from all alerts so they have the same labels and alertmanager deduplicates them.

**Comment by xingmin860818** [comment]
That's  great，I will try it . Thank a lot.

**Comment by bwplotka** [comment]
Essentially you need this: https://github.com/improbable-eng/thanos/blob/master/tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar.yaml#L182

**Comment by 0xVox** [comment]
To save some clicks if you've just come from a search result, as that's no longer in master 

https://github.com/thanos-io/thanos/blob/acb1cb03fd5ecf3e044a97642be50897db11c34f/tutorials/kubernetes-demo/manifests/prometheus-ha-sidecar.yaml#L179
