### ISSUE TITLE
thanos store broken regex

### ISSUE THREAD

**Issue by danielmotaleite** [improbable-eng/thanos#864]
Thanos: improbable/thanos:v0.3.1
Prometheus: 2.5.0

**What happened**
Query the line below and thanos store will return all return all http_status, not just 522. If i disabled thanos store, it returns nothing (as there are no 522 at this time)
`cloudflare_pop_http_responses_sent{http_status=~"522",colo_id=~"LIS"}`

**What you expected to happen**
thanos store should respect the field regex

**How to reproduce it (as minimally and precisely as possible)**:
I tried several thing to reproduce and looks like this works with any field data (eg: `hostname: host123` and `hostname: host456`) and that is in the thanos store. The query regex must not have real regex data that would match something directly (eg:  `hostname=~".ost123"`), it must not match anything, so it tried substring (eg: `hostname=~"ost123"` )
thanos store will return data for all both hostname with that last query, but only return the host123 in the previous

**Full logs to relevant components**
![thanos-broken-regex-prometheus](https://user-images.githubusercontent.com/11890049/53251150-e88b4d00-36b3-11e9-9019-e4857eccf584.png)
![thanos-broken-regex](https://user-images.githubusercontent.com/11890049/53251192-00fb6780-36b4-11e9-97a9-2b94c999e622.png)

**Comment by danielmotaleite** [comment]
i reverted to thanos 0.3.0 and the problem is gone, so it's something that changed in that version, probably in this commit https://github.com/improbable-eng/thanos/pull/839 by @bwplotka 

Of course, i can also workaround with a correct regex, but it's still a different behavior from prometheus

**Comment by waderobson** [comment]
I'm seeing this issue too. 

![image](https://user-images.githubusercontent.com/1497790/53262363-3c357080-368b-11e9-9a6a-0a8fb36e1e21.png)

![image](https://user-images.githubusercontent.com/1497790/53262419-5e2ef300-368b-11e9-90e0-d7db7e7c6eb4.png)

**Comment by benclapp** [comment]
This sounds like issue #833, which has been fixed by #862 but not yet released.

**Comment by waderobson** [comment]
Yup, I'm good now thanks @benclapp I didn't notice that.
