### ISSUE TITLE
too many compact_{thanos_compactor_pod_name}_runtime_*  metrics

### ISSUE THREAD

**Issue by turbotankist** [improbable-eng/thanos#870]
Hello
We have one thanos-query and many different clusters behind it. In That clusters we have thanos-stores and thanos-compactors in a pods. Sometimes pods are being recreated with new names. Also we get metrics from these pods. After few month thanos-query has too many metrics with names as compact_{thanos_compactor_pod_name}_runtime_.*  and if I try to search any metrics then query works very slowly.  
![image](https://user-images.githubusercontent.com/9462236/53474689-d2e4a180-3a7e-11e9-8c0d-2ab18899f2da.png)
How to delete it?
When I trying to get one of these metric in 1y, query return "No datapoints found."

**Comment by bwplotka** [comment]
Hmm. Weird, let us look this place through.

**Comment by FUSAKLA** [comment]
Hi, what version of thanos do you use?
IIRC those unique metrics were removed in the newer version of thanos. 

About  removing them.. this is unfortunately not possible right now. 
For more info about deleting metrics see for example this issue https://github.com/improbable-eng/thanos/issues/415

**Comment by turbotankist** [comment]
removing old backet with metrics resolve it
