### ISSUE TITLE
Sidecar can't be added back to store list (sd via peers) after restart?

### ISSUE THREAD

**Issue by wklken** [improbable-eng/thanos#875]
**Thanos, Prometheus and Golang version used**
- Thanos 0.3.1
- Prometheus 2.7.1

**What happened**
- Upgrade all components to 0.3.1, include all sidecars, it's ok. The sd is gossip peers.
- Restart 3 of the sidecars, 1 of the sidecars in the store list: status=`Down`, error_message=`removing store because it's unhealthy or does not exist`, another 2 sidecars are ok.
- But in the Query-Graph, the query can query and get the recent data of the `Down` sidecar
- If I restart all query compoents, all the sidecars are `Up`
- The sidecar peers is in the metric `thanos_store_node_info`.

![image](https://user-images.githubusercontent.com/2002216/53559022-36a4c280-3b84-11e9-9c5e-3ffa74ef83d7.png)

**What you expected to happen**
- All the sidecars are `Up` after restart.

**How to reproduce it (as minimally and precisely as possible)**:
- Use thanos v0.3.1, sd via gossip peers
- Restart sidecar

**Full logs to relevant components**

I grepped all logs of the query components.
There got no log `update of store node failed` of the sidecar which status is `Down`

**Anything else we need to know**

No warn log `update of store node failed`, maybe is the page in `Query` did not get the right data? any clues?

Thanks:)

**Comment by wklken** [comment]
when Unhealthy, delete from `s.stores`

https://github.com/improbable-eng/thanos/blob/master/pkg/query/storeset.go#L225

when Connected and checked healthy,  should it be added back to `s.stores`?

https://github.com/improbable-eng/thanos/blob/master/pkg/query/storeset.go#L312

It should be like this ?

```
s.stores[addr] = store
```
I'm not sure is the len(s.stores) is always equals to len(s.storeSpecs()), will read the code later
---------

**Comment by GiedriusS** [comment]
I think there were some fixes regarding this in the last few versions. Could you check out `0.5.0` and see if this still happens?

**Comment by wklken** [comment]
Sorry, all the sd of my environments are  gossip peers, so I can't upgrade to 0.5.0.  Close the issue:)
