### ISSUE TITLE
Query api/v1/targets is not good

### ISSUE THREAD

**Issue by muzili1** [improbable-eng/thanos#885]
When I use thanos to query "api/v1/targets" that is not good.I found that thanos did not implement this method.I don't know why and this makes me confused.

**Comment by davtsur** [comment]
What targets did u expect to see? the targets of each store that the query component uses?

**Comment by muzili1** [comment]
With "/api/v1/targets" which is one of the Prometheus HTTP v1 APIs, I want to see all targets monitored by prometheus servers.

**Comment by bwplotka** [comment]
There is no way, and need for have that on Thanos Querier. It's up to Store API how it collects the metrics. In case of Prometheus + sidecar, you can just go there to see targets. (:

**Comment by GZijian** [comment]
May I ask why Thanos sidecar uses remote-read api(/api/v1/read) rather than query api(/api/v1/query or /api/v1/query_range)?
