### ISSUE TITLE
C++ Client for Thanos

### ISSUE THREAD

**Issue by thebuleon29** [improbable-eng/thanos#909]
Hi,

Me and my colleagues are considering Prometheus as a Time Series and monitoring System for a project, but it lacks some functionalities that Thanos has (e.g. downsampling). The thing is that we are working in C++, which is supported by Prometheus. So I wanted to know if using Thanos with C++ is possible or if Go is absolutly mandatory.

**Comment by bwplotka** [comment]
I mean what client exactly do you mean? (: StoreAPI gRPC client - if yes, it's `proto` gRPC so you can generate yourself C++ client just fine, but not sure if you need programmatic access for that.

Essentially what exactly API you want to access programatically?

**Comment by thebuleon29** [comment]
This is my first time with a Time Series DB so I may be asking something completely useless, but what I meant was a client to send PromQL queries to the server and get back data with the adequate level of granularity.

**Comment by bwplotka** [comment]
Cool, I think you want to then ask Prometheus IRC or mailist (or Prometheus-dev) as we use exactly the same QueryAPI as Prometheus does, so most likely someone has some c++ client handy. (:

**Comment by bwplotka** [comment]
Ask for C++ QueryAPI client (: It uses REST HTTP so it's easy to implement one as well. But I am sure something is there..

Actually just searched: https://github.com/jupp0r/prometheus-cpp this is official one from https://prometheus.io/docs/instrumenting/clientlibs/ list

**Comment by bwplotka** [comment]
It will work with Thanos just fine
