### ISSUE TITLE
store version 0.2.1，did --data-dir="./data"   working？

### ISSUE THREAD

**Issue by zhxiaom5** [improbable-eng/thanos#916]
My store process was like this，I use mino cluster as storage
but ，store seems not cacheing much remote bucket，for  the size of data-dir only 31M，meantime the flow between store and mino was really large（more than 1Gbit/s）
./thanos store --data-dir /var/thanos/store --objstore.config-file bucket_config.yaml --index-cache-size 1024MB --chunk-pool-size 20GB --http-address=0.0.0.0:10992 --grpc-address 0.0.0.0:10991 --cluster.disable

**Comment by bwplotka** [comment]
That's indended. There is rarely filesystem cache in this point we do RAM cache mostly.

**Comment by zhxiaom5** [comment]
any possiblity we cache locally，not just ram，the ram size is limit
