### ISSUE TITLE
Thanos downsample not downsampling resolution to 1h

### ISSUE THREAD

**Issue by stepanovmm1992** [improbable-eng/thanos#924]
I starting downsample. Thanos downsample resolution to 5 minets, but not downsample to 1h. May be i should use any way flag? But in help not information about this.

**thanos version**:

thanos, version 0.3.2 (branch: HEAD, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       root@e9a9c28f966a
  build date:       20190304-17:11:05
  go version:       go1.11.5

**Output thanos downsample**:
<pre>
thanos downsample --objstore.config-file=/path/to/minio/config --data-dir=/path/to/data/dir
level=info ts=2019-03-14T13:05:46.647603834Z caller=factory.go:39 msg="loading bucket configuration"
level=info ts=2019-03-14T13:05:46.649020404Z caller=downsample.go:92 msg="starting downsample node"
level=info ts=2019-03-14T13:05:46.649108995Z caller=downsample.go:74 msg="start first pass of downsampling"
level=info ts=2019-03-14T13:05:46.89370969Z caller=downsample.go:80 msg="start second pass of downsampling"
level=info ts=2019-03-14T13:05:47.101386741Z caller=main.go:184 msg=exiting
</pre>

**Output thanos bucket inspect**:
<pre>
thanos bucket inspect --objstore.config-file=/path/to/minio/config
level=info ts=2019-03-14T13:07:22.085343918Z caller=factory.go:39 msg="loading bucket configuration"
|            ULID            |        FROM         |        UNTIL        |  RANGE  | UNTIL-COMP |  #SERIES  |    #SAMPLES    |   #CHUNKS   | COMP-LEVEL | COMP-FAILED |       LABELS       | RESOLUTION |  SOURCE   |
|----------------------------|---------------------|---------------------|---------|------------|-----------|----------------|-------------|------------|-------------|--------------------|------------|-----------|
| 01D5TT428K9PBS02GQGW3BFQ82 | 07-02-2019 03:00:00 | 09-02-2019 03:00:00 | 48h0m0s | -8h0m0s    | 2,294,800 | 20,161,066,783 | 164,023,160 | 3          | false       | monitor=prometheus | 0s         | compactor |
| 01D5TWAVK7W8BFDZ2TN44N4FMD | 07-02-2019 03:00:00 | 09-02-2019 03:00:00 | 48h0m0s | 192h0m0s   | 2,294,348 | 1,078,509,471  | 9,634,535   | 3          | false       | monitor=prometheus | 5m0s       | compactor |
| 01D5TTP2N17SGD1FR7NMA2TW5P | 09-02-2019 03:00:00 | 11-02-2019 03:00:00 | 48h0m0s | -8h0m0s    | 2,418,815 | 18,901,952,349 | 160,489,685 | 3          | false       | monitor=prometheus | 0s         | compactor |
| 01D5TXPPKCKZQ10NQCV9H2AAWY | 09-02-2019 03:00:00 | 11-02-2019 03:00:00 | 48h0m0s | 192h0m0s   | 2,418,363 | 1,069,558,134  | 9,317,763   | 3          | false       | monitor=prometheus | 5m0s       | compactor |
| 01D5VBMV995K3YA9RQ0V04KC2A | 11-02-2019 03:00:00 | 13-02-2019 03:00:00 | 48h0m0s | -8h0m0s    | 2,575,738 | 17,077,310,868 | 139,090,874 | 3          | false       | monitor=prometheus | 0s         | compactor |
| 01D5XHR0D8F5VKM3TE4CAT4RRP | 11-02-2019 03:00:00 | 13-02-2019 03:00:00 | 48h0m0s | 192h0m0s   | 2,575,738 | 934,589,507    | 8,439,227   | 3          | false       | monitor=prometheus | 5m0s       | compactor |
| 01D5VC50Z93TJTCZMD462J4FG8 | 13-02-2019 03:00:00 | 15-02-2019 03:00:00 | 48h0m0s | -8h0m0s    | 1,847,274 | 14,184,596,453 | 118,286,627 | 3          | false       | monitor=prometheus | 0s         | compactor |
| 01D5XJXDK4M6XJT3TZD921P4S8 | 13-02-2019 03:00:00 | 15-02-2019 03:00:00 | 48h0m0s | 192h0m0s   | 1,846,821 | 766,919,703    | 7,110,071   | 3          | false       | monitor=prometheus | 5m0s       | compactor |
level=info ts=2019-03-14T13:07:22.362321406Z caller=main.go:184 msg=exiting
</pre>
**Environment**:
- OS (e.g. from /etc/os-release): Centos 7

**PS**: Can you help? We collect many metric, but cannot display because thanos storage down if i call data of the 4 weeek.

**Comment by FUSAKLA** [comment]
Hi, downsampling to 1h blocks happens only for blocks older than 10 days
According to the output of bucket inspect you have to wait few days.
