### ISSUE TITLE
sidecar: design

### ISSUE THREAD

**Issue by GZijian** [improbable-eng/thanos#925]
## May I ask some questions about design of Thanos? ##
1. As I see in the [document](https://github.com/improbable-eng/thanos/blob/master/docs/design.md#metric-data-backup), thanos section may be added to the file _meta.json_。But when will this happen? I didn't see this section in any of my prometheus servers.

2. Can I deploy a prometheus in k8s and run its sidecar process out of k8s?

3. Why do you prefer _remote-read_ api rather than _query/query_range_ api？Does this mean the sidecar component treat prometheus as a remote TSDB? Or is there any other good reasons?

Thank you.

**Comment by bwplotka** [comment]
1. It's done on upload time. Sidecar attaches that on the fly.
2. It will be hard to set up as sidecar has to watch the Prometheus directory AND serve gRPC traffic. What's the benefit of that?
3. Exactly this: `the sidecar component treat prometheus as a remote TSDB`. We do PromQL evaluation on the global level not the Prometheus level.

**Comment by bwplotka** [comment]
https://github.com/improbable-eng/thanos/pull/929

**Comment by muzili1** [comment]
I run a sidecar out of k8s and prometheus in k8s, There is no problem with the current query usage.What problems might happen in the future?

**Comment by GiedriusS** [comment]
Most likely none unless potential performance problems because Sidecar is supposed to be as close to Prometheus as possible "physically" :)
