### ISSUE TITLE
How to handle Alertmanager discovery?

### ISSUE THREAD

**Issue by fabxc** [improbable-eng/thanos#93]
With #92 an initial version of the rule component is largely complete. 

What's still missing is sending out the alerts to Alertmanagers. Upstream uses the standard service discovery integrations and designated config section for that.
Some upstream dependency decoupling work I did last week however makes the notification sending properly pluggable.

Prometheus' service discovery is quite useful for extracting meta data and doing advanced filtering. Neither really seem to be a concern when sending alerts to a small set of Alertmanagers. DNS is basically in place everywhere and seems sufficient after all.

I'd like to consider going back to a simple `--alertmanagers` flag, that just allows a few specifics regarding used DNS records and ports.

1. `http://alertmanager.example.org:8080` – just sends alerts to that specific address using HTTP
2. `dns+https://alertmanager.example.org:8080` – sends alerts to each A record for the hostname name using port 8080 for each, uses HTTPS
3. `dnssrv+https://alertmanager.example.org` – like 2. but queries SRV records and uses the port specified there
4. `dns+https://alertmanager.example.org:8080/path/prefix/` – like 2. but uses a path prefix

The flag could be repeatable.
That solves virtually all sane use cases well enough with minimal learning curve.

The alternative is pulling in the whole dependency chain of the Prometheus discovery framework and requiring configuration files with relabeling for the rule component.

Another thing upstream supports are relabeling rules for alerts. The only reasonable use case I can think of is dropping "replica" labels from alerts. Since replicas however are a first-class concept in Thanos, we'd handle that case in a first-class manner.

**Comment by fabxc** [comment]
Asking on upstream IRC for alert relabeling use cases I got:

* ensuring a HA pair end up with the same alert labels

See above, doesn't apply to Thanos

* dropping alerts that are "info" level, and shouldn't go to the AM

Heavy alert sending load is at O(10000) active alerts. That's not enough for performance relevance. If it is about visibility, Alertmanager should still be the canonical place to look at alerts and this would merely compensate for an UI issue.
Plus, each rule node would then have its own UI, which defeats the purpose of a global query view.

I don't think this is relevant.

* sending a subset of alerts to some AM system

This is functional sharding to me can be sufficiently divided along alerting rules. We should encourage separate rule HA pairs with different rule subsets, i.e. this should be dealt with at the configuration management level.

**Comment by fabxc** [comment]
Mh, one thing this does not cover is everything regarding auth to Alertmanagers. Pulling that into the  flag might be a bitch much – have to think about it.

**Comment by fabxc** [comment]
Another argument for implementing our own alert sender is that the Prometheus implementation has a behavior of not respecting the external labels if the underlying alert already has them set.
The upstream sentiment seems to be to fix this up by additionally adding relabeling rules re-forcing the external labels onto the alerts again.

We already had concerns about that behavior for external labels for metrics. External labels enforce a global structure and thus should not be overwriteable by a metric being exposed somewhere randomly.

**Comment by Bplotka** [comment]
OK there multiple questions here as far as I can see:
1. Config files vs flags:

As discussed offline, we are getting more & more complicated flagset, if we will add potential auth options, we will have lots of orthogonal flags that will have complicated semantics and the only place to explain these will be --help.. I know we want to avoid config files as much as possible and we don't have tooling for that. Fortunately that might be only little of these.. E.g we don't need to implement support for all types of auth like OIDC, Oauth2, SAML ;p maybe basic auth and certs will be enough? If that we can still stick to flags easily.

2. Implementing our own tiny DNS-based discovery vs grabbing Prometheus one:
 I totally agree it does not make sense to grab the huge chunk of code for the whole SD, just for tiny discovery that DNS can handle.

Regarding configuration:
> I'd like to consider going back to a simple --alertmanagers flag, that just allows a few specifics regarding used DNS records and ports.

> http://alertmanager.example.org:8080 – just sends alerts to that specific address using HTTP
dns+https://alertmanager.example.org:8080 – sends alerts to each A record for the hostname name using port 8080 for each, uses HTTPS
dnssrv+https://alertmanager.example.org – like 2. but queries SRV records and uses the port specified there
dns+https://alertmanager.example.org:8080/path/prefix/ – like 2. but uses a path prefix

Looks like we already did something like that in `known-peers` flag, so maybe worth to make that a standard way in our code of doing DNS-based discovery (and use same syntax for these magic `schemes`).

3. Relabeling, should we add it and how?
If we go through all of these use cases:
- replica drop, as you said, replica is first-class citizen, so just single flag option. This fixes HA problem.
- dropping some alerts, advanced rules for alerts routing: all of these, single [alertmanager](https://github.com/prometheus/alertmanager) can handle, so I think we can just leave it just there. The reasoning would be the same as with why Prometheus or Thanos does not have option to hide the API behind some auth. If you want that - put your own service on top of it that you like to solve this single use case. I don't think it make sense to duplicate the work that alertmanager already implements.

**Comment by fabxc** [comment]
We went with options for direct IPs or DNS discovery.
