### ISSUE TITLE
regression: thanos store 0.3.2 stop serving requests

### ISSUE THREAD

**Issue by danielmotaleite** [improbable-eng/thanos#931]
I upgrades to thanos:0.3.2 and found that after a few time thanos store will stop serving requests, in a way that thanos query will timeout on any graph request. Using the (current data) console, i can get data without any problem, as querying directly the prometheus servers.

After some debug i found that stopping the thanos store makes everything work again. I now reverted to thanos store to 0.3.1 and had no problems for now. Thanos query is still in 0.3.2

the thanos store do not crash nor have any useful output, the healtcheck still valid, so i'm not really understanding where it is failing, it just looks like it gets the request and never reply

**Comment by bwplotka** [comment]
Have you read warning in [CHANGELOG.md](https://github.com/improbable-eng/thanos/blob/master/CHANGELOG.md#added-1)?

**Comment by danielmotaleite** [comment]
Sorry, no, i looked in to the https://github.com/improbable-eng/thanos/releases instead, didn't notices that the Changelog had extra info :)

But shouldn't it fail or something? right now the store locks thanos query and make the queries timeout, even queries that i would say would fit in 256MB :) 

Applying right now with higher cache value and checking how it behaves

**Comment by bwplotka** [comment]
It's not about queries it's about how much store gateway has to sync actually.

**Comment by danielmotaleite** [comment]
so the low value blocked store from getting new blocks from the s3 and that is why it locked everything, correct?

the new `--index-cache-size=10GB` value with 0.3.2 did solved my problem, so closing
Thanks for the help!

**Comment by bwplotka** [comment]
Seems so ): the low default looks like hit people - we should maybe increase that.
