### ISSUE TITLE
Support China Azure Storage

### ISSUE THREAD

**Issue by wang415** [improbable-eng/thanos#968]
The current Azure storage feature is supported by the International Edition, which is not supported by the Chinese version

**Comment by wang415** [comment]
type: AZURE
config:
  storage_account: ""
  storage_account_key: ""
  container: ""
  版本: "AzureChina"

**Comment by bwplotka** [comment]
Sorry, can tell us what exactly is missing to have that working for Chinese version of azure? cc @vglafirov

**Comment by adrien-f** [comment]
Hey @wang415 

I think you mean you need to be able to setup the endpoint to point to chinacloudapi.cn like on this page: 

* https://docs.microsoft.com/en-us/azure/china/china-get-started-developer-guide

Is that right ?

**Comment by adrien-f** [comment]
It's me again ! :wave: 

I published a PR addressing this issue: #980

Would you be as kind as to build it yourself and test it from China ?
