### ISSUE TITLE
Gossips Cluster unit test failed

### ISSUE THREAD

**Issue by jojohappy** [improbable-eng/thanos#994]
**Thanos, Prometheus and Golang version used**
Thanos master head - 7a83cda50c8ad0f2bd95f960103a3bc0ac14a33c

**What happened**
Here is the CI [link](https://circleci.com/gh/improbable-eng/thanos/2789?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

The cluster peers could not get the updated metadata, `outdated metadata` error would be thrown.

**How to reproduce it (as minimally and precisely as possible)**:

Not always happended, it is a small probability event. But the CI test would be failed.

**Comment by povilasv** [comment]
IMO we should burn gossip tests with fire and get rid of it :fire:

**Comment by jojohappy** [comment]
@povilasv Agree with you. But at this moment, we have not totally removed the gossip cluster feature.

**Comment by yeya24** [comment]
Same test error here. https://github.com/improbable-eng/thanos/blob/7a83cda50c8ad0f2bd95f960103a3bc0ac14a33c/pkg/cluster/cluster_test.go#L129

**Comment by bwplotka** [comment]
You mean flaky test?

**Comment by povilasv** [comment]
gossip code was removed.
